/**
 * SPEC-048: Búsqueda global — grupo nuevo «Grupos» en el command palette ⌘K
 * (entre Discoveries y Empresas), fila con el nombre del grupo y el nombre de
 * su discovery como contexto muted, navegación a la página del grupo
 * (/discoveries/:discoveryId/groups/:groupId), ocultación con cero hits y
 * navegación de empresa sin ningún discovery en los resultados (modelo v3).
 * Generated by QA Dev agent.
 *
 * Mismo arnés que GlobalSearch.test.tsx: TopBar FUERA de las Routes con
 * probes de destino; api.db.search mockeado; debounce real de 150 ms →
 * findBy/waitFor; scoping por [cmdk-group] (lección SPEC-018: los nombres de
 * discovery se repiten como contexto en otros grupos).
 */
import { render, screen, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { TopBar } from '@/components/layout/TopBar'
import type { SearchResults } from '@/types/search'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

const EMPTY_RESULTS: SearchResults = {
  discoveries: [],
  groups: [],
  companies: [],
  contacts: [],
  interviews: []
}

/** Discovery + grupo + empresa: el contexto del grupo repite el nombre del discovery. */
const RESULTS: SearchResults = {
  discoveries: [{ id: 'd-1', name: 'Vertical Sanidad' }],
  groups: [
    { id: 'g-1', discoveryId: 'd-1', name: 'Sesión Fundadores', discoveryName: 'Vertical Sanidad' }
  ],
  companies: [{ id: 'c-1', name: 'Acmé Córp' }],
  contacts: [],
  interviews: []
}

function setSearch(results: SearchResults): void {
  vi.mocked(mockApi.api.db.search).mockResolvedValue({ ok: true, data: results })
}

function renderTopBar(): RenderResult {
  return render(
    <MemoryRouter initialEntries={['/capture']}>
      <TopBar />
      <Routes>
        <Route path="/capture" element={<div>HOME_PROBE</div>} />
        <Route path="/discoveries/:discoveryId" element={<div>DISCOVERY_PROBE</div>} />
        <Route path="/discoveries/:discoveryId/groups/:groupId" element={<div>GROUP_PROBE</div>} />
        <Route path="/companies/:companyId" element={<div>COMPANY_PROBE</div>} />
      </Routes>
    </MemoryRouter>
  )
}

async function openSearch(user: ReturnType<typeof userEvent.setup>): Promise<HTMLElement> {
  await user.click(screen.getByRole('button', { name: 'Buscar' }))
  await screen.findByRole('dialog')
  return screen.getByPlaceholderText('Buscar…')
}

/** Grupo de cmdk por su heading (scoping obligatorio: los contextos se repiten). */
async function findGroup(heading: string): Promise<HTMLElement> {
  const headingNode = await screen.findByText(heading)
  const group = headingNode.closest('[cmdk-group]')
  if (group === null) {
    throw new Error(`El heading ${heading} debe pertenecer a un grupo de cmdk`)
  }
  return group as HTMLElement
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  setSearch(RESULTS)
})

describe('GlobalSearch (SPEC-048 groups)', () => {
  // SPEC-048 · AC-04 (UI: grupo «Grupos» entre Discoveries y Empresas, fila
  // con el nombre del grupo y el nombre de su discovery como contexto muted)
  it('shows the "Grupos" group between Discoveries and Empresas with the group name and its discovery name as context', async () => {
    const user = userEvent.setup()
    renderTopBar()
    const input = await openSearch(user)

    await user.type(input, 'sesion')

    const group = await findGroup('Grupos')
    expect(within(group).getByText('Sesión Fundadores')).toBeInTheDocument()
    expect(within(group).getByText('Vertical Sanidad')).toBeInTheDocument()

    // Orden fijo de headings: Discoveries → Grupos → Empresas
    const headings = Array.from(document.querySelectorAll('[cmdk-group-heading]')).map(
      (node) => node.textContent
    )
    expect(headings).toEqual(['Discoveries', 'Grupos', 'Empresas'])
  })

  // SPEC-048 · AC-05 (seleccionar un hit de grupo navega a la página del grupo)
  it('navigates to the group page and closes when a group hit is clicked', async () => {
    const user = userEvent.setup()
    renderTopBar()
    const input = await openSearch(user)
    await user.type(input, 'sesion')

    const group = await findGroup('Grupos')
    await user.click(within(group).getByText('Sesión Fundadores'))

    expect(await screen.findByText('GROUP_PROBE')).toBeInTheDocument()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  // SPEC-048 · AC-07 (cero grupos coincidentes → el grupo «Grupos» no se
  // renderiza, patrón de grupos vacíos ocultos de SPEC-018)
  it('hides the "Grupos" group when there are no group hits', async () => {
    const user = userEvent.setup()
    setSearch({ ...RESULTS, groups: [] })
    renderTopBar()
    const input = await openSearch(user)

    await user.type(input, 'sanid')

    const discoveriesGroup = await findGroup('Discoveries')
    expect(within(discoveriesGroup).getByText('Vertical Sanidad')).toBeInTheDocument()
    expect(screen.queryByText('Grupos')).not.toBeInTheDocument()
  })

  // SPEC-048 · AC-02 (UI: en un sistema sin discoveries — cero hits de
  // discovery — el resultado de empresa aparece y navega al detalle global)
  it('shows and navigates a company hit even when the results carry no discoveries', async () => {
    const user = userEvent.setup()
    setSearch({ ...EMPTY_RESULTS, companies: [{ id: 'c-1', name: 'Acmé Córp' }] })
    renderTopBar()
    const input = await openSearch(user)

    await user.type(input, 'acme')

    const group = await findGroup('Empresas')
    expect(screen.queryByText('Discoveries')).not.toBeInTheDocument()
    await user.click(within(group).getByText('Acmé Córp'))

    expect(await screen.findByText('COMPANY_PROBE')).toBeInTheDocument()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })
})
