/**
 * SPEC-058: montaje del banner de onboarding en el detalle de entrevista de
 * un discovery — posición (entre la superficie de grabación y la sección
 * Objetivos), apertura del diálogo de edición con el select «Plantilla de
 * preguntas» desde «Asignar plantilla» (hasta esta spec el diálogo solo
 * existía en los listados) y avance al paso 2 al guardar la plantilla sin
 * recargar. Generated by QA Dev agent.
 *
 * Arnés heredado de InterviewDetailPage.test.tsx (mockApi + MemoryRouter);
 * el comportamiento interno del banner está garantizado por
 * InterviewOnboardingBanner.test.tsx — aquí se verifica el contrato de página.
 */
import { render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import type { Company, Interview, InterviewTemplate } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const TEMPLATE: InterviewTemplate = {
  id: 't-1',
  name: 'Guión base',
  phase: null,
  blocks: [],
  createdAt: '2026-07-01T09:00:00.000Z',
  updatedAt: '2026-07-01T09:00:00.000Z'
}

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactIds: [],
    interviewGroupId: null,
    templateId: null,
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

function renderDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route
            path="/discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
            element={<InterviewDetailPage />}
          />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: interview() })
  vi.mocked(mockApi.api.db.listInterviewTemplates).mockResolvedValue({
    ok: true,
    data: [TEMPLATE]
  })
})

describe('InterviewDetailPage onboarding', () => {
  // SPEC-058 · AC-27: el banner vive entre la superficie de grabación y la
  // sección Objetivos (orden DOM: banner antes de objectives-section)
  it('renders the onboarding banner before the Objetivos section', async () => {
    // SPEC-061 (adaptación): «Objetivos» solo se pinta con guión u objetivos;
    // el AC es POSICIONAL, así que se ejercita con una entrevista que la tiene.
    vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({
      ok: true,
      data: interview({ objectives: ['Objetivo cero'] })
    })
    renderDetail()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    const objectives = await screen.findByTestId('objectives-section')
    expect(
      banner.compareDocumentPosition(objectives) & Node.DOCUMENT_POSITION_FOLLOWING
    ).toBeTruthy()
  })

  // SPEC-058 · AC-14: «Asignar plantilla» abre el diálogo de edición con el
  // select «Plantilla de preguntas» (EditInterviewDialog no lo tiene: la
  // página monta InterviewFormDialog en modo edición)
  it('opens the edit dialog with the "Plantilla de preguntas" select from "Asignar plantilla"', async () => {
    const user = userEvent.setup()
    renderDetail()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    expect(banner).toHaveAttribute('data-step', '1')
    await user.click(within(banner).getByTestId('onboarding-step-action'))

    const dialog = await screen.findByRole('dialog')
    expect(within(dialog).getByText('Editar entrevista')).toBeInTheDocument()
    expect(
      within(dialog).getByRole('combobox', { name: 'Plantilla de preguntas' })
    ).toBeInTheDocument()
  })

  // SPEC-058 · AC-15: guardar con plantilla avanza el banner al paso 2 sin
  // recargar (updateInterview con templateId + onInterviewUpdated)
  it('moves the banner to step 2 after saving a template from the dialog', async () => {
    const withTemplate = interview({ templateId: 't-1' })
    vi.mocked(mockApi.api.db.updateInterview).mockResolvedValue({
      ok: true,
      data: withTemplate
    })
    const user = userEvent.setup()
    renderDetail()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    await user.click(within(banner).getByTestId('onboarding-step-action'))
    const dialog = await screen.findByRole('dialog')

    await user.click(within(dialog).getByRole('combobox', { name: 'Plantilla de preguntas' }))
    await user.click(await screen.findByRole('option', { name: 'Guión base' }))
    await user.click(within(dialog).getByRole('button', { name: 'Guardar' }))

    await waitFor(() =>
      expect(mockApi.api.db.updateInterview).toHaveBeenCalledWith(
        'i-1',
        expect.objectContaining({ templateId: 't-1' })
      )
    )
    // El Dialog se cierra y el banner avanza al paso 2 sin recargar la página
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    await waitFor(() =>
      expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '2')
    )
  })
})
