/**
 * SPEC-058: banner de onboarding guiado — derivación de los 7 pasos desde el
 * estado real de la entrevista, acciones propias (asignar plantilla, generar
 * guión, confirmar objetivos, iniciar grabación, ocultar) y ocultamiento
 * (grabación en curso / onboardingHiddenAt). Las acciones espejadas de las
 * secciones (nota/evaluación, vía onboardingBridge) se cubren en
 * OnboardingBannerBridge.test.tsx; el montaje en las páginas, en
 * InterviewDetailPage.onboarding.test.tsx y CaptureDetailPage.onboarding.test.tsx.
 * Generated by QA Dev agent.
 *
 * Frontera de mocking: bridge window.api (installMockApi) + un
 * RecordingController fabricado (el banner solo lee permissions/capturing y
 * dispara handleStart — SPEC-055 sigue siendo la fuente de estado real).
 */
import { act, render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { InterviewOnboardingBanner } from '@/components/interviews/InterviewOnboardingBanner'
import type { RecordingController } from '@/hooks/useRecordingController'
import type { Interview } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactIds: [],
    interviewGroupId: null,
    templateId: null,
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

/** Fixtures por paso (condiciones de la tabla de la spec, sección 01). */
const STEP_FIXTURES: Record<number, Interview> = {
  1: interview(),
  2: interview({ templateId: 't-1' }),
  3: interview({ templateId: 't-1', scriptMarkdown: '# Guión', status: 'prepared' }),
  4: interview({
    templateId: 't-1',
    scriptMarkdown: '# Guión',
    status: 'prepared',
    objectivesConfirmedAt: '2026-07-27T10:00:00.000Z'
  }),
  5: interview({
    templateId: 't-1',
    scriptMarkdown: '# Guión',
    status: 'recorded',
    objectives: ['Objetivo cero'],
    objectivesConfirmedAt: '2026-07-27T10:00:00.000Z',
    wavPath: '/tmp/rec.wav',
    transcriptPath: '/tmp/rec.transcript.json'
  }),
  6: interview({
    templateId: 't-1',
    scriptMarkdown: '# Guión',
    status: 'summarized',
    objectives: ['Objetivo cero'],
    objectivesConfirmedAt: '2026-07-27T10:00:00.000Z',
    wavPath: '/tmp/rec.wav',
    transcriptPath: '/tmp/rec.transcript.json'
  }),
  7: interview({
    templateId: 't-1',
    scriptMarkdown: '# Guión',
    status: 'summarized',
    objectives: ['Objetivo cero'],
    objectivesConfirmedAt: '2026-07-27T10:00:00.000Z',
    wavPath: '/tmp/rec.wav',
    transcriptPath: '/tmp/rec.transcript.json',
    objectiveResults: [{ met: true, reason: 'Se cubrió con hechos.' }]
  })
}

/** Controller mínimo: el banner solo consume permissions/capturing/handleStart. */
function makeController(overrides: Partial<RecordingController> = {}): RecordingController {
  return {
    permissions: { microphone: 'granted', systemAudio: 'granted' },
    devices: [],
    selectedDeviceId: '__default__',
    setSelectedDeviceId: vi.fn(),
    handleStart: vi.fn(),
    capturing: false,
    recorded: false,
    status: 'idle',
    elapsedSeconds: 0,
    levels: { microphone: 0, system: 0 },
    error: null,
    result: null,
    stop: vi.fn(async () => null),
    displayLatency: null,
    requestNewRecording: vi.fn(),
    handleShowInFinder: vi.fn(),
    transcription: {
      status: 'inactive',
      lines: [],
      partials: { mic: '', system: '' },
      error: null,
      degraded: false
    },
    assistant: {
      state: 'idle',
      queue: [],
      error: null,
      usage: null,
      pauseLimitUsd: null,
      setPinned: vi.fn(),
      resolveItem: vi.fn(),
      resume: vi.fn()
    },
    consentDialogOpen: false,
    handleConsentCancel: vi.fn(),
    handleConsentConfirm: vi.fn(),
    closeDialogOpen: false,
    cancelClose: vi.fn(),
    confirmClose: vi.fn(async () => {}),
    ...overrides
  }
}

interface RenderOptions {
  controller?: RecordingController
  onAssignTemplate?: () => void
  onInterviewUpdated?: (value: Interview) => void
}

function renderBanner(value: Interview, options: RenderOptions = {}): RenderResult {
  return render(
    <TooltipProvider>
      <InterviewOnboardingBanner
        interview={value}
        onInterviewUpdated={options.onInterviewUpdated ?? vi.fn()}
        controller={options.controller ?? makeController()}
        onAssignTemplate={options.onAssignTemplate ?? vi.fn()}
      />
      <Toaster />
    </TooltipProvider>
  )
}

function rerenderBanner(result: RenderResult, value: Interview, options: RenderOptions = {}): void {
  result.rerender(
    <TooltipProvider>
      <InterviewOnboardingBanner
        interview={value}
        onInterviewUpdated={options.onInterviewUpdated ?? vi.fn()}
        controller={options.controller ?? makeController()}
        onAssignTemplate={options.onAssignTemplate ?? vi.fn()}
      />
      <Toaster />
    </TooltipProvider>
  )
}

/** Habilita la clave de Anthropic (el default del mock es SIN clave). */
function grantAnthropicKey(): void {
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
})

describe('InterviewOnboardingBanner', () => {
  describe('step derivation', () => {
    // SPEC-058 · AC-01
    it('shows step 1 "Asigna una plantilla de preguntas" with "Asignar plantilla" when there is no template and no script', async () => {
      const onAssignTemplate = vi.fn()
      renderBanner(STEP_FIXTURES[1], { onAssignTemplate })

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '1')
      expect(within(banner).getByText('Paso 1 de 7')).toBeInTheDocument()
      expect(within(banner).getByText('Asigna una plantilla de preguntas')).toBeInTheDocument()
      const action = within(banner).getByTestId('onboarding-step-action')
      expect(action).toHaveTextContent('Asignar plantilla')

      const user = userEvent.setup()
      await user.click(action)
      expect(onAssignTemplate).toHaveBeenCalledTimes(1)
    })

    // SPEC-058 · AC-02 (la mitad "misma generación + ambos botones" vive en
    // OnboardingBannerBridge.test.tsx, AC-16)
    it('shows step 2 "Genera el guión antes de la entrevista" with "Generar guión" when a template is set and there is no script', async () => {
      grantAnthropicKey()
      renderBanner(STEP_FIXTURES[2])

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '2')
      expect(within(banner).getByText('Genera el guión antes de la entrevista')).toBeInTheDocument()
      expect(within(banner).getByTestId('onboarding-step-action')).toHaveTextContent(
        'Generar guión'
      )
    })

    // SPEC-058 · AC-03
    it('shows step 3 "Revisa los objetivos" with "Objetivos revisados" when the script exists and objectives are not confirmed', async () => {
      renderBanner(STEP_FIXTURES[3])

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '3')
      expect(within(banner).getByText('Revisa los objetivos')).toBeInTheDocument()
      expect(within(banner).getByTestId('onboarding-step-action')).toHaveTextContent(
        'Objetivos revisados'
      )
    })

    // SPEC-058 · AC-04
    it('shows step 4 "¡Todo listo para la entrevista!" with "Iniciar grabación" when objectives are confirmed and there is no recording', async () => {
      renderBanner(STEP_FIXTURES[4])

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '4')
      expect(within(banner).getByText('¡Todo listo para la entrevista!')).toBeInTheDocument()
      expect(within(banner).getByTestId('onboarding-step-action')).toHaveTextContent(
        'Iniciar grabación'
      )
    })

    // SPEC-058 · AC-05
    it('shows step 5 "Genera la nota de la entrevista" with "Generar nota" when recorded with transcript and no note', async () => {
      renderBanner(STEP_FIXTURES[5])

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '5')
      expect(banner).not.toHaveAttribute('data-degraded')
      expect(within(banner).getByText('Genera la nota de la entrevista')).toBeInTheDocument()
      expect(within(banner).getByTestId('onboarding-step-action')).toHaveTextContent('Generar nota')
    })

    // SPEC-058 · AC-06
    it('shows the degraded step 5 "La grabación no tiene transcripción" with "Escribir nota" when recorded without transcript', async () => {
      renderBanner(interview({ ...STEP_FIXTURES[5], transcriptPath: null }))

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '5')
      expect(banner).toHaveAttribute('data-degraded', 'true')
      expect(within(banner).getByText('La grabación no tiene transcripción')).toBeInTheDocument()
      expect(
        within(banner).getByText(
          'La transcripción falló durante la grabación, así que la nota no se puede generar con IA. Puedes escribirla a mano en la sección Nota.'
        )
      ).toBeInTheDocument()
      expect(within(banner).getByTestId('onboarding-step-action')).toHaveTextContent(
        'Escribir nota'
      )
    })

    // SPEC-058 · AC-07
    it('shows step 6 "Evalúa los objetivos" with "Evaluar objetivos" when the note exists and there are no objective results', async () => {
      renderBanner(STEP_FIXTURES[6])

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '6')
      expect(within(banner).getByText('Evalúa los objetivos')).toBeInTheDocument()
      expect(within(banner).getByTestId('onboarding-step-action')).toHaveTextContent(
        'Evaluar objetivos'
      )
    })

    // SPEC-058 · AC-08
    it('shows step 7 "¡Entrevista finalizada!" with "Ocultar" when the note exists and objectives are evaluated', async () => {
      renderBanner(STEP_FIXTURES[7])

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '7')
      expect(within(banner).getByText('¡Entrevista finalizada!')).toBeInTheDocument()
      expect(within(banner).getByTestId('onboarding-hide-button')).toHaveTextContent('Ocultar')
    })

    // SPEC-058 · AC-09: el paso 1 solo aplica mientras no hay guión
    it('does not fall back to step 1 when the template was unassigned after the script was generated', async () => {
      renderBanner(interview({ templateId: null, scriptMarkdown: '# Guión', status: 'prepared' }))

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '3')
    })

    // SPEC-058 · AC-10: evaluación previa a la nota → 5 salta directo a 7
    it('jumps from step 5 straight to step 7 when the note is generated with objective results already present', async () => {
      const evaluatedBeforeNote = interview({
        ...STEP_FIXTURES[5],
        objectiveResults: [{ met: true, reason: 'Cubierto en vivo.' }]
      })
      const result = renderBanner(evaluatedBeforeNote)

      const banner = await screen.findByTestId('interview-onboarding-banner')
      expect(banner).toHaveAttribute('data-step', '5')

      rerenderBanner(result, interview({ ...evaluatedBeforeNote, status: 'summarized' }))
      await waitFor(() =>
        expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '7')
      )
    })

    // SPEC-058 · AC-11: 7 segmentos — hechos sólidos, actual atenuado, resto
    // pendientes. El estado visual vive SOLO en clases (elemento aria-hidden
    // sin texto): la aserción por clase es aquí el único observable.
    it('renders 7 progress segments with done/current/pending states for the current step', async () => {
      renderBanner(STEP_FIXTURES[3])

      const banner = await screen.findByTestId('interview-onboarding-banner')
      const segments = Array.from(banner.querySelectorAll('[aria-hidden="true"] > span'))
      expect(segments).toHaveLength(7)
      const done = segments.filter(
        (segment) =>
          segment.className.includes('bg-foreground') && !segment.className.includes('opacity-40')
      )
      const current = segments.filter((segment) => segment.className.includes('opacity-40'))
      const pending = segments.filter((segment) => segment.className.includes('bg-border'))
      expect(done).toHaveLength(2)
      expect(current).toHaveLength(1)
      expect(pending).toHaveLength(4)
    })

    // SPEC-058 · AC-12
    it('does not render while a recording is in progress', async () => {
      renderBanner(STEP_FIXTURES[4], {
        controller: makeController({ capturing: true, status: 'recording' })
      })

      // La condición es síncrona pero el banner resuelve efectos: se asegura
      // el asentamiento con un tick del bridge antes del assert negativo.
      await act(async () => {
        await Promise.resolve()
      })
      expect(screen.queryByTestId('interview-onboarding-banner')).not.toBeInTheDocument()
    })

    // SPEC-058 · AC-13
    it('does not render when the banner was hidden for the interview', async () => {
      renderBanner(
        interview({ ...STEP_FIXTURES[7], onboardingHiddenAt: '2026-07-27T12:00:00.000Z' })
      )

      await act(async () => {
        await Promise.resolve()
      })
      expect(screen.queryByTestId('interview-onboarding-banner')).not.toBeInTheDocument()
    })

    // SPEC-058 · AC-25
    it('never offers "Ocultar" in steps 1 to 6', async () => {
      for (const step of [1, 2, 3, 4, 5, 6]) {
        const result = renderBanner(STEP_FIXTURES[step])
        const banner = await screen.findByTestId('interview-onboarding-banner')
        expect(banner).toHaveAttribute('data-step', String(step))
        expect(within(banner).queryByTestId('onboarding-hide-button')).not.toBeInTheDocument()
        result.unmount()
      }
    })
  })

  describe('step actions', () => {
    // SPEC-058 · AC-16 (disparo; el reflejo en ScriptSection se verifica en
    // OnboardingBannerBridge.test.tsx) — reutiliza la autogeneración SPEC-033
    it('fires the shared script generation and shows "Generando guión…" disabled while the events report progress', async () => {
      grantAnthropicKey()
      renderBanner(STEP_FIXTURES[2])
      const user = userEvent.setup()

      // Referencias frescas: el botón se remonta al alternar disabled/enabled
      // (wrapper de Tooltip — lección SPEC-029)
      await screen.findByTestId('onboarding-step-action')
      await waitFor(() => expect(screen.getByTestId('onboarding-step-action')).toBeEnabled())
      await user.click(screen.getByTestId('onboarding-step-action'))
      expect(mockApi.api.llm.autoGenerateScript).toHaveBeenCalledWith('i-1')

      act(() => {
        mockApi.emitScriptGeneration({ interviewId: 'i-1', status: 'generating' })
      })
      const busyAction = screen.getByTestId('onboarding-step-action')
      expect(busyAction).toHaveTextContent('Generando guión…')
      expect(busyAction).toBeDisabled()
    })

    // SPEC-058 · AC-17 (mismo motivo que ScriptSection; 1 solo hover por it —
    // lección Radix grace area en jsdom)
    it('disables "Generar guión" with the key tooltip when no Anthropic key is configured', async () => {
      renderBanner(STEP_FIXTURES[2])
      const user = userEvent.setup()

      // Referencias frescas: el botón se remonta al pasar a disabled+Tooltip
      await screen.findByTestId('onboarding-step-action')
      await waitFor(() => expect(screen.getByTestId('onboarding-step-action')).toBeDisabled())
      await user.hover(screen.getByTestId('onboarding-step-action').parentElement as HTMLElement)
      // findAll: Radix duplica el texto del tooltip (contenido + copia accesible)
      expect(
        (
          await screen.findAllByText(
            'Configura tu clave de Anthropic en Ajustes para generar el guión'
          )
        ).length
      ).toBeGreaterThanOrEqual(1)
    })

    // SPEC-058 · AC-18
    it('persists objectivesConfirmedAt on "Objetivos revisados" and moves to step 4 without reloading', async () => {
      const confirmed = interview({
        ...STEP_FIXTURES[3],
        objectivesConfirmedAt: '2026-07-27T12:00:00.000Z'
      })
      vi.mocked(mockApi.api.db.confirmInterviewObjectives).mockResolvedValue({
        ok: true,
        data: confirmed
      })
      const onInterviewUpdated = vi.fn()
      const result = renderBanner(STEP_FIXTURES[3], { onInterviewUpdated })
      const user = userEvent.setup()

      await user.click(await screen.findByTestId('onboarding-step-action'))
      await waitFor(() =>
        expect(mockApi.api.db.confirmInterviewObjectives).toHaveBeenCalledWith('i-1')
      )
      await waitFor(() => expect(onInterviewUpdated).toHaveBeenCalledWith(confirmed))

      // El padre refleja la entrevista actualizada (sin recargar la página)
      rerenderBanner(result, confirmed, { onInterviewUpdated })
      await waitFor(() =>
        expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '4')
      )
    })

    // SPEC-058 · AC-19: la MISMA grabación que la top bar (mismo controller)
    it('starts the recording through the page controller on "Iniciar grabación"', async () => {
      const controller = makeController()
      renderBanner(STEP_FIXTURES[4], { controller })
      const user = userEvent.setup()

      await user.click(await screen.findByTestId('onboarding-step-action'))
      expect(controller.handleStart).toHaveBeenCalledTimes(1)
    })

    // SPEC-058 · AC-20 (criterio permsBlocked de SPEC-055-iter-2; 1 hover)
    it('disables "Iniciar grabación" with the permissions tooltip under a hard permission denial', async () => {
      const controller = makeController({
        permissions: { microphone: 'denied', systemAudio: 'granted' }
      })
      renderBanner(STEP_FIXTURES[4], { controller })
      const user = userEvent.setup()

      const action = await screen.findByTestId('onboarding-step-action')
      expect(action).toBeDisabled()
      await user.hover(action.parentElement as HTMLElement)
      // findAll: Radix duplica el texto del tooltip (contenido + copia accesible)
      expect(
        (
          await screen.findAllByText(
            'Hay permisos de audio denegados: concédelos en Ajustes del Sistema'
          )
        ).length
      ).toBeGreaterThanOrEqual(1)
      expect(controller.handleStart).not.toHaveBeenCalled()
    })

    // SPEC-058 · AC-24
    it('persists onboardingHiddenAt on "Ocultar" and the banner disappears', async () => {
      const hidden = interview({
        ...STEP_FIXTURES[7],
        onboardingHiddenAt: '2026-07-27T12:00:00.000Z'
      })
      vi.mocked(mockApi.api.db.hideInterviewOnboarding).mockResolvedValue({
        ok: true,
        data: hidden
      })
      const onInterviewUpdated = vi.fn()
      const result = renderBanner(STEP_FIXTURES[7], { onInterviewUpdated })
      const user = userEvent.setup()

      await user.click(await screen.findByTestId('onboarding-hide-button'))
      await waitFor(() =>
        expect(mockApi.api.db.hideInterviewOnboarding).toHaveBeenCalledWith('i-1')
      )
      await waitFor(() => expect(onInterviewUpdated).toHaveBeenCalledWith(hidden))

      rerenderBanner(result, hidden, { onInterviewUpdated })
      await waitFor(() =>
        expect(screen.queryByTestId('interview-onboarding-banner')).not.toBeInTheDocument()
      )
    })

    // SPEC-058 · AC-26
    it('shows an error toast and stays on the current step when persisting the mark fails', async () => {
      vi.mocked(mockApi.api.db.confirmInterviewObjectives).mockResolvedValue({
        ok: false,
        error: { kind: 'storage', message: 'No se pudo escribir el almacén' }
      })
      const onInterviewUpdated = vi.fn()
      renderBanner(STEP_FIXTURES[3], { onInterviewUpdated })
      const user = userEvent.setup()

      await user.click(await screen.findByTestId('onboarding-step-action'))
      expect(await screen.findByText('No se pudo escribir el almacén')).toBeInTheDocument()
      expect(onInterviewUpdated).not.toHaveBeenCalled()
      expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '3')
    })
  })
})
