/**
 * SPEC-049: Permisos no concedidos visibles — detalle de entrevista.
 * ACs de página: el botón «Abrir Ajustes del Sistema» comparte fila con los
 * badges de permisos en la sección Grabación (AC-02) y el Alert de error de
 * permiso al iniciar la grabación se muestra bajo la cabecera, antes de
 * Objetivos (AC-15) — misma consistencia entre superficies que la captura.
 * Arnés: InterviewDetailPage en su ruta anidada real (patrón
 * RecordingSection.test.tsx, SPEC-015); fronteras de mocking idénticas:
 * permissionsService/captureService/wavRecorderService + bridge window.api.
 * SPEC-019: todo arranque atraviesa el aviso de consentimiento.
 * Generated by QA Dev agent.
 */
import { render, screen, within, type RenderResult } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Layout } from '@/components/layout/Layout'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import { listAudioInputDevices } from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { Company, Interview } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

const recorderMock = vi.hoisted(() => ({
  start: vi.fn(),
  stop: vi.fn(),
  getLevels: vi.fn(),
  durationSeconds: 0
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = recorderMock.start
    stop = recorderMock.stop
    getLevels = recorderMock.getLevels
    get durationSeconds(): number {
      return recorderMock.durationSeconds
    }
    get samplesWritten(): number {
      return recorderMock.durationSeconds * 16000
    }
  }
}))

let mockApi: MockApiHandle

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const INTERVIEW: Interview = {
  id: 'i-1',
  discoveryId: 'd-1',
  companyId: 'c-1',
  contactIds: [],
  interviewGroupId: null,
  templateId: null,
  title: 'Discovery con Acme',
  status: 'draft',
  scriptMarkdown: null,
  objectives: [],
  wavPath: null,
  transcriptPath: null,
  createdAt: '2026-07-04T10:00:00.000Z',
  updatedAt: '2026-07-04T10:00:00.000Z'
}

/**
 * SPEC-055: los controles de preparación (badges + OpenSettingsButton + micro)
 * viven en la top bar, así que el arnés monta la ruta BAJO <Layout/> para que el
 * portal del slot exista.
 */
function renderDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route
              path="discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
              element={<InterviewDetailPage />}
            />
          </Route>
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

/** El banner de la top bar (donde viven los controles de preparación). */
function topBar(): HTMLElement {
  return screen.getByRole('banner')
}

beforeEach(() => {
  vi.clearAllMocks()
  // Aislamiento del aviso de consentimiento (SPEC-019)
  window.localStorage.clear()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: INTERVIEW })
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  // Sin Alert de clave en ScriptSection para no colisionar con los role=alert
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  recorderMock.start.mockResolvedValue(undefined)
  recorderMock.stop.mockResolvedValue(undefined)
  recorderMock.getLevels.mockReturnValue({ microphone: 42, system: 17 })
})

describe('InterviewDetailPage (SPEC-049 permission visibility)', () => {
  // SPEC-049 · AC-02 (SPEC-055: badges + OpenSettingsButton + micro viven en la
  // top bar; «Iniciar grabación» en la cabecera)
  it('renders "Abrir Ajustes del Sistema" to the right of the permission badges in the top bar when a permission is not granted', async () => {
    vi.mocked(getPermissionsStatus).mockResolvedValue({
      microphone: 'granted',
      systemAudio: 'denied'
    })
    renderDetail()

    const controls = await within(topBar()).findByTestId('topbar-capture-controls')
    // El badge destructive ya cargó (el snapshot resolvió)
    expect(await within(controls).findByText('No concedido')).toBeInTheDocument()
    const button = within(controls).getByTestId('open-settings-button')
    expect(button).toHaveTextContent('Abrir Ajustes del Sistema')
    // El botón va a la derecha de los badges, dentro del contenedor de la top bar
    const systemBadgeLabel = within(controls).getByText('Audio del sistema')
    expect(
      systemBadgeLabel.compareDocumentPosition(button) & Node.DOCUMENT_POSITION_FOLLOWING
    ).toBeTruthy()
    // SPEC-055-iter-1: el selector queda en la top bar pero DISABLED sin
    // permisos; «Iniciar grabación» también en la top bar (disabled)
    expect(within(controls).getByRole('combobox', { name: 'Micrófono' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Iniciar grabación' })).toBeInTheDocument()
  })

  // SPEC-049 · AC-15 (derogado por SPEC-055-iter-1: el bloqueo por permiso es
  // preventivo — «Iniciar grabación» disabled — no reactivo por Alert al pulsar)
  it('disables "Iniciar grabación" and shows "Abrir Ajustes del Sistema" when a permission is denied', async () => {
    vi.mocked(getPermissionsStatus).mockResolvedValue({
      microphone: 'denied',
      systemAudio: 'granted'
    })
    renderDetail()

    const controls = await within(topBar()).findByTestId('topbar-capture-controls')
    expect(
      await within(controls).findByRole('button', { name: 'Iniciar grabación' })
    ).toBeDisabled()
    expect(within(controls).getByTestId('open-settings-button')).toBeInTheDocument()
    // No arranca ni aparece Alert reactivo (el bloqueo es preventivo)
    expect(screen.queryByRole('button', { name: 'Detener' })).not.toBeInTheDocument()
    expect(recorderMock.start).not.toHaveBeenCalled()
    expect(screen.queryByTestId('permission-error-alert')).not.toBeInTheDocument()
  })
})
