/**
 * SPEC-058: acciones del banner espejadas de las secciones vía el puente
 * (onboardingBridge) — misma composición que las páginas de detalle: banner +
 * ObjectivesSection + NoteScriptSections dentro de OnboardingBridgeProvider,
 * con la entrevista compartida en el estado del arnés (onInterviewUpdated la
 * propaga a todos, como hacen las páginas). Cubre: generación del guión
 * espejada de la sección (AC-16 y AC-17, reescritos por SPEC-058-iter-1, más
 * los dos sentidos del defecto que corrige — disparo desde la sección y
 * autogeneración SPEC-033), generación de la nota espejada (AC-21), nota
 * manual del paso degradado (AC-22, la parte automatizable), evaluación
 * espejada (AC-23) y la jerarquía primary/outline (AC-29).
 * Generated by QA Dev agent.
 *
 * Frontera de mocking: bridge window.api (installMockApi) + controller
 * fabricado. Las secciones se montan REALES (sus suites propias cubren su
 * comportamiento interno).
 */
import React, { useState } from 'react'
import { act, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { InterviewOnboardingBanner } from '@/components/interviews/InterviewOnboardingBanner'
import { NoteScriptSections } from '@/components/interviews/NoteScriptSections'
import { ObjectivesSection } from '@/components/interviews/ObjectivesSection'
import { OnboardingBridgeProvider } from '@/components/interviews/onboardingBridge'
import type { RecordingController } from '@/hooks/useRecordingController'
import type { Interview, Note, NoteTemplate } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactIds: [],
    interviewGroupId: null,
    templateId: 't-1',
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

const RECORDED: Interview = interview({
  scriptMarkdown: '# Guión',
  status: 'recorded',
  objectives: ['Objetivo cero'],
  objectivesConfirmedAt: '2026-07-27T10:00:00.000Z',
  wavPath: '/tmp/rec.wav',
  transcriptPath: '/tmp/rec.transcript.json'
})

const NOTE: Note = {
  id: 'n-1',
  interviewId: 'i-1',
  contentMarkdown: '# Nota de la entrevista',
  createdAt: '2026-07-27T11:00:00.000Z',
  updatedAt: '2026-07-27T11:00:00.000Z'
}

const NOTE_TEMPLATE: NoteTemplate = {
  id: 'nt-1',
  name: 'Resumen Mom Test',
  context: 'Notas de descubrimiento',
  sections: [{ title: 'Problemas', description: 'Problemas detectados con hechos.' }],
  createdAt: '2026-07-01T09:00:00.000Z',
  updatedAt: '2026-07-01T09:00:00.000Z'
}

function makeController(overrides: Partial<RecordingController> = {}): RecordingController {
  return {
    permissions: { microphone: 'granted', systemAudio: 'granted' },
    devices: [],
    selectedDeviceId: '__default__',
    setSelectedDeviceId: vi.fn(),
    handleStart: vi.fn(),
    capturing: false,
    recorded: false,
    status: 'idle',
    elapsedSeconds: 0,
    levels: { microphone: 0, system: 0 },
    error: null,
    result: null,
    stop: vi.fn(async () => null),
    displayLatency: null,
    requestNewRecording: vi.fn(),
    handleShowInFinder: vi.fn(),
    transcription: {
      status: 'inactive',
      lines: [],
      partials: { mic: '', system: '' },
      error: null,
      degraded: false
    },
    assistant: {
      state: 'idle',
      queue: [],
      error: null,
      usage: null,
      pauseLimitUsd: null,
      setPinned: vi.fn(),
      resolveItem: vi.fn(),
      resume: vi.fn()
    },
    consentDialogOpen: false,
    handleConsentCancel: vi.fn(),
    handleConsentConfirm: vi.fn(),
    closeDialogOpen: false,
    cancelClose: vi.fn(),
    confirmClose: vi.fn(async () => {}),
    ...overrides
  }
}

/**
 * Arnés con la MISMA composición que las páginas de detalle (SPEC-058):
 * la entrevista vive en el estado y onInterviewUpdated la propaga a todos.
 */
function Harness({ initial }: { initial: Interview }): React.ReactElement {
  const [current, setCurrent] = useState(initial)
  return (
    <OnboardingBridgeProvider>
      <InterviewOnboardingBanner
        interview={current}
        onInterviewUpdated={setCurrent}
        controller={makeController()}
        onAssignTemplate={vi.fn()}
      />
      <ObjectivesSection interview={current} onInterviewUpdated={setCurrent} />
      {/* SPEC-061: el arnés reproduce la composición real, con la página sin
          grabar (el banner visible es justo el escenario que espeja) */}
      <NoteScriptSections interview={current} onInterviewUpdated={setCurrent} capturing={false} />
    </OnboardingBridgeProvider>
  )
}

function renderHarness(initial: Interview): void {
  render(
    <TooltipProvider>
      <MemoryRouter>
        <Harness initial={initial} />
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

function grantAnthropicKey(): void {
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
}

/** Nota "persistida" mutable: getNoteByInterview y createNote la comparten. */
let storedNote: Note | null

function deferred<T>(): { promise: Promise<T>; resolve: (value: T) => void } {
  let resolve!: (value: T) => void
  const promise = new Promise<T>((resolver) => {
    resolve = resolver
  })
  return { promise, resolve }
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  storedNote = null
  vi.mocked(mockApi.api.db.getNoteByInterview).mockImplementation(() =>
    Promise.resolve({ ok: true, data: storedNote })
  )
})

describe('InterviewOnboardingBanner bridge', () => {
  /**
   * Espera a que la sección Guión haya registrado su acción en el puente.
   * SPEC-061: con el banner visible la sección ya NO pinta botones, así que la
   * señal deja de ser «su botón está habilitado» y pasa a ser su heading
   * (asíncrono: NoteScriptSections resuelve getNoteByInterview antes de
   * montarla) seguido del botón espejado habilitado — entre el montaje de la
   * sección y la resolución de la clave el registro lo deja deshabilitado, así
   * que este orden nunca deja pasar el estado «aún sin registrar» (en el que
   * el botón del banner está habilitado pero es no-op).
   */
  const waitForScriptActionMirrored = async (banner: HTMLElement): Promise<void> => {
    await screen.findByRole('heading', { name: 'Guión' })
    await waitFor(() => expect(within(banner).getByTestId('onboarding-step-action')).toBeEnabled())
  }

  // SPEC-058 · AC-16, reescrito por SPEC-058-iter-1: el botón del banner
  // ejecuta la generación MANUAL de la sección (el mismo `llm:generate-script`
  // que su botón), no el invoke silencioso de la autogeneración.
  it('generates the script through the shared pipeline and both buttons show "Generando guión…" until done', async () => {
    grantAnthropicKey()
    const pending = deferred<Awaited<ReturnType<typeof mockApi.api.llm.generateScript>>>()
    vi.mocked(mockApi.api.llm.generateScript).mockReturnValue(pending.promise)
    renderHarness(interview())
    const user = userEvent.setup()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    expect(banner).toHaveAttribute('data-step', '2')
    // La sección Guión debe haber registrado su acción antes del click
    await waitForScriptActionMirrored(banner)
    await user.click(within(banner).getByTestId('onboarding-step-action'))

    await waitFor(() => expect(mockApi.api.llm.generateScript).toHaveBeenCalledWith('i-1'))
    expect(mockApi.api.llm.autoGenerateScript).not.toHaveBeenCalled()
    // Banner + sección Guión reflejan el progreso a la vez (SPEC-061: el de la
    // sección es el indicador de su empty state, ya sin botón de cabecera)
    await waitFor(() =>
      expect(screen.getAllByText('Generando guión…').length).toBeGreaterThanOrEqual(2)
    )
    expect(within(banner).getByTestId('onboarding-step-action')).toBeDisabled()

    const generated = interview({ scriptMarkdown: '# Guión nuevo', status: 'prepared' })
    act(() => {
      pending.resolve({ ok: true, data: generated })
    })
    // La entrevista actualizada avanza el banner al paso 3 (sin recargar)
    await waitFor(() =>
      expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '3')
    )
  })

  // SPEC-058-iter-1 · el defecto corregido (disparo desde el BOTÓN de la
  // sección Guión) queda DEROGADO por SPEC-061: con el banner visible la
  // sección ya no pinta ese botón, así que el escenario es inalcanzable por
  // construcción. La dirección que verificaba —estado propiedad de la sección
  // reflejado en el banner— sigue cubierta por el test de autogeneración de
  // aquí abajo (eventos SPEC-033, mismo estado, misma vía de espejo).

  // SPEC-058-iter-1 · la autogeneración de SPEC-033 sigue espejándose
  it('reflects in the banner the SPEC-033 auto-generation driven by events', async () => {
    grantAnthropicKey()
    renderHarness(interview())

    const banner = await screen.findByTestId('interview-onboarding-banner')
    await waitForScriptActionMirrored(banner)

    act(() => {
      mockApi.emitScriptGeneration({ interviewId: 'i-1', status: 'generating' })
    })
    await waitFor(() => {
      const action = within(banner).getByTestId('onboarding-step-action')
      expect(action).toHaveTextContent('Generando guión…')
      expect(action).toBeDisabled()
    })
    expect(mockApi.api.llm.generateScript).not.toHaveBeenCalled()

    const generated = interview({ scriptMarkdown: '# Guión auto', status: 'prepared' })
    act(() => {
      mockApi.emitScriptGeneration({ interviewId: 'i-1', status: 'done', interview: generated })
    })
    await waitFor(() =>
      expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '3')
    )
  })

  // SPEC-058 · AC-17, reubicado aquí por SPEC-058-iter-1: el motivo ya no lo
  // resuelve el banner sino la sección, así que hace falta la composición real
  // (1 solo hover por it — lección Radix grace area en jsdom)
  it('disables the mirrored "Generar guión" with the same key tooltip as the Guión section', async () => {
    vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
      ok: true,
      data: { hasAnthropicKey: false }
    })
    renderHarness(interview())
    const user = userEvent.setup()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    await waitFor(() => expect(within(banner).getByTestId('onboarding-step-action')).toBeDisabled())
    await user.hover(
      within(banner).getByTestId('onboarding-step-action').parentElement as HTMLElement
    )
    // findAll: Radix duplica el texto del tooltip (contenido + copia accesible)
    expect(
      (
        await screen.findAllByText(
          'Configura tu clave de Anthropic en Ajustes para generar el guión'
        )
      ).length
    ).toBeGreaterThanOrEqual(1)
  })

  // SPEC-058 · AC-21: la acción espejada dispara la MISMA generación de nota
  it('generates the note through NoteSection and both buttons show "Generando nota…" until done', async () => {
    grantAnthropicKey()
    vi.mocked(mockApi.api.db.listNoteTemplates).mockResolvedValue({
      ok: true,
      data: [NOTE_TEMPLATE]
    })
    const pending = deferred<Awaited<ReturnType<typeof mockApi.api.llm.generateNote>>>()
    vi.mocked(mockApi.api.llm.generateNote).mockReturnValue(pending.promise)
    renderHarness(RECORDED)
    const user = userEvent.setup()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    expect(banner).toHaveAttribute('data-step', '5')
    // La sección Nota debe estar lista (registro del puente hecho) antes del
    // click. Referencias SIEMPRE frescas (remontaje al habilitarse, lección
    // SPEC-029) y query de SECCIÓN: el botón espejado del banner también se
    // llama «Generar nota» → se excluye por su testid.
    const sectionGenerate = (): HTMLElement => {
      const match = screen
        .getAllByRole('button', { name: 'Generar nota' })
        .find((button) => button.dataset.testid !== 'onboarding-step-action')
      if (match === undefined) {
        throw new Error('El botón «Generar nota» de la sección Nota no está montado')
      }
      return match
    }
    await waitFor(() => expect(sectionGenerate()).toBeEnabled())
    await waitFor(() => expect(within(banner).getByTestId('onboarding-step-action')).toBeEnabled())
    await user.click(within(banner).getByTestId('onboarding-step-action'))

    await waitFor(() => expect(mockApi.api.llm.generateNote).toHaveBeenCalledWith('i-1', 'nt-1'))
    await waitFor(() =>
      expect(screen.getAllByText('Generando nota…').length).toBeGreaterThanOrEqual(2)
    )

    const summarized: Interview = { ...RECORDED, status: 'summarized' }
    storedNote = NOTE
    act(() => {
      pending.resolve({ ok: true, data: { note: NOTE, interview: summarized } })
    })
    // Con la nota generada y sin evaluación, el banner pasa al paso 6
    await waitFor(() =>
      expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '6')
    )
  })

  // SPEC-058 · AC-22 (parte automatizable: creación de la nota y montaje de la
  // sección; el scroll y el foco reales del editor son verificación MANUAL)
  it('creates an empty note on "Escribir nota" in the degraded step and the Nota section appears', async () => {
    grantAnthropicKey()
    vi.mocked(mockApi.api.db.listNoteTemplates).mockResolvedValue({
      ok: true,
      data: [NOTE_TEMPLATE]
    })
    vi.mocked(mockApi.api.db.createNote).mockImplementation((input) => {
      storedNote = { ...NOTE, contentMarkdown: input.contentMarkdown ?? '' }
      return Promise.resolve({ ok: true, data: storedNote })
    })
    renderHarness({ ...RECORDED, transcriptPath: null })
    const user = userEvent.setup()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    expect(banner).toHaveAttribute('data-step', '5')
    expect(banner).toHaveAttribute('data-degraded', 'true')
    // Sin nota y sin transcripción la sección Nota NO está montada (SPEC-035)
    expect(screen.queryByRole('heading', { name: 'Nota' })).not.toBeInTheDocument()

    await user.click(within(banner).getByTestId('onboarding-step-action'))
    await waitFor(() =>
      expect(mockApi.api.db.createNote).toHaveBeenCalledWith({
        interviewId: 'i-1',
        contentMarkdown: ''
      })
    )
    // El puente monta la sección Nota con el editor (nota manual editable)
    expect(await screen.findByRole('heading', { name: 'Nota' })).toBeInTheDocument()
    expect(await screen.findByTestId('note-markdown-editor')).toBeInTheDocument()
  })

  // SPEC-058 · AC-23: la acción espejada dispara la MISMA evaluación
  it('evaluates the objectives through ObjectivesSection and both buttons show "Evaluando objetivos…" until done', async () => {
    grantAnthropicKey()
    vi.mocked(mockApi.api.db.listNoteTemplates).mockResolvedValue({
      ok: true,
      data: [NOTE_TEMPLATE]
    })
    storedNote = NOTE
    const summarized: Interview = { ...RECORDED, status: 'summarized' }
    const pending = deferred<Awaited<ReturnType<typeof mockApi.api.llm.evaluateObjectives>>>()
    vi.mocked(mockApi.api.llm.evaluateObjectives).mockReturnValue(pending.promise)
    renderHarness(summarized)
    const user = userEvent.setup()

    const banner = await screen.findByTestId('interview-onboarding-banner')
    expect(banner).toHaveAttribute('data-step', '6')
    // Referencia fresca en cada assert: el botón se remonta al habilitarse
    await waitFor(() => expect(within(banner).getByTestId('onboarding-step-action')).toBeEnabled())
    await user.click(within(banner).getByTestId('onboarding-step-action'))

    await waitFor(() => expect(mockApi.api.llm.evaluateObjectives).toHaveBeenCalledWith('i-1'))
    await waitFor(() =>
      expect(screen.getAllByText('Evaluando objetivos…').length).toBeGreaterThanOrEqual(2)
    )

    const evaluated: Interview = {
      ...summarized,
      objectiveResults: [{ met: true, reason: 'Cubierto con hechos concretos.' }]
    }
    act(() => {
      pending.resolve({ ok: true, data: evaluated })
    })
    // Con nota y evaluación, el banner llega al paso final
    await waitFor(() =>
      expect(screen.getByTestId('interview-onboarding-banner')).toHaveAttribute('data-step', '7')
    )
  })

  // SPEC-058 · AC-29: el botón del paso es primary; los de sección conservan
  // su variante (outline en Regenerar/Evaluar). Nota: los CTA de generación de
  // los empty states de Guión/Nota siguen siendo primary (variante actual
  // conservada) — contradicción interna del AC documentada en el map.
  it('renders the banner action as the primary button while section buttons keep their variant', async () => {
    grantAnthropicKey()
    vi.mocked(mockApi.api.db.listNoteTemplates).mockResolvedValue({
      ok: true,
      data: [NOTE_TEMPLATE]
    })
    renderHarness(RECORDED)

    const banner = await screen.findByTestId('interview-onboarding-banner')
    const action = within(banner).getByTestId('onboarding-step-action')
    expect(action.className).toContain('bg-primary')

    // «Evaluar objetivos» de la sección Objetivos sigue en outline y operativo
    const evaluate = await screen.findByTestId('objectives-evaluate-button')
    expect(evaluate.className).not.toContain('bg-primary')
    expect(evaluate.className).toContain('border')
    await waitFor(() => expect(evaluate).toBeEnabled())
  })
})
