// @vitest-environment node
/**
 * SPEC-046: Guión personalizado con TODOS los participantes — el user prompt
 * gana el contexto de la empresa, la sección «## Contactos» con un bloque por
 * participante (en el orden de contactIds) y las secciones condicionales
 * «## Objetivos del discovery» y «## Objetivo del grupo»; sin ellas el prompt
 * es byte-estable con el previo y las degradaciones de SPEC-020 se conservan
 * EXACTAS. El system prompt NO cambia (prefijo cacheado SPEC-023/031).
 * Generated by QA Dev agent.
 *
 * Mismo arnés que llmService.test.ts (SPEC-014): SDK de Anthropic mockeado con
 * clases de error espejo y store/repository REALES en directorio temporal.
 */
import { mkdtempSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { generateInterviewScript } from '../../../src/main/llmService'
import * as repository from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'
import type { InterviewTemplate } from '../../../src/renderer/src/types/domain'

const harness = vi.hoisted(() => {
  /** Jerarquía espejo de la del SDK: instanceof debe funcionar en mapSdkError. */
  class APIError extends Error {}
  class AuthenticationError extends APIError {}
  class RateLimitError extends APIError {}
  class APIConnectionError extends APIError {}
  return {
    create: vi.fn(),
    errors: { APIError, AuthenticationError, RateLimitError, APIConnectionError }
  }
})

vi.mock('@anthropic-ai/sdk', () => {
  class MockAnthropic {
    static APIError = harness.errors.APIError
    static AuthenticationError = harness.errors.AuthenticationError
    static RateLimitError = harness.errors.RateLimitError
    static APIConnectionError = harness.errors.APIConnectionError
    readonly messages = { create: harness.create }
  }
  return { default: MockAnthropic }
})

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

/** Respuesta del SDK con bloque thinking + bloque text (el JSON va en text). */
function sdkResponse(text: string): unknown {
  return {
    stop_reason: 'end_turn',
    content: [
      { type: 'thinking', thinking: 'razonamiento interno' },
      { type: 'text', text }
    ]
  }
}

const VALID_JSON = JSON.stringify({
  scriptMarkdown: '# Guión adaptado',
  objectives: ['Objetivo uno', 'Objetivo dos', 'Objetivo tres']
})

/** Template mínimo compartido (un bloque, una pregunta, sin guías). */
function seedTemplate(): InterviewTemplate {
  return repository.createInterviewTemplate({
    name: 'Entrevista de problema',
    phase: 'problem',
    blocks: [{ title: 'Contexto', questions: [{ text: '¿Quién lleva el regulatorio?' }] }]
  })
}

function sentUserPrompt(callIndex = 0): string {
  const params = harness.create.mock.calls[callIndex][0] as {
    messages: Array<{ role: string; content: string }>
  }
  return params.messages[0].content
}

function sentSystemPrompt(callIndex = 0): string {
  const params = harness.create.mock.calls[callIndex][0] as { system: string }
  return params.system
}

let dataDir = ''

beforeEach(() => {
  vi.clearAllMocks()
  dataDir = mkdtempSync(join(tmpdir(), 'maurya-llm-participants-'))
  initStore(dataDir)
  process.env['ANTHROPIC_API_KEY'] = 'sk-ant-test-key'
})

afterEach(() => {
  delete process.env['ANTHROPIC_API_KEY']
})

describe('llmService (SPEC-046 participantes)', () => {
  describe('contacts and company context sections', () => {
    // SPEC-046 · AC-16: contexto de empresa en la sección Empresa y un bloque
    // por participante (nombre, cargo, LinkedIn y contexto) bajo ## Contactos
    it('includes the company context line and one block per participant with name, cargo, LinkedIn and contexto in contactIds order', async () => {
      const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
      const company = repository.createCompany({
        name: 'Acme Corp',
        website: 'https://acme.example',
        linkedinUrl: 'https://linkedin.com/company/acme',
        context: 'Scale-up MedTech con certificación MDR en curso'
      })
      const jane = repository.createContact({
        companyId: company.id,
        name: 'Jane Doe',
        position: 'CTO',
        linkedinUrl: 'https://linkedin.com/in/janedoe',
        context: 'Impulsa la digitalización del área regulatoria'
      })
      const john = repository.createContact({
        companyId: company.id,
        name: 'John Smith',
        context: 'Escéptico con herramientas nuevas'
      })
      const template = seedTemplate()
      const interview = repository.createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        // Orden de marcado inverso al de alta: manda el orden de contactIds
        contactIds: [john.id, jane.id],
        templateId: template.id,
        title: 'Discovery con Acme'
      })
      harness.create.mockResolvedValue(sdkResponse(VALID_JSON))

      await generateInterviewScript(interview.id)

      const userPrompt = sentUserPrompt()
      // Empresa: línea Contexto tras LinkedIn
      expect(userPrompt).toContain(
        '## Empresa\nNombre: Acme Corp\nWeb: https://acme.example\n' +
          'LinkedIn: https://linkedin.com/company/acme\n' +
          'Contexto: Scale-up MedTech con certificación MDR en curso'
      )
      // Contactos: un bloque por participante, en el orden de contactIds
      // (John primero), con las líneas ausentes omitidas
      expect(userPrompt).toContain(
        '## Contactos\n' +
          'Nombre: John Smith\nContexto: Escéptico con herramientas nuevas\n\n' +
          'Nombre: Jane Doe\nCargo: CTO\nLinkedIn: https://linkedin.com/in/janedoe\n' +
          'Contexto: Impulsa la digitalización del área regulatoria'
      )
    })

    // SPEC-046 · AC-19: sin contactos se conserva la degradación EXACTA de
    // SPEC-020 («Sin contacto asignado todavía.»), sin errores
    it('keeps the exact "Sin contacto asignado todavía." degradation when the interview has a company but no contacts', async () => {
      const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
      const company = repository.createCompany({ name: 'Acme Corp' })
      const template = seedTemplate()
      const interview = repository.createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        templateId: template.id,
        title: 'Discovery con Acme'
      })
      harness.create.mockResolvedValue(sdkResponse(VALID_JSON))

      const updated = await generateInterviewScript(interview.id)

      expect(sentUserPrompt()).toContain('## Contactos\nSin contacto asignado todavía.')
      expect(updated.status).toBe('prepared')
    })
  })

  describe('discovery objectives and group objective sections', () => {
    // SPEC-046 · AC-17: los objetivos del discovery y el objetivo del grupo
    // entran como secciones propias del mensaje de usuario
    it('includes "## Objetivos del discovery" and "## Objetivo del grupo" as their own sections when both exist', async () => {
      const discovery = repository.createDiscovery({
        name: 'Discovery Maurya',
        objectives: 'Entender el problema real\nValidar la urgencia'
      })
      const group = repository.createInterviewGroup({
        discoveryId: discovery.id,
        name: 'Founders early-stage',
        objective: 'Detectar dolores reales en la validación'
      })
      const company = repository.createCompany({ name: 'Acme Corp' })
      const template = seedTemplate()
      const interview = repository.createInterview({
        discoveryId: discovery.id,
        interviewGroupId: group.id,
        companyId: company.id,
        templateId: template.id,
        title: 'Discovery con Acme'
      })
      harness.create.mockResolvedValue(sdkResponse(VALID_JSON))

      await generateInterviewScript(interview.id)

      const userPrompt = sentUserPrompt()
      expect(userPrompt).toContain(
        '## Objetivos del discovery\nEntender el problema real\nValidar la urgencia'
      )
      expect(userPrompt).toContain(
        '## Objetivo del grupo\nDetectar dolores reales en la validación'
      )
      // Orden del wireframe del prompt: Discovery → Objetivos → Objetivo del
      // grupo → Empresa
      const discoveryIndex = userPrompt.indexOf('## Discovery')
      const objectivesIndex = userPrompt.indexOf('## Objetivos del discovery')
      const groupIndex = userPrompt.indexOf('## Objetivo del grupo')
      const companyIndex = userPrompt.indexOf('## Empresa')
      expect(discoveryIndex).toBeGreaterThanOrEqual(0)
      expect(objectivesIndex).toBeGreaterThan(discoveryIndex)
      expect(groupIndex).toBeGreaterThan(objectivesIndex)
      expect(companyIndex).toBeGreaterThan(groupIndex)
    })

    // SPEC-046 · AC-18: sin grupo y sin objetivos del discovery las secciones
    // se OMITEN y el resto del prompt no cambia — byte-exacto con la forma
    // previa (salvo «## Contactos», derogación presupuestada de SPEC-014/020)
    it('omits both sections producing a byte-exact prompt for an interview without group and a discovery without objectives', async () => {
      const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
      const company = repository.createCompany({
        name: 'Acme Corp',
        website: 'https://acme.example'
      })
      const jane = repository.createContact({
        companyId: company.id,
        name: 'Jane Doe',
        position: 'CTO'
      })
      const template = seedTemplate()
      const interview = repository.createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [jane.id],
        templateId: template.id,
        title: 'Discovery con Acme'
      })
      harness.create.mockResolvedValue(sdkResponse(VALID_JSON))

      await generateInterviewScript(interview.id)

      // Byte-exacto: sin secciones nuevas, degradaciones y orden intactos
      expect(sentUserPrompt()).toBe(
        '## Discovery\nNombre: Discovery Maurya\n\n' +
          '## Empresa\nNombre: Acme Corp\nWeb: https://acme.example\n\n' +
          '## Contactos\nNombre: Jane Doe\nCargo: CTO\n\n' +
          '## Template de entrevista\nTemplate: Entrevista de problema\n\n' +
          'Bloque 1: Contexto\n  1.1 ¿Quién lleva el regulatorio?\n\n' +
          '## Tarea\nGenera el guión personalizado y los objetivos para la entrevista ' +
          '"Discovery con Acme".'
      )
    })

    // SPEC-046 · Notas técnicas: el system prompt NO cambia — las secciones
    // nuevas viven SOLO en el mensaje de usuario (prefijo cacheado intacto)
    it('sends a byte-identical system prompt with and without group/discovery objectives', async () => {
      const template = seedTemplate()
      const company = repository.createCompany({ name: 'Acme Corp' })

      // Generación SIN grupo ni objetivos
      const plainDiscovery = repository.createDiscovery({ name: 'Discovery plano' })
      const plainInterview = repository.createInterview({
        discoveryId: plainDiscovery.id,
        companyId: company.id,
        templateId: template.id,
        title: 'Sin extras'
      })
      // Generación CON objetivos del discovery y objetivo del grupo
      const richDiscovery = repository.createDiscovery({
        name: 'Discovery rico',
        objectives: 'Entender el problema real'
      })
      const group = repository.createInterviewGroup({
        discoveryId: richDiscovery.id,
        name: 'Founders',
        objective: 'Detectar dolores'
      })
      const richInterview = repository.createInterview({
        discoveryId: richDiscovery.id,
        interviewGroupId: group.id,
        companyId: company.id,
        templateId: template.id,
        title: 'Con extras'
      })
      harness.create.mockResolvedValue(sdkResponse(VALID_JSON))

      await generateInterviewScript(plainInterview.id)
      await generateInterviewScript(richInterview.id)

      const plainSystem = sentSystemPrompt(0)
      const richSystem = sentSystemPrompt(1)
      expect(richSystem).toBe(plainSystem)
      // Y las secciones nuevas jamás se cuelan en el system prompt
      expect(richSystem).not.toContain('## Objetivos del discovery')
      expect(richSystem).not.toContain('## Objetivo del grupo')
      expect(richSystem).not.toContain('Contexto:')
    })
  })
})
