/**
 * SPEC-026: Prompts de IA personalizables — edición en Sheet con editor
 * Markdown WYSIWYG (AC-06..AC-13). Frontera de mocking: api.db del bridge;
 * el editor TipTap se monta REAL sobre jsdom (polyfills de geometría de
 * ProseMirror en tests/helpers/prosemirrorJsdom.ts).
 *
 * Nota de estrategia: para "modificar el texto" los tests usan la acción
 * Título de la botonera (cambio de documento determinista); simular escritura
 * con teclado dentro de un contenteditable de ProseMirror no es fiable en
 * jsdom (beforeinput no implementado).
 * Generated by QA Dev agent.
 */
import { render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeAll, beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { SettingsPage } from '@/pages/SettingsPage'
import type { CustomPrompt, CustomPromptId } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'
import { installProseMirrorJsdomPolyfills } from '../../helpers/prosemirrorJsdom'

let mockApi: MockApiHandle

const SCRIPT_DEFAULT_BODY = 'Eres un preparador experto de entrevistas de discovery.'

function promptView(id: CustomPromptId, overrides: Partial<CustomPrompt> = {}): CustomPrompt {
  return {
    id,
    defaultBody: SCRIPT_DEFAULT_BODY,
    lockedRules:
      'Tu tarea: adaptar el template.\nReglas:\n- Responde únicamente con el JSON pedido.',
    overrideBody: null,
    updatedAt: null,
    ...overrides
  }
}

function setPrompts(prompts: CustomPrompt[]): void {
  vi.mocked(mockApi.api.db.listCustomPrompts).mockResolvedValue({ ok: true, data: prompts })
}

function renderSettings(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/settings?tab=custom-prompts']}>
        <Routes>
          <Route path="/settings" element={<SettingsPage />} />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

/** Abre el Sheet de edición del prompt indicado desde su fila del listado. */
async function openEditor(
  user: ReturnType<typeof userEvent.setup>,
  rowTestId = 'custom-prompt-row-script'
): Promise<HTMLElement> {
  const row = await screen.findByTestId(rowTestId)
  await user.click(within(row).getByRole('button', { name: 'Editar prompt' }))
  return await screen.findByTestId('custom-prompt-sheet')
}

beforeAll(() => {
  installProseMirrorJsdomPolyfills()
})

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  setPrompts([promptView('script')])
})

describe('CustomPromptSheet', () => {
  describe('opening the editor', () => {
    // SPEC-026 · AC-06
    it('opens the Sheet with the WYSIWYG editor showing the current text, the toolbar and the read-only locked rules', async () => {
      const user = userEvent.setup()
      renderSettings()

      const sheet = await openEditor(user)

      expect(
        within(sheet).getByRole('heading', { name: 'Editar prompt — Guión y objetivos' })
      ).toBeInTheDocument()
      expect(within(sheet).getByText('Persona y enfoque')).toBeInTheDocument()
      // El editor muestra el texto vigente (default: no hay override)
      const editor = within(sheet).getByTestId('custom-prompt-editor')
      expect(
        within(editor).getByText(/Eres un preparador experto de entrevistas de discovery\./)
      ).toBeInTheDocument()
      // Botonera con las 5 acciones de formato
      const toolbar = within(sheet).getByTestId('custom-prompt-editor-toolbar')
      for (const label of ['Negrita', 'Cursiva', 'Título', 'Lista de viñetas', 'Lista numerada']) {
        expect(within(toolbar).getByRole('button', { name: label })).toBeInTheDocument()
      }
      // Reglas fijas en solo lectura (sin controles de edición)
      const lockedRules = within(sheet).getByTestId('custom-prompt-locked-rules')
      expect(lockedRules).toHaveTextContent('Responde únicamente con el JSON pedido.')
      expect(within(lockedRules).queryByRole('textbox')).not.toBeInTheDocument()
    })

    // SPEC-026 · AC-09
    it('renders a saved override with its exact formatting when reopening the editor (Markdown round-trip)', async () => {
      const user = userEvent.setup()
      setPrompts([
        promptView('script', {
          overrideBody: '**Negrita** y una lista:\n\n- uno\n- dos',
          updatedAt: '2026-07-10T10:00:00.000Z'
        })
      ])
      renderSettings()

      const sheet = await openEditor(user)

      const editor = within(sheet).getByTestId('custom-prompt-editor')
      const bold = within(editor).getByText('Negrita')
      expect(bold.tagName).toBe('STRONG')
      const items = within(editor).getAllByRole('listitem')
      expect(items.map((item) => item.textContent)).toEqual(['uno', 'dos'])
      // El default NO se muestra: manda el override
      expect(within(editor).queryByText(/Eres un preparador experto/)).not.toBeInTheDocument()
    })
  })

  describe('formatting from the toolbar', () => {
    // SPEC-026 · AC-07
    it('applies toolbar formatting and reflects it immediately in the editor view', async () => {
      const user = userEvent.setup()
      renderSettings()

      const sheet = await openEditor(user)
      const editor = within(sheet).getByTestId('custom-prompt-editor')
      expect(within(editor).queryByRole('heading')).not.toBeInTheDocument()

      await user.click(within(sheet).getByRole('button', { name: 'Título' }))

      const heading = await within(editor).findByRole('heading', { level: 2 })
      expect(heading).toHaveTextContent('Eres un preparador experto de entrevistas de discovery.')
      // La acción activa se refleja en la botonera (aria-pressed)
      expect(within(sheet).getByRole('button', { name: 'Título' })).toHaveAttribute(
        'aria-pressed',
        'true'
      )
    })
  })

  describe('saving', () => {
    // SPEC-026 · AC-08
    it('saves the modified text as Markdown, closes the Sheet, shows the "Prompt guardado" toast and switches the badge to "Personalizado"', async () => {
      const user = userEvent.setup()
      vi.mocked(mockApi.api.db.saveCustomPrompt).mockResolvedValue({
        ok: true,
        data: promptView('script', {
          overrideBody: `## ${SCRIPT_DEFAULT_BODY}`,
          updatedAt: '2026-07-10T10:00:00.000Z'
        })
      })
      renderSettings()

      const sheet = await openEditor(user)
      await user.click(within(sheet).getByRole('button', { name: 'Título' }))
      await user.click(within(sheet).getByRole('button', { name: 'Guardar' }))

      // Se persiste el Markdown plano serializado (el título → prefijo '## ')
      await waitFor(() =>
        expect(vi.mocked(mockApi.api.db.saveCustomPrompt)).toHaveBeenCalledWith(
          'script',
          expect.stringMatching(/^## Eres un preparador experto/)
        )
      )
      await waitFor(() =>
        expect(screen.queryByTestId('custom-prompt-sheet')).not.toBeInTheDocument()
      )
      const toasts = await screen.findAllByText('Prompt guardado')
      expect(toasts.length).toBeGreaterThanOrEqual(1)
      const scriptRow = screen.getByTestId('custom-prompt-row-script')
      expect(await within(scriptRow).findByText('Personalizado')).toBeInTheDocument()
    })

    // SPEC-026 · AC-10 — GIVEN "editor vacío o solo espacios": se materializa
    // con un override de solo espacios (la vía de teclado para vaciar un
    // contenteditable de ProseMirror no es fiable en jsdom).
    it('shows the inline error "El prompt no puede quedar vacío" and does not persist when saving an empty editor', async () => {
      const user = userEvent.setup()
      setPrompts([
        promptView('script', { overrideBody: '   ', updatedAt: '2026-07-10T10:00:00.000Z' })
      ])
      renderSettings()

      const sheet = await openEditor(user)
      await user.click(within(sheet).getByRole('button', { name: 'Guardar' }))

      expect(await within(sheet).findByText('El prompt no puede quedar vacío')).toBeInTheDocument()
      expect(vi.mocked(mockApi.api.db.saveCustomPrompt)).not.toHaveBeenCalled()
      expect(screen.getByTestId('custom-prompt-sheet')).toBeInTheDocument()
    })

    // SPEC-026 · AC-11
    it('keeps the Sheet open with the text intact and shows a destructive toast when saving fails', async () => {
      const user = userEvent.setup()
      vi.mocked(mockApi.api.db.saveCustomPrompt).mockResolvedValue({
        ok: false,
        error: { kind: 'storage', message: 'Fallo simulado al guardar el prompt' }
      })
      renderSettings()

      const sheet = await openEditor(user)
      await user.click(within(sheet).getByRole('button', { name: 'Título' }))
      await user.click(within(sheet).getByRole('button', { name: 'Guardar' }))

      const toasts = await screen.findAllByText('Fallo simulado al guardar el prompt')
      expect(toasts.length).toBeGreaterThanOrEqual(1)
      // El Sheet sigue abierto y conserva el texto con su formato
      const editor = within(screen.getByTestId('custom-prompt-sheet')).getByTestId(
        'custom-prompt-editor'
      )
      expect(within(editor).getByRole('heading', { level: 2 })).toHaveTextContent(
        'Eres un preparador experto de entrevistas de discovery.'
      )
    })
  })

  describe('closing', () => {
    // SPEC-026 · AC-12
    it('asks to discard unsaved changes with the "Descartar cambios" AlertDialog and closes without persisting on confirm', async () => {
      const user = userEvent.setup()
      renderSettings()

      const sheet = await openEditor(user)
      await user.click(within(sheet).getByRole('button', { name: 'Título' }))
      await user.click(within(sheet).getByRole('button', { name: 'Cancelar' }))

      const dialog = await screen.findByRole('alertdialog')
      expect(within(dialog).getByRole('heading', { name: 'Descartar cambios' })).toBeInTheDocument()
      expect(
        within(dialog).getByText('Los cambios no guardados en el prompt se perderán.')
      ).toBeInTheDocument()

      await user.click(within(dialog).getByRole('button', { name: 'Descartar' }))

      await waitFor(() =>
        expect(screen.queryByTestId('custom-prompt-sheet')).not.toBeInTheDocument()
      )
      expect(vi.mocked(mockApi.api.db.saveCustomPrompt)).not.toHaveBeenCalled()
    })

    // SPEC-026 · AC-13
    it('closes the Sheet directly without confirmation when there are no unsaved changes', async () => {
      const user = userEvent.setup()
      renderSettings()

      const sheet = await openEditor(user)
      await user.click(within(sheet).getByRole('button', { name: 'Cancelar' }))

      await waitFor(() =>
        expect(screen.queryByTestId('custom-prompt-sheet')).not.toBeInTheDocument()
      )
      expect(screen.queryByRole('alertdialog')).not.toBeInTheDocument()
      expect(vi.mocked(mockApi.api.db.saveCustomPrompt)).not.toHaveBeenCalled()
    })
  })
})
