// @vitest-environment node
/**
 * SPEC-025: resolución de prompts personalizados en runtime (AC-17..AC-22).
 * SDK de Anthropic mockeado (clases de error espejo, patrón SPEC-014/016/017)
 * y store/repository REALES sobre un directorio temporal. Para el asistente,
 * transcriptionService se mockea capturando el finalLineListener (la frontera
 * pública por la que entran las líneas); tiempo con fake timers SOLO de Date
 * para gobernar el intervalo mínimo entre análisis (lección fake timers).
 * Generated by QA Dev agent.
 */
import { mkdtempSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import type { WebContents } from 'electron'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { generateInterviewScript } from '../../../src/main/llmService'
import { generateInterviewNote } from '../../../src/main/noteService'
import { MIN_INTERVAL_MS, startAssistant, stopAssistant } from '../../../src/main/assistantService'
import { resolvePromptPersona } from '../../../src/main/prompts'
import { CUSTOM_PROMPT_DEFAULTS } from '../../../src/main/prompts/defaults'
import * as repository from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'
import type { TranscriptLine } from '../../../src/renderer/src/types/audio'
import type { AssistantUpdateEvent } from '../../../src/renderer/src/types/assistant'
import type { NoteTemplate } from '../../../src/renderer/src/types/domain'

const harness = vi.hoisted(() => {
  /** Jerarquía espejo de la del SDK: instanceof debe funcionar en mapSdkError. */
  class APIError extends Error {}
  class AuthenticationError extends APIError {}
  class RateLimitError extends APIError {}
  class APIConnectionError extends APIError {}
  return {
    create: vi.fn(),
    finalLineListener: null as ((line: TranscriptLine) => void) | null,
    errors: { APIError, AuthenticationError, RateLimitError, APIConnectionError }
  }
})

vi.mock('@anthropic-ai/sdk', () => {
  class MockAnthropic {
    static APIError = harness.errors.APIError
    static AuthenticationError = harness.errors.AuthenticationError
    static RateLimitError = harness.errors.RateLimitError
    static APIConnectionError = harness.errors.APIConnectionError
    readonly messages = { create: harness.create }
  }
  return { default: MockAnthropic }
})

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  },
  dialog: { showSaveDialog: vi.fn() },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

// El asistente se alimenta por setFinalLineListener: capturamos el listener y
// le inyectamos líneas directamente (frontera pública de transcriptionService).
vi.mock('../../../src/main/transcriptionService', () => ({
  setFinalLineListener: vi.fn((listener: ((line: TranscriptLine) => void) | null) => {
    harness.finalLineListener = listener
  })
}))

/** Respuesta del SDK con bloque thinking + bloque text (el JSON va en text). */
function sdkResponse(payload: Record<string, unknown>): unknown {
  return {
    stop_reason: 'end_turn',
    content: [
      { type: 'thinking', thinking: 'razonamiento' },
      { type: 'text', text: JSON.stringify(payload) }
    ]
  }
}

const SCRIPT_JSON = {
  scriptMarkdown: '# Guión adaptado',
  objectives: ['Objetivo uno', 'Objetivo dos', 'Objetivo tres']
}

const NOTE_JSON = {
  sections: [
    { title: 'ignorado', contentMarkdown: 'El CTO gestiona todo a mano.' },
    { title: 'ignorado', contentMarkdown: '«Nos lleva dos días»' }
  ]
}

const ANALYSIS_JSON = {
  action: 'continue',
  suggestedQuestion: '¿Cuándo fue la última vez que pasó?',
  reason: 'Ya hay material concreto',
  alarms: [],
  objectivesMet: []
}

function seedScriptInterview(): string {
  const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
  const company = repository.createCompany({ discoveryId: discovery.id, name: 'Acme Corp' })
  const template = repository.createInterviewTemplate({
    name: 'Entrevista de problema',
    phase: 'problem',
    blocks: [{ title: 'Contexto', questions: [{ text: '¿Quién lleva el regulatorio?' }] }]
  })
  const interview = repository.createInterview({
    discoveryId: discovery.id,
    companyId: company.id,
    title: 'Discovery con Acme',
    templateId: template.id
  })
  return interview.id
}

function seedNoteInterview(): { interviewId: string; template: NoteTemplate } {
  const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
  const template = repository.createNoteTemplate({
    name: 'Notas discovery',
    context: 'Céntrate en dolores.',
    sections: [
      { title: 'Dolores', description: 'Problemas detectados' },
      { title: 'Citas', description: 'Frases literales' }
    ]
  })
  const interview = repository.createInterview({
    discoveryId: discovery.id,
    title: 'Captura'
  })
  const dir = mkdtempSync(join(tmpdir(), 'maurya-prompts-transcript-'))
  const transcriptPath = join(dir, 'entrevista.transcript.json')
  writeFileSync(
    transcriptPath,
    JSON.stringify({
      lines: [
        {
          channel: 'mic',
          speaker: 0,
          text: '¿Cómo gestionáis hoy el registro?',
          startMs: 0,
          endMs: 1000,
          receivedAtMs: 1100
        }
      ],
      latency: null,
      assistant: null
    })
  )
  repository.updateInterview(interview.id, { transcriptPath, status: 'recorded' })
  return { interviewId: interview.id, template }
}

function seedAssistantInterview(): string {
  const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
  const interview = repository.createInterview({ discoveryId: discovery.id, title: 'Entrevista' })
  return interview.id
}

function createSender(): { sender: WebContents; send: ReturnType<typeof vi.fn> } {
  const send = vi.fn()
  const senderLike = { isDestroyed: (): boolean => false, send }
  return { sender: senderLike as unknown as WebContents, send }
}

function assistantEvents(send: ReturnType<typeof vi.fn>): AssistantUpdateEvent[] {
  return send.mock.calls
    .filter((call) => call[0] === 'assistant:update')
    .map((call) => call[1] as AssistantUpdateEvent)
}

let lineCounter = 0

/** Inyecta N líneas finales por el listener capturado (dispara el análisis). */
function feedFinalLines(count: number): void {
  for (let index = 0; index < count; index += 1) {
    lineCounter += 1
    harness.finalLineListener?.({
      channel: lineCounter % 2 === 0 ? 'system' : 'mic',
      speaker: 0,
      text: `Línea de conversación ${lineCounter}`,
      startMs: lineCounter * 1000,
      endMs: lineCounter * 1000 + 900,
      receivedAtMs: lineCounter * 1000 + 950
    })
  }
}

async function waitForCreateCalls(count: number): Promise<void> {
  await vi.waitFor(() => expect(harness.create).toHaveBeenCalledTimes(count))
}

/** Espera a que el último evento sea 'active' (la promesa del análisis resolvió). */
async function waitForActive(send: ReturnType<typeof vi.fn>): Promise<void> {
  await vi.waitFor(() => {
    expect(assistantEvents(send).at(-1)?.state).toBe('active')
  })
}

/** El system de la llamada N (0-based) del SDK, como lo recibió messages.create. */
function systemOfCall(index: number): unknown {
  const params = harness.create.mock.calls[index][0] as Record<string, unknown>
  return params.system
}

const BASE_TIME_MS = 1_000_000_000

beforeEach(() => {
  vi.clearAllMocks()
  harness.finalLineListener = null
  lineCounter = 0
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(BASE_TIME_MS)
  initStore(mkdtempSync(join(tmpdir(), 'maurya-prompts-')))
  process.env['ANTHROPIC_API_KEY'] = 'sk-ant-test-key'
})

afterEach(() => {
  stopAssistant()
  vi.useRealTimers()
  delete process.env['ANTHROPIC_API_KEY']
})

describe('customPromptsResolution', () => {
  describe('script generation (llmService)', () => {
    // SPEC-025 · AC-17
    it('uses the saved script override as persona block keeping the locked rules intact in the system prompt', async () => {
      const interviewId = seedScriptInterview()
      repository.saveCustomPromptOverride('script', 'Persona personalizada del guión.')
      harness.create.mockResolvedValue(sdkResponse(SCRIPT_JSON))

      await generateInterviewScript(interviewId)

      const system = systemOfCall(0) as string
      expect(system.startsWith('Persona personalizada del guión.')).toBe(true)
      expect(system).not.toContain('Eres un preparador experto')
      // Partes bloqueadas intactas: fase dinámica + tarea + reglas del JSON
      expect(system).toContain('La entrevista es de fase de problema.')
      expect(system).toContain('Tu tarea: adaptar el template de entrevista')
      expect(system).toContain('`scriptMarkdown`: el guión completo en markdown')
      expect(system).toContain('`objectives`: entre 3 y 7 objetivos')
      expect(system).toContain('Responde únicamente con el JSON pedido.')
    })

    // SPEC-025 · AC-20
    it('builds the system prompt from the module defaults when no override is saved', async () => {
      const interviewId = seedScriptInterview()
      harness.create.mockResolvedValue(sdkResponse(SCRIPT_JSON))

      await generateInterviewScript(interviewId)

      const system = systemOfCall(0) as string
      expect(system.startsWith(CUSTOM_PROMPT_DEFAULTS.script.persona)).toBe(true)
      // Los otros dos prompts también resuelven al default del módulo
      expect(resolvePromptPersona('note')).toBe(CUSTOM_PROMPT_DEFAULTS.note.persona)
      expect(resolvePromptPersona('assistant')).toBe(CUSTOM_PROMPT_DEFAULTS.assistant.persona)
    })

    // SPEC-025 · AC-22
    it('returns to the default persona on the next generation after resetting the override', async () => {
      const interviewId = seedScriptInterview()
      repository.saveCustomPromptOverride('script', 'Persona personalizada del guión.')
      harness.create.mockResolvedValue(sdkResponse(SCRIPT_JSON))

      await generateInterviewScript(interviewId)
      expect((systemOfCall(0) as string).startsWith('Persona personalizada del guión.')).toBe(true)

      repository.resetCustomPromptOverride('script')
      await generateInterviewScript(interviewId)

      const system = systemOfCall(1) as string
      expect(system.startsWith(CUSTOM_PROMPT_DEFAULTS.script.persona)).toBe(true)
      expect(system).not.toContain('Persona personalizada del guión.')
    })
  })

  describe('note generation (noteService)', () => {
    // SPEC-025 · AC-18
    it('uses the saved note override as persona block keeping the locked rules intact in the system prompt', async () => {
      const { interviewId, template } = seedNoteInterview()
      repository.saveCustomPromptOverride('note', 'Persona personalizada de la nota.')
      harness.create.mockResolvedValue(sdkResponse(NOTE_JSON))

      await generateInterviewNote(interviewId, template.id)

      const system = systemOfCall(0) as string
      expect(system.startsWith('Persona personalizada de la nota.')).toBe(true)
      expect(system).not.toContain('Eres un sintetizador experto')
      // Partes bloqueadas intactas: contexto dinámico del template + reglas
      expect(system).toContain('Contexto del note-template')
      expect(system).toContain('Céntrate en dolores.')
      expect(system).toContain('Tu tarea: sintetizar la conversación')
      expect(system).toContain('`sections`: exactamente una entrada')
      expect(system).toContain('Responde únicamente con el JSON pedido.')
    })
  })

  describe('live assistant (assistantService)', () => {
    // SPEC-025 · AC-19
    it('builds the session systemBlocks with the saved assistant override keeping rules and char limits intact', async () => {
      const interviewId = seedAssistantInterview()
      repository.saveCustomPromptOverride('assistant', 'Persona personalizada del copiloto.')
      harness.create.mockResolvedValue(sdkResponse(ANALYSIS_JSON))
      const { sender, send } = createSender()

      startAssistant(sender, interviewId)
      feedFinalLines(3)
      await waitForCreateCalls(1)
      await waitForActive(send)

      const blocks = systemOfCall(0) as Array<{
        type: string
        text: string
        cache_control?: { type: string }
      }>
      expect(Array.isArray(blocks)).toBe(true)
      expect(blocks[0].text.startsWith('Persona personalizada del copiloto.')).toBe(true)
      expect(blocks[0].text).not.toContain('Eres el copiloto en tiempo real')
      // Reglas y límites de caracteres bloqueados, intactos en el prompt
      expect(blocks[0].text).toContain('Reglas:')
      expect(blocks[0].text).toContain('máximo 200 caracteres')
      expect(blocks[0].text).toContain('máximo 140 caracteres')
      expect(blocks[0].text).toContain('Responde únicamente con el JSON pedido.')
      // Prefijo cacheado (SPEC-023): cache_control ephemeral en el último bloque
      expect(blocks.at(-1)?.cache_control).toEqual({ type: 'ephemeral' })
    })

    // SPEC-025 · AC-21
    it('keeps the running session systemBlocks byte-stable when the override changes and applies it on the next session', async () => {
      const interviewId = seedAssistantInterview()
      harness.create.mockResolvedValue(sdkResponse(ANALYSIS_JSON))
      const { sender, send } = createSender()

      startAssistant(sender, interviewId)
      feedFinalLines(3)
      await waitForCreateCalls(1)
      await waitForActive(send)

      // Override guardado A MITAD de sesión: no debe tocar el prefijo en curso
      repository.saveCustomPromptOverride('assistant', 'Nueva persona en caliente.')
      vi.setSystemTime(BASE_TIME_MS + MIN_INTERVAL_MS + 1000)
      feedFinalLines(3)
      await waitForCreateCalls(2)

      const firstSystem = systemOfCall(0)
      const secondSystem = systemOfCall(1)
      expect(JSON.stringify(secondSystem)).toBe(JSON.stringify(firstSystem))
      const secondBlocks = secondSystem as Array<{ text: string }>
      expect(secondBlocks[0].text).not.toContain('Nueva persona en caliente.')

      // La SIGUIENTE sesión sí arranca con el override
      stopAssistant()
      const next = createSender()
      startAssistant(next.sender, interviewId)
      feedFinalLines(3)
      await waitForCreateCalls(3)

      const thirdBlocks = systemOfCall(2) as Array<{ text: string }>
      expect(thirdBlocks[0].text.startsWith('Nueva persona en caliente.')).toBe(true)
    })
  })
})
