/**
 * SPEC-059: visibilidad de la sección «Objetivos» en el detalle. Deja de ser
 * incondicional (SPEC-025): sin guión y sin objetivos no aporta nada —los
 * objetivos los propone el guión— y compite con la única acción que importa en
 * ese momento, generar el guión desde el banner de onboarding. En cuanto hay
 * guión u objetivos (incluidos los añadidos a mano) vuelve a mostrarse: ocultar
 * datos creados por el usuario no es limpiar.
 * Generated by QA Dev agent.
 *
 * Frontera de mocking: window.api (installMockApi). Las secciones se montan
 * REALES a través de las dos páginas de detalle, porque la spec exige el
 * comportamiento en ambas.
 */
import { render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { CaptureDetailPage } from '@/pages/CaptureDetailPage'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import type { Company, Discovery, Interview } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const DISCOVERY: Discovery = {
  id: 'd-1',
  name: 'Discovery de julio',
  objectives: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactIds: [],
    interviewGroupId: null,
    templateId: 'tpl-1',
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

/** Captura sin empresa (SPEC-020): misma entrevista sin companyId. */
function capture(overrides: Partial<Interview> = {}): Interview {
  return interview({ companyId: null, title: 'Captura sin empresa', ...overrides })
}

function setInterview(value: Interview): void {
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: value })
}

function renderInterviewDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route
            path="/discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
            element={<InterviewDetailPage />}
          />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

function renderCaptureDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/captures/i-1']}>
        <Routes>
          <Route path="/captures/:id" element={<CaptureDetailPage />} />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

/**
 * Botón «Generar guión» del paso 2 del banner, listo para clicar: espera al
 * heading de la sección Guión (asíncrono, Skeleton de NoteScriptSections) y
 * después a que el botón espejado quede habilitado — entre el montaje de la
 * sección y la resolución de la clave el registro lo deja deshabilitado, así
 * que este orden nunca deja pasar el estado sin registrar (botón habilitado
 * pero no-op).
 */
async function bannerGenerateButton(): Promise<HTMLElement> {
  const banner = await screen.findByTestId('interview-onboarding-banner')
  await screen.findByRole('heading', { name: 'Guión' })
  await waitFor(() => expect(within(banner).getByTestId('onboarding-step-action')).toBeEnabled())
  return within(banner).getByTestId('onboarding-step-action')
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.db.getDiscovery).mockResolvedValue({ ok: true, data: DISCOVERY })
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
  setInterview(interview())
})

describe('Objetivos section visibility (SPEC-059)', () => {
  describe('clean state without script', () => {
    // SPEC-059 · AC-01
    it('does not render the Objetivos section on an interview without script and without objectives', async () => {
      renderInterviewDetail()

      // Ancla de sincronización: la página ya pintó su contenido (la sección
      // Guión es lo último en montarse, tras resolver getNoteByInterview)
      expect(await screen.findByRole('heading', { name: 'Guión' })).toBeInTheDocument()
      expect(screen.queryByTestId('objectives-section')).not.toBeInTheDocument()
      expect(screen.queryByRole('heading', { name: 'Objetivos' })).not.toBeInTheDocument()
    })

    // SPEC-059 · AC-02
    it('does not render the Objetivos section on a capture without script and without objectives', async () => {
      setInterview(capture())
      renderCaptureDetail()

      expect(await screen.findByRole('heading', { name: 'Guión' })).toBeInTheDocument()
      expect(screen.queryByTestId('objectives-section')).not.toBeInTheDocument()
      expect(screen.queryByRole('heading', { name: 'Objetivos' })).not.toBeInTheDocument()
    })
  })

  describe('generation from the banner', () => {
    // SPEC-059 · AC-07
    it('reveals the Objetivos section with the proposed objectives when the generation succeeds', async () => {
      const user = userEvent.setup()
      vi.mocked(mockApi.api.llm.generateScript).mockResolvedValue({
        ok: true,
        data: interview({
          scriptMarkdown: '# Bloque 1\n\nPregunta adaptada a Acme',
          objectives: ['Entender el proceso actual', 'Cuantificar el dolor'],
          status: 'prepared'
        })
      })
      renderInterviewDetail()

      expect(screen.queryByTestId('objectives-section')).not.toBeInTheDocument()
      await user.click(await bannerGenerateButton())

      const section = await screen.findByTestId('objectives-section')
      expect(within(section).getByLabelText('Objetivo 1')).toHaveValue('Entender el proceso actual')
      expect(within(section).getByLabelText('Objetivo 2')).toHaveValue('Cuantificar el dolor')
    })

    // SPEC-059 · AC-09
    it('keeps the Objetivos section hidden and toasts the error when the generation fails', async () => {
      const user = userEvent.setup()
      vi.mocked(mockApi.api.llm.generateScript).mockResolvedValue({
        ok: false,
        error: {
          kind: 'network',
          message:
            'No se pudo conectar con la API de Anthropic. Comprueba tu conexión e inténtalo de nuevo.'
        }
      })
      renderInterviewDetail()

      await user.click(await bannerGenerateButton())

      const toasts = await screen.findAllByText(
        'No se pudo conectar con la API de Anthropic. Comprueba tu conexión e inténtalo de nuevo.'
      )
      expect(toasts.length).toBeGreaterThanOrEqual(1)
      expect(screen.queryByTestId('objectives-section')).not.toBeInTheDocument()
    })
  })

  describe('with content', () => {
    // SPEC-059 · AC-10
    it('renders the Objetivos section on an interview with script', async () => {
      setInterview(
        interview({
          scriptMarkdown: '# Bloque 1\n\nPregunta adaptada a Acme',
          objectives: ['Entender el proceso actual'],
          status: 'prepared'
        })
      )
      renderInterviewDetail()

      const section = await screen.findByTestId('objectives-section')
      expect(within(section).getByRole('heading', { name: 'Objetivos' })).toBeInTheDocument()
      expect(within(section).getByLabelText('Objetivo 1')).toHaveValue('Entender el proceso actual')
    })

    // SPEC-059 · AC-12: los objetivos añadidos a mano antes del guión son datos
    // del usuario — la limpieza nunca los esconde
    it('renders the Objetivos section without script when there are manually added objectives', async () => {
      setInterview(interview({ objectives: ['Objetivo añadido a mano'] }))
      renderInterviewDetail()

      const section = await screen.findByTestId('objectives-section')
      expect(within(section).getByLabelText('Objetivo 1')).toHaveValue('Objetivo añadido a mano')
      // Sigue sin guión: la sección Guión conserva su empty state
      expect(await screen.findByText('Aún no hay guión')).toBeInTheDocument()
    })
  })
})
