/**
 * SPEC-025: editor markdown WYSIWYG (componente compartido guión/nota).
 * Generated by QA Dev agent.
 *
 * Estrategia jsdom+ProseMirror: la escritura libre (beforeinput nativo) no es
 * reproducible en jsdom, pero SÍ lo son (a) los comandos de la toolbar (van
 * por la API de TipTap, no por eventos nativos) y (b) los atajos de teclado
 * que ProseMirror implementa como keydown handlers propios (Mod-a, Backspace).
 * La selección se consigue con Ctrl+A sobre el editor enfocado.
 */
import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { TooltipProvider } from '@/components/ui/tooltip'
import { MarkdownEditor } from '@/components/markdown/MarkdownEditor'

const TOOLBAR_LABELS = [
  'Encabezado 2',
  'Encabezado 3',
  'Negrita',
  'Cursiva',
  'Lista con viñetas',
  'Lista numerada',
  'Cita'
]

function renderEditor(
  initialMarkdown: string,
  onChange: (markdown: string) => void = vi.fn()
): ReturnType<typeof render> {
  return render(
    <TooltipProvider>
      <MarkdownEditor
        initialMarkdown={initialMarkdown}
        onChange={onChange}
        ariaLabel="Contenido"
        testId="markdown-editor"
      />
    </TooltipProvider>
  )
}

function editorRoot(): HTMLElement {
  return screen.getByTestId('markdown-editor')
}

/** El área editable (contenteditable con el aria-label del editor). */
function editableArea(): HTMLElement {
  return within(editorRoot()).getByLabelText('Contenido')
}

beforeEach(() => {
  vi.clearAllMocks()
})

describe('MarkdownEditor', () => {
  it('renders the 7-action toolbar with accessible names and the initial markdown as rich content', () => {
    renderEditor('# Título\n\nTexto con **negrita**')

    const toolbar = within(editorRoot()).getByRole('toolbar', { name: 'Formato' })
    TOOLBAR_LABELS.forEach((label) => {
      expect(within(toolbar).getByRole('button', { name: label })).toBeInTheDocument()
    })

    const area = editableArea()
    // Sin sintaxis markdown en crudo: heading real y strong real
    const heading = within(area).getByText('Título')
    expect(heading.closest('h1')).not.toBeNull()
    const bold = within(area).getByText('negrita')
    expect(bold.closest('strong')).not.toBeNull()
    expect(area.textContent).not.toContain('#')
    expect(area.textContent).not.toContain('**')
  })

  // SPEC-025 · AC-13
  it('applies bold visually to the selected text when Negrita is clicked, marking the button pressed', async () => {
    const user = userEvent.setup()
    renderEditor('Texto sin formato')

    // Selección: enfocar el contenteditable y Ctrl+A (keymap de ProseMirror)
    editableArea().focus()
    await user.keyboard('{Control>}a{/Control}')
    await user.click(within(editorRoot()).getByRole('button', { name: 'Negrita' }))

    await waitFor(() => {
      const text = within(editableArea()).getByText('Texto sin formato')
      expect(text.closest('strong')).not.toBeNull()
    })
    expect(within(editorRoot()).getByRole('button', { name: 'Negrita' })).toHaveAttribute(
      'aria-pressed',
      'true'
    )
  })

  it('emits the serialized markdown through onChange after a toolbar block change', async () => {
    const user = userEvent.setup()
    const onChange = vi.fn()
    renderEditor('Texto sin formato', onChange)

    await user.click(within(editorRoot()).getByRole('button', { name: 'Encabezado 2' }))

    await waitFor(() => expect(onChange).toHaveBeenCalled())
    expect(onChange).toHaveBeenLastCalledWith('## Texto sin formato')
  })

  it('does not emit onChange while the document is untouched (round-trip guard)', () => {
    const onChange = vi.fn()
    renderEditor('# Título\n\n- uno\n- dos', onChange)

    expect(onChange).not.toHaveBeenCalled()
  })
})
