/**
 * SPEC-027: disposición de las secciones Nota y Guión en el detalle
 * (apilado condicional vs pestañas "Notas"/"Guión").
 * Generated by QA Dev agent.
 *
 * Monta NoteScriptSections directamente (las páginas solo lo componen tras la
 * Grabación; la cabecera se cubre en las suites de SPEC-013/020). Radix Tabs
 * con forceMount mantiene AMBOS paneles montados y la ocultación del inactivo
 * es por clase Tailwind (data-[state=inactive]:hidden), que jsdom NO aplica
 * (lección 15) → los dos paneles coexisten para los queries de rol y toda
 * aserción de contenido/acciones debe scopearse al tabpanel por data-state
 * (helper activePanel/inactivePanel); el estado activo se asierta por
 * aria-selected.
 */
import { render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import { TooltipProvider } from '@/components/ui/tooltip'
import { NoteScriptSections } from '@/components/interviews/NoteScriptSections'
import type { Interview, Note, NoteTemplate } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

const TRANSCRIPT_PATH = '/tmp/maurya-recordings/entrevista.transcript.json'
const SCRIPT_MD = '# Guión adaptado\n\n## Bloque 1\nPregunta adaptada a Acme'

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactId: null,
    templateId: 'tpl-1',
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

const NOTE: Note = {
  id: 'n-1',
  interviewId: 'i-1',
  contentMarkdown: '## Dolores\n\nEl CTO gestiona todo a mano.',
  createdAt: '2026-07-04T11:00:00.000Z',
  updatedAt: '2026-07-04T11:00:00.000Z'
}

const NOTE_TEMPLATE: NoteTemplate = {
  id: 'nt-1',
  name: 'Notas discovery',
  context: 'Céntrate en dolores.',
  sections: [{ title: 'Dolores', description: 'Problemas detectados' }],
  createdAt: '2026-07-04T09:00:00.000Z',
  updatedAt: '2026-07-04T09:00:00.000Z'
}

function setNote(value: Note | null): void {
  vi.mocked(mockApi.api.db.getNoteByInterview).mockResolvedValue({ ok: true, data: value })
}

function renderSections(value: Interview): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter>
        <NoteScriptSections interview={value} onInterviewUpdated={vi.fn()} />
      </MemoryRouter>
    </TooltipProvider>
  )
}

/** Headings h3 de sección visibles, en orden documental. */
async function sectionTitles(): Promise<Array<string | null>> {
  const headings = await screen.findAllByRole('heading', { level: 3 })
  return headings.map((heading) => heading.textContent)
}

/** Tabpanel por estado (con forceMount ambos están montados; jsdom no aplica la clase que oculta el inactivo). */
function panelByState(state: 'active' | 'inactive'): HTMLElement {
  const panel = screen
    .getAllByRole('tabpanel', { hidden: true })
    .find((candidate) => candidate.getAttribute('data-state') === state)
  if (panel === undefined) {
    throw new Error(`No hay tabpanel en estado ${state}`)
  }
  return panel
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  setNote(null)
  vi.mocked(mockApi.api.db.listNoteTemplates).mockResolvedValue({
    ok: true,
    data: [NOTE_TEMPLATE]
  })
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
})

describe('NoteScriptSections', () => {
  describe('stacked layouts', () => {
    // SPEC-027 · AC-01
    it('shows only the Guión section (empty state) when there is no script, no note and no transcript', async () => {
      renderSections(interview())

      expect(await screen.findByRole('heading', { name: 'Guión', level: 3 })).toBeInTheDocument()
      expect(await screen.findByText('Aún no hay guión')).toBeInTheDocument()
      expect(screen.queryByRole('heading', { name: 'Nota', level: 3 })).not.toBeInTheDocument()
      expect(screen.queryByRole('tablist')).not.toBeInTheDocument()
    })

    // SPEC-027 · AC-02
    it('shows the Guión section plus the note generation controls when there is a transcript but no script and no note', async () => {
      renderSections(interview({ transcriptPath: TRANSCRIPT_PATH, status: 'recorded' }))

      expect(await screen.findByRole('heading', { name: 'Guión', level: 3 })).toBeInTheDocument()
      expect(await screen.findByRole('heading', { name: 'Nota', level: 3 })).toBeInTheDocument()
      expect(await screen.findByRole('button', { name: 'Generar nota' })).toBeInTheDocument()
      expect(screen.getByRole('combobox', { name: 'Note-template' })).toBeInTheDocument()
      expect(screen.queryByRole('tablist')).not.toBeInTheDocument()
    })

    // SPEC-027 · AC-03
    it('stacks the full Guión section and the note generation controls without tabs when there is a script but no note', async () => {
      renderSections(interview({ scriptMarkdown: SCRIPT_MD, status: 'prepared' }))

      expect(await screen.findByRole('heading', { name: 'Guión', level: 3 })).toBeInTheDocument()
      // Guión completa: contenido renderizado + acciones de lectura
      expect(await screen.findByText('Pregunta adaptada a Acme')).toBeInTheDocument()
      expect(screen.getByRole('button', { name: 'Editar' })).toBeInTheDocument()
      expect(await screen.findByRole('heading', { name: 'Nota', level: 3 })).toBeInTheDocument()
      expect(screen.queryByRole('tablist')).not.toBeInTheDocument()
    })

    // SPEC-027 · AC-08
    it('stacks the full Nota section first and the Guión section below, without tabs, when there is a note but no script', async () => {
      setNote(NOTE)
      renderSections(interview({ transcriptPath: TRANSCRIPT_PATH, status: 'summarized' }))

      await screen.findByText('El CTO gestiona todo a mano.')
      const titles = await sectionTitles()
      expect(titles.indexOf('Nota')).toBeGreaterThanOrEqual(0)
      expect(titles.indexOf('Guión')).toBeGreaterThan(titles.indexOf('Nota'))
      expect(await screen.findByText('Aún no hay guión')).toBeInTheDocument()
      expect(screen.queryByRole('tablist')).not.toBeInTheDocument()
    })
  })

  describe('tabs when both exist', () => {
    function bothExist(): Interview {
      return interview({
        scriptMarkdown: SCRIPT_MD,
        transcriptPath: TRANSCRIPT_PATH,
        status: 'summarized'
      })
    }

    // SPEC-027 · AC-04
    it('renders the "Notas" and "Guión" tabs, in that order, when both note and script exist', async () => {
      setNote(NOTE)
      renderSections(bothExist())

      const tablist = await screen.findByRole('tablist')
      const tabs = within(tablist).getAllByRole('tab')
      expect(tabs.map((tab) => tab.textContent)).toEqual(['Notas', 'Guión'])
      expect(screen.getByTestId('note-script-tabs')).toBeInTheDocument()
    })

    // SPEC-027 · AC-05
    it('activates the "Notas" tab by default showing the note content', async () => {
      setNote(NOTE)
      renderSections(bothExist())

      const notasTab = await screen.findByRole('tab', { name: 'Notas' })
      expect(notasTab).toHaveAttribute('aria-selected', 'true')
      expect(screen.getByRole('tab', { name: 'Guión' })).toHaveAttribute('aria-selected', 'false')
      // El panel activo contiene la nota; el del guión está en estado inactive
      expect(
        await within(panelByState('active')).findByText('El CTO gestiona todo a mano.')
      ).toBeInTheDocument()
      expect(
        within(panelByState('inactive')).queryByText('El CTO gestiona todo a mano.')
      ).toBeNull()
    })

    // SPEC-027 · AC-06
    it('shows the full Guión section (content, Editar and Regenerar) when the "Guión" tab is clicked', async () => {
      const user = userEvent.setup()
      setNote(NOTE)
      renderSections(bothExist())

      await user.click(await screen.findByRole('tab', { name: 'Guión' }))

      expect(screen.getByRole('tab', { name: 'Guión' })).toHaveAttribute('aria-selected', 'true')
      // Scope al panel activo: con forceMount el panel de la nota sigue en el
      // DOM y sus botones colisionarían con los del guión (lección 15)
      const panel = panelByState('active')
      expect(await within(panel).findByText('Pregunta adaptada a Acme')).toBeInTheDocument()
      expect(within(panel).getByRole('button', { name: 'Editar' })).toBeInTheDocument()
      expect(within(panel).getByRole('button', { name: 'Regenerar' })).toBeInTheDocument()
      expect(
        within(panel).getByRole('heading', { name: 'Objetivos', level: 4 })
      ).toBeInTheDocument()
    })

    // SPEC-027 · AC-07
    it('switches to tabs with "Notas" active showing the fresh note after generating it from the stacked layout', async () => {
      const user = userEvent.setup()
      const withScript = interview({
        scriptMarkdown: SCRIPT_MD,
        transcriptPath: TRANSCRIPT_PATH,
        status: 'recorded'
      })
      // Dos fetch iniciales (disposición + sección) sin nota; tras generar, la
      // sección remontada dentro de la pestaña relee la nota ya persistida.
      vi.mocked(mockApi.api.db.getNoteByInterview)
        .mockResolvedValueOnce({ ok: true, data: null })
        .mockResolvedValueOnce({ ok: true, data: null })
        .mockResolvedValue({ ok: true, data: NOTE })
      vi.mocked(mockApi.api.llm.generateNote).mockResolvedValue({
        ok: true,
        data: { interview: { ...withScript, status: 'summarized' }, note: NOTE }
      })
      renderSections(withScript)

      await waitFor(() =>
        expect(screen.getByRole('button', { name: 'Generar nota' })).toBeEnabled()
      )
      await user.click(screen.getByRole('button', { name: 'Generar nota' }))

      const notasTab = await screen.findByRole('tab', { name: 'Notas' })
      expect(notasTab).toHaveAttribute('aria-selected', 'true')
      expect(await screen.findByText('El CTO gestiona todo a mano.')).toBeInTheDocument()
    })

    // SPEC-027 · AC-09
    it('keeps the edit mode and the draft when switching tabs back and forth', async () => {
      const user = userEvent.setup()
      setNote(NOTE)
      renderSections(bothExist())

      // Entrar en edición de la nota (scope al panel activo: el panel del
      // guión también tiene "Editar" y su carga es asíncrona) y hacer un
      // cambio real vía toolbar
      await screen.findByRole('tablist')
      await user.click(
        await within(panelByState('active')).findByRole('button', { name: 'Editar' })
      )
      const editor = await screen.findByTestId('note-markdown-editor')
      await user.click(within(editor).getByRole('button', { name: 'Encabezado 3' }))
      await waitFor(() => {
        expect(within(editor).getByText('Dolores').closest('h3')).not.toBeNull()
      })

      // Ir a Guión y volver: el editor sigue montado con el cambio
      await user.click(screen.getByRole('tab', { name: 'Guión' }))
      await user.click(screen.getByRole('tab', { name: 'Notas' }))

      const editorBack = screen.getByTestId('note-markdown-editor')
      expect(editorBack).toBeInTheDocument()
      expect(within(editorBack).getByText('Dolores').closest('h3')).not.toBeNull()
      expect(screen.getByRole('button', { name: 'Guardar' })).toBeInTheDocument()
    })
  })
})
