/**
 * SPEC-020: Capturas — Sheet "Asignar empresa y contacto" (componente
 * aislado), adaptado por SPEC-046: el Select de contacto único queda DEROGADO
 * — la sección «Participantes» es una lista de Checkbox (N contactos de la
 * empresa elegida) + la fila Checkbox «+ Nuevo contacto» cuyo contacto inline
 * se SUMA a los marcados; sin empresa, texto muted «Elige una empresa para
 * ver sus contactos» (sustituye al DisabledTooltip).
 * Generated by QA Dev agent.
 *
 * Frontera de mocking: bridge window.api (listCompanies/listContacts/
 * assignInterviewCompany). El Sheet de Radix es un Dialog (portal + fondo
 * aria-hidden): las opciones del Select se buscan con screen, el resto
 * scopeado al Sheet.
 */
import { render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { AssignCompanySheet } from '@/components/captures/AssignCompanySheet'
import type { AssignCompanyResult } from '@/types/captures'
import type { Company, Contact, Interview } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle
let onAssigned: ReturnType<typeof vi.fn<(result: AssignCompanyResult) => void>>
let onOpenChange: ReturnType<typeof vi.fn<(open: boolean) => void>>

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const CONTACT: Contact = {
  id: 'ct-1',
  companyId: 'c-1',
  name: 'Jane Doe',
  position: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

/** Segundo contacto de la empresa (SPEC-046: multiselección de participantes). */
const CONTACT_JOHN: Contact = {
  id: 'ct-2',
  companyId: 'c-1',
  name: 'John Smith',
  position: 'CEO',
  createdAt: '2026-07-02T12:30:00.000Z',
  updatedAt: '2026-07-02T12:30:00.000Z',
  linkedinUrl: null
}

const INTERVIEW: Interview = {
  id: 'i-1',
  discoveryId: 'd-1',
  companyId: null,
  contactIds: [],
  interviewGroupId: null,
  templateId: null,
  title: 'Captura sin empresa',
  status: 'draft',
  scriptMarkdown: null,
  objectives: [],
  wavPath: null,
  transcriptPath: null,
  createdAt: '2026-07-10T10:00:00.000Z',
  updatedAt: '2026-07-10T10:00:00.000Z'
}

function renderSheet(): RenderResult {
  return render(
    <TooltipProvider>
      <AssignCompanySheet
        open
        onOpenChange={onOpenChange}
        interview={INTERVIEW}
        discoveryName="Vertical Sanidad"
        onAssigned={onAssigned}
      />
      <Toaster />
    </TooltipProvider>
  )
}

async function findSheet(): Promise<HTMLElement> {
  return await screen.findByTestId('assign-company-sheet')
}

/** Selecciona una opción del Select "Empresa" (las opciones viven en un portal). */
async function chooseCompany(
  user: ReturnType<typeof userEvent.setup>,
  optionName: string
): Promise<void> {
  const sheet = await findSheet()
  await user.click(within(sheet).getByRole('combobox', { name: 'Empresa' }))
  await user.click(await screen.findByRole('option', { name: optionName }))
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  onAssigned = vi.fn<(result: AssignCompanyResult) => void>()
  onOpenChange = vi.fn<(open: boolean) => void>()
  vi.mocked(mockApi.api.db.listCompanies).mockResolvedValue({ ok: true, data: [COMPANY] })
  vi.mocked(mockApi.api.db.listContacts).mockResolvedValue({ ok: true, data: [CONTACT] })
})

describe('AssignCompanySheet', () => {
  // SPEC-020 · AC-23 (adaptado por SPEC-043: empresas globales) + SPEC-046 ·
  // AC-23: la sección Participantes (lista de Checkbox) sustituye al Select
  // de contacto y queda gateada tras elegir empresa con el texto muted
  it('offers every company in the system plus "+ Nueva empresa", and gates the Participantes checklist behind choosing a company', async () => {
    vi.mocked(mockApi.api.db.listContacts).mockResolvedValue({
      ok: true,
      data: [CONTACT, CONTACT_JOHN]
    })
    const user = userEvent.setup()
    renderSheet()

    const sheet = await findSheet()
    // Descripción con el discovery de la captura
    expect(sheet).toHaveTextContent(
      'La captura se moverá a la empresa dentro de su discovery «Vertical Sanidad».'
    )

    // Sin empresa elegida: texto muted en lugar de la lista de participantes
    expect(within(sheet).getByText('Elige una empresa para ver sus contactos')).toBeInTheDocument()
    expect(within(sheet).queryByTestId('interview-participants')).not.toBeInTheDocument()
    expect(within(sheet).queryByRole('checkbox', { name: '+ Nuevo contacto' })).toBeNull()

    // Empresa: TODAS las empresas del sistema (SPEC-043) + "+ Nueva empresa"
    await user.click(within(sheet).getByRole('combobox', { name: 'Empresa' }))
    expect(await screen.findByRole('option', { name: 'Acme Corp' })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: '+ Nueva empresa' })).toBeInTheDocument()
    expect(vi.mocked(mockApi.api.db.listCompanies)).toHaveBeenCalledWith()
    await user.click(screen.getByRole('option', { name: 'Acme Corp' }))

    // Con empresa existente: Checkbox por contacto + fila "+ Nuevo contacto"
    const participants = await within(sheet).findByTestId('interview-participants')
    expect(
      await within(participants).findByRole('checkbox', { name: /Jane Doe/ })
    ).not.toBeChecked()
    expect(within(participants).getByRole('checkbox', { name: /John Smith/ })).not.toBeChecked()
    expect(within(sheet).getByRole('checkbox', { name: '+ Nuevo contacto' })).not.toBeChecked()
    expect(
      within(sheet).queryByText('Elige una empresa para ver sus contactos')
    ).not.toBeInTheDocument()
    expect(vi.mocked(mockApi.api.db.listContacts)).toHaveBeenCalledWith('c-1')
  })

  // SPEC-020 · AC-24 + SPEC-046 · AC-24: con empresa NUEVA inline no hay
  // contactos previos que listar — el único participante posible es el nuevo
  it('shows the inline Nombre/Website/LinkedIn fields when "+ Nueva empresa" is selected, without a second modal', async () => {
    const user = userEvent.setup()
    renderSheet()

    await chooseCompany(user, '+ Nueva empresa')

    const sheet = await findSheet()
    expect(within(sheet).getByLabelText('Nombre')).toBeInTheDocument()
    expect(within(sheet).getByLabelText('Website')).toBeInTheDocument()
    expect(within(sheet).getByLabelText('LinkedIn')).toBeInTheDocument()
    // Sigue siendo el mismo Sheet: no se abre un segundo dialog
    expect(screen.getAllByRole('dialog')).toHaveLength(1)

    // SPEC-046 · AC-24: sin checklist de participantes (la empresa recién
    // creada no tiene contactos) — solo la opción "+ Nuevo contacto"
    expect(within(sheet).queryByTestId('interview-participants')).not.toBeInTheDocument()
    expect(within(sheet).getByRole('checkbox', { name: '+ Nuevo contacto' })).toBeInTheDocument()
    expect(within(sheet).queryByText('Jane Doe')).not.toBeInTheDocument()
  })

  // SPEC-020 · AC-25, adaptado por SPEC-046: "+ Nuevo contacto" pasa de opción
  // del Select derogado a fila Checkbox que despliega los Inputs inline
  it('shows the inline Nombre/Posición/LinkedIn fields when the "+ Nuevo contacto" checkbox is checked', async () => {
    const user = userEvent.setup()
    renderSheet()

    await chooseCompany(user, 'Acme Corp')
    const sheet = await findSheet()
    await user.click(within(sheet).getByRole('checkbox', { name: '+ Nuevo contacto' }))

    expect(within(sheet).getByLabelText('Nombre')).toBeInTheDocument()
    expect(within(sheet).getByLabelText('Posición')).toBeInTheDocument()
    expect(within(sheet).getByLabelText('LinkedIn')).toBeInTheDocument()
  })

  // SPEC-020 · AC-26
  it('shows the inline "Campo requerido" error and persists nothing when the new company name is empty', async () => {
    const user = userEvent.setup()
    renderSheet()

    await chooseCompany(user, '+ Nueva empresa')
    const sheet = await findSheet()
    await user.click(within(sheet).getByRole('button', { name: 'Asignar' }))

    expect(await within(sheet).findByText('Campo requerido')).toBeInTheDocument()
    expect(vi.mocked(mockApi.api.db.assignInterviewCompany)).not.toHaveBeenCalled()
    expect(onAssigned).not.toHaveBeenCalled()
  })

  // SPEC-020 · AC-28 (renderer: UNA sola operación compuesta con los datos
  // inline), adaptado por SPEC-046: contactIds viaja vacío con empresa nueva
  // y el resultado llega con contacts (lista)
  it('assigns creating the new company and contact in a single bridge operation and notifies the assignment', async () => {
    const assigned: AssignCompanyResult = {
      interview: { ...INTERVIEW, companyId: 'c-9', contactIds: ['ct-9'] },
      company: { ...COMPANY, id: 'c-9', name: 'Globex' },
      contacts: [{ ...CONTACT, id: 'ct-9', companyId: 'c-9', name: 'John Smith' }]
    }
    vi.mocked(mockApi.api.db.assignInterviewCompany).mockResolvedValue({
      ok: true,
      data: assigned
    })
    const user = userEvent.setup()
    renderSheet()

    await chooseCompany(user, '+ Nueva empresa')
    const sheet = await findSheet()
    await user.type(within(sheet).getByLabelText('Nombre'), 'Globex')
    await user.click(within(sheet).getByRole('checkbox', { name: '+ Nuevo contacto' }))
    // Tras marcar "+ Nuevo contacto" hay dos grupos de campos inline: el del
    // contacto es el segundo "Nombre"
    const nameInputs = within(sheet).getAllByLabelText('Nombre')
    await user.type(nameInputs[1], 'John Smith')
    await user.click(within(sheet).getByRole('button', { name: 'Asignar' }))

    await waitFor(() =>
      expect(vi.mocked(mockApi.api.db.assignInterviewCompany)).toHaveBeenCalledWith('i-1', {
        newCompany: { name: 'Globex', website: null, linkedinUrl: null },
        contactIds: [],
        newContact: { name: 'John Smith', position: null, linkedinUrl: null }
      })
    )
    expect(vi.mocked(mockApi.api.db.assignInterviewCompany)).toHaveBeenCalledTimes(1)
    expect(onAssigned).toHaveBeenCalledWith(assigned)
    expect((await screen.findAllByText('Empresa asignada')).length).toBeGreaterThanOrEqual(1)
    expect(onOpenChange).toHaveBeenCalledWith(false)
  })

  // SPEC-046 · AC-23 (renderer): N contactos marcados de la empresa elegida +
  // contacto nuevo inline — los marcados viajan en contactIds (en el orden de
  // marcado) y el nuevo en newContact, todo en UNA operación
  it('assigns the marked participants plus the inline new contact in a single bridge operation with contactIds in marking order', async () => {
    vi.mocked(mockApi.api.db.listContacts).mockResolvedValue({
      ok: true,
      data: [CONTACT, CONTACT_JOHN]
    })
    const assigned: AssignCompanyResult = {
      interview: { ...INTERVIEW, companyId: 'c-1', contactIds: ['ct-2', 'ct-1', 'ct-9'] },
      company: COMPANY,
      contacts: [
        CONTACT_JOHN,
        CONTACT,
        { ...CONTACT, id: 'ct-9', name: 'Ada López', position: 'CEO' }
      ]
    }
    vi.mocked(mockApi.api.db.assignInterviewCompany).mockResolvedValue({
      ok: true,
      data: assigned
    })
    const user = userEvent.setup()
    renderSheet()

    await chooseCompany(user, 'Acme Corp')
    const sheet = await findSheet()
    const participants = await within(sheet).findByTestId('interview-participants')
    // Orden de marcado: John primero, Jane después (manda sobre el de alta)
    await user.click(await within(participants).findByRole('checkbox', { name: /John Smith/ }))
    await user.click(within(participants).getByRole('checkbox', { name: /Jane Doe/ }))
    await user.click(within(sheet).getByRole('checkbox', { name: '+ Nuevo contacto' }))
    await user.type(within(sheet).getByLabelText('Nombre'), 'Ada López')
    await user.click(within(sheet).getByRole('button', { name: 'Asignar' }))

    await waitFor(() =>
      expect(vi.mocked(mockApi.api.db.assignInterviewCompany)).toHaveBeenCalledWith('i-1', {
        companyId: 'c-1',
        contactIds: ['ct-2', 'ct-1'],
        newContact: { name: 'Ada López', position: null, linkedinUrl: null }
      })
    )
    expect(vi.mocked(mockApi.api.db.assignInterviewCompany)).toHaveBeenCalledTimes(1)
    expect(onAssigned).toHaveBeenCalledWith(assigned)
    expect(onOpenChange).toHaveBeenCalledWith(false)
  })

  // SPEC-046 · AC-12 (invariante compartida con el Dialog del grupo): cambiar
  // la empresa del Select vacía la selección de participantes marcada
  it('empties the marked participants selection when the company select changes', async () => {
    const OTHER_COMPANY = { ...COMPANY, id: 'c-2', name: 'Globex' }
    vi.mocked(mockApi.api.db.listCompanies).mockResolvedValue({
      ok: true,
      data: [COMPANY, OTHER_COMPANY]
    })
    vi.mocked(mockApi.api.db.listContacts).mockImplementation(async (companyId: string) => ({
      ok: true,
      data:
        companyId === 'c-1'
          ? [CONTACT, CONTACT_JOHN]
          : [{ ...CONTACT, id: 'ct-3', companyId: 'c-2', name: 'Otra Persona' }]
    }))
    const user = userEvent.setup()
    renderSheet()

    await chooseCompany(user, 'Acme Corp')
    const sheet = await findSheet()
    const participants = await within(sheet).findByTestId('interview-participants')
    await user.click(await within(participants).findByRole('checkbox', { name: /Jane Doe/ }))
    expect(within(participants).getByRole('checkbox', { name: /Jane Doe/ })).toBeChecked()

    // Cambiar de empresa: la selección se vacía (invariante v3)
    await chooseCompany(user, 'Globex')
    const refreshed = await within(sheet).findByTestId('interview-participants')
    const otherCheckbox = await within(refreshed).findByRole('checkbox', { name: /Otra Persona/ })
    expect(otherCheckbox).not.toBeChecked()
    expect(within(refreshed).queryByRole('checkbox', { name: /Jane Doe/ })).toBeNull()
  })

  // SPEC-020 · AC-30
  it('keeps the Sheet open with a destructive toast and no half-applied state when the bridge fails', async () => {
    vi.mocked(mockApi.api.db.assignInterviewCompany).mockResolvedValue({
      ok: false,
      error: { kind: 'storage', message: 'Fallo simulado al asignar' }
    })
    const user = userEvent.setup()
    renderSheet()

    await chooseCompany(user, 'Acme Corp')
    const sheet = await findSheet()
    await user.click(within(sheet).getByRole('button', { name: 'Asignar' }))

    expect((await screen.findAllByText('Fallo simulado al asignar')).length).toBeGreaterThanOrEqual(
      1
    )
    // El Sheet permanece abierto con el formulario intacto
    expect(screen.getByTestId('assign-company-sheet')).toBeInTheDocument()
    expect(within(sheet).getByRole('combobox', { name: 'Empresa' })).toHaveTextContent('Acme Corp')
    expect(onAssigned).not.toHaveBeenCalled()
    expect(onOpenChange).not.toHaveBeenCalledWith(false)
    // Y se puede reintentar: el botón vuelve a estar habilitado
    await waitFor(() =>
      expect(within(sheet).getByRole('button', { name: 'Asignar' })).toBeEnabled()
    )
  })
})
