/**
 * SPEC-034: Controles de grabación reubicados en la Captura — permisos y
 * selector de micrófono en la top bar (portal al slot del Layout) y «Iniciar
 * grabación» en la cabecera, solo en estado Preparación; la sección
 * «Grabación» de la captura pierde esos controles (los Alerts de error se
 * quedan) y el detalle de entrevista clásico no cambia.
 * Generated by QA Dev agent.
 *
 * Arnés: a diferencia de CaptureDetailPage.test.tsx (SPEC-020, monta la página
 * suelta), aquí las rutas se montan BAJO <Layout/> replicando la tabla de
 * App.tsx — sin Layout el TopBarSlotContext es null y el portal es no-op, y
 * estos ACs viven precisamente en la top bar. Fronteras de mocking idénticas
 * a RecordingSection.test.tsx (SPEC-015): servicios del spike
 * (permissionsService/captureService/wavRecorderService) + bridge window.api.
 * SPEC-019: todo arranque atraviesa el aviso de consentimiento (localStorage
 * limpio en cada test → sin preferencia persistida).
 * Lecciones: headings/badges asíncronos con findBy*; Radix Select en jsdom =
 * click al combobox + click a la option (patrón AssignCompanySheet).
 */
import { render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Layout } from '@/components/layout/Layout'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { CaptureDetailPage } from '@/pages/CaptureDetailPage'
import { CapturesPage } from '@/pages/CapturesPage'
import { DiscoveriesPage } from '@/pages/DiscoveriesPage'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import {
  acquireMicrophoneStream,
  acquireSystemAudioStream,
  listAudioInputDevices
} from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { Company, Contact, Discovery, Interview } from '@/types/domain'
import { createFakeAudioStream } from '../../helpers/fakeMediaStream'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

const recorderMock = vi.hoisted(() => ({
  start: vi.fn(),
  stop: vi.fn(),
  getLevels: vi.fn(),
  durationSeconds: 0
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = recorderMock.start
    stop = recorderMock.stop
    getLevels = recorderMock.getLevels
    get durationSeconds(): number {
      return recorderMock.durationSeconds
    }
    get samplesWritten(): number {
      return recorderMock.durationSeconds * 16000
    }
  }
}))

let mockApi: MockApiHandle

const DISCOVERY: Discovery = {
  id: 'd-1',
  name: 'Vertical Sanidad',
  objectives: null,
  createdAt: '2026-07-01T09:00:00.000Z',
  updatedAt: '2026-07-01T09:00:00.000Z'
}

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const CONTACT: Contact = {
  id: 'ct-1',
  companyId: 'c-1',
  name: 'Jane Doe',
  position: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

function capture(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: null,
    contactIds: [],
    interviewGroupId: null,
    templateId: null,
    title: 'Captura sin empresa',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-10T10:00:00.000Z',
    updatedAt: '2026-07-10T10:00:00.000Z',
    ...overrides
  }
}

const WAV_PATH = '/tmp/maurya-recordings/captura-i-1.wav'
const TRANSCRIPT_PATH = '/tmp/maurya-recordings/captura-i-1.transcript.json'

/** Captura en estado Grabada (wavPath asociado, sin «Nueva grabación» pedida). */
const RECORDED = capture({
  wavPath: WAV_PATH,
  transcriptPath: TRANSCRIPT_PATH,
  status: 'recorded'
})

function setInterview(value: Interview): void {
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: value })
}

function setupGrantedCapture(): void {
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  vi.mocked(acquireMicrophoneStream).mockResolvedValue(createFakeAudioStream().stream)
  vi.mocked(acquireSystemAudioStream).mockResolvedValue(createFakeAudioStream().stream)
}

/**
 * Réplica de la tabla de rutas de App.tsx BAJO Layout (las que este arnés
 * necesita): el portal de la top bar solo existe dentro del shell real.
 */
function renderAt(initialEntry: string): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={[initialEntry]}>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route path="captures" element={<CapturesPage />} />
            <Route path="captures/:id" element={<CaptureDetailPage />} />
            <Route path="discoveries" element={<DiscoveriesPage />} />
            <Route
              path="discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
              element={<InterviewDetailPage />}
            />
          </Route>
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

function topBar(): HTMLElement {
  return screen.getByRole('banner')
}

/** La sección «Grabación» (el <section> que envuelve su heading). */
async function grabacionSection(): Promise<HTMLElement> {
  const heading = await screen.findByRole('heading', { name: 'Grabación' })
  const section = heading.closest('section')
  if (section === null) {
    throw new Error('El heading «Grabación» debe vivir dentro de un <section>')
  }
  return section
}

/**
 * Arranca la grabación desde el botón de la CABECERA (capture-start-button)
 * atravesando el aviso de consentimiento (SPEC-019) sin persistir preferencia.
 */
async function startFromHeader(user: ReturnType<typeof userEvent.setup>): Promise<void> {
  await user.click(await screen.findByTestId('capture-start-button'))
  const consent = await screen.findByRole('alertdialog')
  expect(within(consent).getByRole('heading', { name: 'Aviso de grabación' })).toBeInTheDocument()
  await user.click(within(consent).getByRole('button', { name: 'Entendido, iniciar grabación' }))
  await screen.findByRole('button', { name: 'Detener' })
}

beforeEach(() => {
  vi.clearAllMocks()
  // Aislamiento: consentimiento SPEC-019 sin preferencia y sidebar expandido
  window.localStorage.clear()
  mockApi = installMockApi()
  setInterview(capture())
  vi.mocked(mockApi.api.db.getDiscovery).mockResolvedValue({ ok: true, data: DISCOVERY })
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.db.getContact).mockResolvedValue({ ok: true, data: CONTACT })
  // Sin Alert de clave en ScriptSection para no colisionar con los role=alert
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  recorderMock.start.mockResolvedValue(undefined)
  recorderMock.stop.mockResolvedValue(undefined)
  recorderMock.getLevels.mockReturnValue({ microphone: 42, system: 17 })
  vi.mocked(mockApi.api.recording.stop).mockResolvedValue({
    filePath: WAV_PATH,
    durationSeconds: 95,
    sizeBytes: 44 + 95 * 16000 * 4,
    sampleRate: 16000,
    channels: 2,
    transcriptPath: null,
    latency: null,
    interview: null
  })
})

describe('CaptureDetailPage (SPEC-034 recording controls)', () => {
  describe('top bar (Preparación)', () => {
    // SPEC-034 · AC-01
    it('shows the compact permission badges and the "Micrófono" select inside the top bar banner next to "Buscar"', async () => {
      renderAt('/captures/i-1')

      const controls = await within(topBar()).findByTestId('topbar-capture-controls')
      // Badges de permisos con sus literales (asíncronos: llegan al resolver TCC)
      expect(await within(controls).findAllByText('Concedido')).toHaveLength(2)
      expect(within(controls).getByText('Micrófono')).toBeInTheDocument()
      expect(within(controls).getByText('Audio del sistema')).toBeInTheDocument()
      // Selector de micrófono compacto, operable, con su aria-label
      expect(within(controls).getByRole('combobox', { name: 'Micrófono' })).toBeEnabled()
      // Conviven en el mismo header que el disparador de la búsqueda global
      expect(within(topBar()).getByRole('button', { name: 'Buscar' })).toBeInTheDocument()
    })

    // SPEC-034 · AC-02
    it('starts the capture with the microphone chosen in the top bar select', async () => {
      const user = userEvent.setup()
      vi.mocked(listAudioInputDevices).mockResolvedValue([
        { deviceId: 'mic-usb', label: 'USB Mic' }
      ])
      setupGrantedCapture()
      renderAt('/captures/i-1')

      const controls = await screen.findByTestId('topbar-capture-controls')
      await user.click(within(controls).getByRole('combobox', { name: 'Micrófono' }))
      await user.click(await screen.findByRole('option', { name: 'USB Mic' }))
      await startFromHeader(user)

      // Misma semántica que el selector que vivía dentro de la sección: el
      // arranque adquiere el stream del dispositivo elegido en la top bar
      expect(vi.mocked(acquireMicrophoneStream)).toHaveBeenCalledWith('mic-usb')
    })

    // SPEC-034 · AC-03
    it('hides the top bar recording controls on the captures list and on Discoveries', async () => {
      const { unmount } = renderAt('/captures')
      expect(await screen.findByText('Aún no hay capturas')).toBeInTheDocument()
      expect(screen.queryByTestId('topbar-capture-controls')).not.toBeInTheDocument()

      unmount()
      renderAt('/discoveries')
      expect(await screen.findByText('Aún no hay discoveries')).toBeInTheDocument()
      expect(screen.queryByTestId('topbar-capture-controls')).not.toBeInTheDocument()
    })
  })

  describe('header start button', () => {
    // SPEC-034 · AC-04
    it('renders the default "Iniciar grabación" button before the outline "Asignar empresa" when the capture has no company', async () => {
      renderAt('/captures/i-1')

      const start = await screen.findByTestId('capture-start-button')
      expect(start).toHaveTextContent('Iniciar grabación')
      expect(start).toHaveAttribute('data-variant', 'default')
      const assign = screen.getByTestId('assign-company-button')
      expect(assign).toHaveAttribute('data-variant', 'outline')
      // Primario a la izquierda del secundario (decisión asumida de la spec)
      expect(start.compareDocumentPosition(assign) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
    })

    // SPEC-034 · AC-05
    it('renders only "Iniciar grabación" in the header when the capture already has a company', async () => {
      setInterview(capture({ companyId: 'c-1', contactIds: ['ct-1'] }))
      renderAt('/captures/i-1')

      expect(await screen.findByTestId('capture-start-button')).toBeInTheDocument()
      expect(screen.queryByTestId('assign-company-button')).not.toBeInTheDocument()
    })

    // SPEC-034 · AC-06
    it('starts through the SPEC-019 consent dialog and the recording:start bridge when clicking the header button', async () => {
      const user = userEvent.setup()
      setupGrantedCapture()
      renderAt('/captures/i-1')

      // startFromHeader atraviesa el aviso «Aviso de grabación» y espera Detener
      await startFromHeader(user)

      expect(vi.mocked(mockApi.api.recording.start)).toHaveBeenCalledWith(
        'i-1',
        expect.stringMatching(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/)
      )
      expect(recorderMock.start).toHaveBeenCalledTimes(1)
    })
  })

  describe('recording states', () => {
    // SPEC-034 · AC-07
    it('hides the top bar and header controls while recording, keeping the live session inside the Grabación section', async () => {
      const user = userEvent.setup()
      setupGrantedCapture()
      renderAt('/captures/i-1')

      await startFromHeader(user)

      expect(screen.queryByTestId('topbar-capture-controls')).not.toBeInTheDocument()
      expect(screen.queryByTestId('capture-start-button')).not.toBeInTheDocument()
      // La sesión en curso vive en la sección: cronómetro, Detener, medidores
      // y el selector deshabilitado de siempre (SPEC-015)
      const section = await grabacionSection()
      expect(within(section).getByText('00:00')).toBeInTheDocument()
      expect(within(section).getByRole('button', { name: 'Detener' })).toBeInTheDocument()
      expect(within(section).getAllByRole('progressbar')).toHaveLength(2)
      expect(within(section).getByRole('combobox', { name: 'Micrófono' })).toBeDisabled()
    })

    // SPEC-034 · AC-08
    it('hides all recording controls in Grabada, keeping the summary and "Nueva grabación" inside the section', async () => {
      setInterview(RECORDED)
      renderAt('/captures/i-1')

      expect(await screen.findByText(WAV_PATH)).toBeInTheDocument()
      expect(screen.queryByTestId('topbar-capture-controls')).not.toBeInTheDocument()
      expect(screen.queryByTestId('capture-start-button')).not.toBeInTheDocument()
      // Nada que configurar en Grabada: sin selector en ninguna zona
      expect(screen.queryByRole('combobox', { name: 'Micrófono' })).not.toBeInTheDocument()
      const section = await grabacionSection()
      expect(within(section).getByText(TRANSCRIPT_PATH)).toBeInTheDocument()
      expect(within(section).getByRole('button', { name: 'Nueva grabación' })).toBeInTheDocument()
    })

    // SPEC-034 · AC-09
    it('brings the controls back to the top bar and the header after confirming "Nueva grabación"', async () => {
      const user = userEvent.setup()
      setInterview(RECORDED)
      renderAt('/captures/i-1')

      await user.click(await screen.findByRole('button', { name: 'Nueva grabación' }))
      const dialog = await screen.findByRole('alertdialog')
      expect(
        within(dialog).getByRole('heading', { name: 'Sobrescribir grabación' })
      ).toBeInTheDocument()
      await user.click(within(dialog).getByRole('button', { name: 'Sobrescribir' }))

      // Vuelta a Preparación: controles arriba (top bar + cabecera) otra vez
      const controls = await within(topBar()).findByTestId('topbar-capture-controls')
      expect(await within(controls).findAllByText('Concedido')).toHaveLength(2)
      expect(within(controls).getByRole('combobox', { name: 'Micrófono' })).toBeEnabled()
      expect(await screen.findByTestId('capture-start-button')).toBeInTheDocument()
      expect(screen.queryByText(WAV_PATH)).not.toBeInTheDocument()
    })
  })

  describe('Grabación section without duplicates', () => {
    // SPEC-034 · AC-10
    it('renders the capture Grabación section without permission badges, mic select or start button in Preparación', async () => {
      renderAt('/captures/i-1')

      // Los controles están arriba (y cargados): la sección no los duplica
      const controls = await within(topBar()).findByTestId('topbar-capture-controls')
      await within(controls).findAllByText('Concedido')
      const section = await grabacionSection()
      expect(within(section).queryByText('Concedido')).not.toBeInTheDocument()
      expect(within(section).queryByText('Audio del sistema')).not.toBeInTheDocument()
      expect(within(section).queryByRole('combobox', { name: 'Micrófono' })).not.toBeInTheDocument()
      expect(
        within(section).queryByRole('button', { name: 'Iniciar grabación' })
      ).not.toBeInTheDocument()
      // Un solo selector y un solo botón de arranque en toda la página
      expect(screen.getAllByRole('combobox', { name: 'Micrófono' })).toHaveLength(1)
      expect(screen.getAllByRole('button', { name: 'Iniciar grabación' })).toHaveLength(1)
    })

    // SPEC-034 · AC-11
    it('keeps the classic interview detail controls inside the Grabación section with no top bar controls', async () => {
      setInterview(capture({ companyId: 'c-1', title: 'Discovery con Acme' }))
      renderAt('/discoveries/d-1/companies/c-1/interviews/i-1')

      const section = await grabacionSection()
      // Los controles siguen DENTRO de la sección, como hasta ahora (SPEC-015)
      expect(await within(section).findAllByText('Concedido')).toHaveLength(2)
      expect(within(section).getByText('Audio del sistema')).toBeInTheDocument()
      expect(within(section).getByRole('combobox', { name: 'Micrófono' })).toBeEnabled()
      expect(within(section).getByRole('button', { name: 'Iniciar grabación' })).toBeInTheDocument()
      // Y la top bar no gana controles fuera de /captures/:id
      expect(screen.queryByTestId('topbar-capture-controls')).not.toBeInTheDocument()
      expect(screen.queryByTestId('capture-start-button')).not.toBeInTheDocument()
    })
  })

  describe('flow regressions', () => {
    // SPEC-034 · AC-12
    it('blocks the start from the header and shows the destructive permission Alert inside the Grabación section', async () => {
      const user = userEvent.setup()
      vi.mocked(getPermissionsStatus).mockResolvedValue({
        microphone: 'denied',
        systemAudio: 'granted'
      })
      renderAt('/captures/i-1')

      await user.click(await screen.findByTestId('capture-start-button'))
      // SPEC-019: el aviso aparece ANTES; el bloqueo se evalúa tras confirmar
      const consent = await screen.findByRole('alertdialog')
      await user.click(
        within(consent).getByRole('button', { name: 'Entendido, iniciar grabación' })
      )

      const title = await screen.findByText('Permiso de micrófono no concedido')
      const alert = title.closest('[role="alert"]')
      if (alert === null) {
        throw new Error('El error de permiso debe mostrarse dentro de un Alert')
      }
      expect(alert).toHaveTextContent(/Ajustes del Sistema → Privacidad y seguridad → Micrófono/)
      // El Alert vive en la sección «Grabación» del final, no en la top bar
      const section = await grabacionSection()
      expect(section.contains(alert)).toBe(true)
      // No arranca: sin Detener ni recorder ni bridge
      expect(screen.queryByRole('button', { name: 'Detener' })).not.toBeInTheDocument()
      expect(recorderMock.start).not.toHaveBeenCalled()
      expect(vi.mocked(mockApi.api.recording.start)).not.toHaveBeenCalled()
    })

    // SPEC-034 · AC-13
    it('auto-stops and saves when navigating away from the capture detail during a recording', async () => {
      const user = userEvent.setup()
      setupGrantedCapture()
      renderAt('/captures/i-1')
      await startFromHeader(user)

      // Navegar por el sidebar del Layout desmonta CaptureDetailContent (el
      // controller — y su cleanup de auto-guardado — vive en el ready-branch)
      const sidebar = screen.getByRole('navigation', { name: 'Navegación principal' })
      await user.click(within(sidebar).getByRole('link', { name: 'Capturas' }))
      expect(await screen.findByText('Aún no hay capturas')).toBeInTheDocument()

      // El cleanup detiene y guarda sin diálogo (la asociación ocurre en main)
      await waitFor(() => expect(vi.mocked(mockApi.api.recording.stop)).toHaveBeenCalledTimes(1))
      expect(screen.queryByRole('alertdialog')).not.toBeInTheDocument()
    })
  })
})
