/**
 * SPEC-020: Capturas — detalle de captura (/captures/:id) con la misma
 * experiencia que el detalle de entrevista (secciones reutilizadas).
 * Generated by QA Dev agent.
 *
 * Fronteras de mocking: servicios del spike (permissionsService/captureService/
 * wavRecorderService, patrón SPEC-015/016/017 — las secciones se montan
 * REALES) + bridge window.api. El comportamiento interno de cada sección está
 * garantizado por sus propias suites (SPEC-015/016/017/019): aquí se verifica
 * el contrato del detalle de captura (cabecera, orden de secciones, error
 * state y asignación de empresa reflejada sin recargar).
 */
import { render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { CaptureDetailPage } from '@/pages/CaptureDetailPage'
import { listAudioInputDevices } from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { Company, Contact, Discovery, Interview } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = vi.fn()
    stop = vi.fn()
    getLevels = vi.fn()
  }
}))

let mockApi: MockApiHandle

const DISCOVERY: Discovery = {
  id: 'd-1',
  name: 'Vertical Sanidad',
  createdAt: '2026-07-01T09:00:00.000Z',
  updatedAt: '2026-07-01T09:00:00.000Z'
}

const COMPANY: Company = {
  id: 'c-1',
  discoveryId: 'd-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const CONTACT: Contact = {
  id: 'ct-1',
  companyId: 'c-1',
  name: 'Jane Doe',
  position: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

function capture(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: null,
    contactId: null,
    templateId: null,
    title: 'Captura sin empresa',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-10T10:00:00.000Z',
    updatedAt: '2026-07-10T10:00:00.000Z',
    ...overrides
  }
}

function setInterview(value: Interview): void {
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: value })
}

function renderDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/captures/i-1']}>
        <Routes>
          <Route path="/captures/:id" element={<CaptureDetailPage />} />
          <Route path="/captures" element={<div>CAPTURES_LIST_PROBE</div>} />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  setInterview(capture())
  vi.mocked(mockApi.api.db.getDiscovery).mockResolvedValue({ ok: true, data: DISCOVERY })
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.db.getContact).mockResolvedValue({ ok: true, data: CONTACT })
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
})

describe('CaptureDetailPage', () => {
  describe('header', () => {
    // SPEC-020 · AC-14
    it('shows the "Volver" back button to /captures, the h1 title, the status badge and the muted refs row with fallbacks', async () => {
      const user = userEvent.setup()
      renderDetail()

      expect(
        await screen.findByRole('heading', { level: 1, name: 'Captura sin empresa' })
      ).toBeInTheDocument()
      expect(screen.getByText('Borrador')).toBeInTheDocument()
      // "{discovery} · {empresa | Sin empresa} · {contacto | Sin contacto} · {template | Sin template}"
      // (regex: SPEC-021 añadió el segmento de coste de IA al final de la fila)
      expect(
        screen.getByText(/Vertical Sanidad · Sin empresa · Sin contacto · Sin template/)
      ).toBeInTheDocument()
      // SPEC-021: captura sin aiUsage → "Sin datos de coste" sin errores
      expect(screen.getByText('Sin datos de coste')).toBeInTheDocument()

      await user.click(screen.getByRole('button', { name: 'Volver' }))
      expect(await screen.findByText('CAPTURES_LIST_PROBE')).toBeInTheDocument()
    })
  })

  describe('sections', () => {
    // SPEC-020 · AC-15, adaptado por SPEC-025: las mismas secciones montadas
    // tal cual tras la Grabación, pero la disposición Nota/Guión ahora es
    // condicional (NoteScriptSections) — con transcripción y sin guión ni nota
    // se apilan Guión + controles de generación de la nota; la disposición
    // completa la cubre tests/unit/markdown/NoteScriptSections.test.tsx
    it('mounts Grabación first and the SPEC-025 Nota/Guión disposition for a capture with transcript', async () => {
      setInterview(
        capture({
          wavPath: '/tmp/maurya-recordings/captura.wav',
          transcriptPath: '/tmp/maurya-recordings/captura.transcript.json',
          status: 'recorded'
        })
      )
      renderDetail()

      await screen.findByRole('heading', { level: 1, name: 'Captura sin empresa' })
      const headings = await screen.findAllByRole('heading', { level: 3 })
      const titles = headings.map((heading) => heading.textContent)
      const grabacion = titles.indexOf('Grabación')
      const guion = titles.indexOf('Guión')
      const nota = titles.indexOf('Nota')
      expect(grabacion).toBeGreaterThanOrEqual(0)
      expect(guion).toBeGreaterThan(grabacion)
      expect(nota).toBeGreaterThan(guion)
      // Las secciones reciben la captura real: la Grabación está en estado
      // "Grabada" y muestra la ruta del WAV del fixture (con wavPath ya no
      // ofrece el CTA "Iniciar grabación")
      expect(await screen.findByText('/tmp/maurya-recordings/captura.wav')).toBeInTheDocument()
    })
  })

  describe('error state', () => {
    // SPEC-020 · AC-17
    it('shows the error state with a "Volver a Capturas" link when the capture id does not exist', async () => {
      vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({
        ok: false,
        error: { kind: 'not-found', message: 'No existe entrevista con id i-1' }
      })
      const user = userEvent.setup()
      renderDetail()

      expect(await screen.findByText('No existe entrevista con id i-1')).toBeInTheDocument()
      await user.click(screen.getByRole('link', { name: 'Volver a Capturas' }))
      expect(await screen.findByText('CAPTURES_LIST_PROBE')).toBeInTheDocument()
    })
  })

  describe('company assignment', () => {
    // SPEC-020 · AC-21
    it('shows the outline "Asignar empresa" button opening the Sheet only while the capture has no company', async () => {
      const user = userEvent.setup()
      const { unmount } = renderDetail()

      await user.click(await screen.findByTestId('assign-company-button'))
      expect(await screen.findByTestId('assign-company-sheet')).toBeInTheDocument()
      expect(
        screen.getByRole('heading', { name: 'Asignar empresa y contacto' })
      ).toBeInTheDocument()

      // Con empresa asignada el botón no existe y la cabecera resuelve nombres
      unmount()
      setInterview(capture({ companyId: 'c-1', contactId: 'ct-1' }))
      renderDetail()
      await screen.findByRole('heading', { level: 1, name: 'Captura sin empresa' })
      expect(screen.queryByTestId('assign-company-button')).not.toBeInTheDocument()
      expect(
        screen.getByText(/Vertical Sanidad · Acme Corp · Jane Doe · Sin template/)
      ).toBeInTheDocument()
    })

    // SPEC-020 · AC-27
    it('assigns an existing company, toasts "Empresa asignada", closes the Sheet and refreshes the header without reloading', async () => {
      vi.mocked(mockApi.api.db.listCompanies).mockResolvedValue({ ok: true, data: [COMPANY] })
      vi.mocked(mockApi.api.db.assignInterviewCompany).mockResolvedValue({
        ok: true,
        data: {
          interview: capture({ companyId: 'c-1' }),
          company: COMPANY,
          contact: null
        }
      })
      const user = userEvent.setup()
      renderDetail()

      await user.click(await screen.findByTestId('assign-company-button'))
      const sheet = await screen.findByTestId('assign-company-sheet')
      await user.click(within(sheet).getByRole('combobox', { name: 'Empresa' }))
      await user.click(await screen.findByRole('option', { name: 'Acme Corp' }))
      await user.click(within(sheet).getByRole('button', { name: 'Asignar' }))

      await waitFor(() =>
        expect(vi.mocked(mockApi.api.db.assignInterviewCompany)).toHaveBeenCalledWith('i-1', {
          companyId: 'c-1',
          contactId: null
        })
      )
      expect((await screen.findAllByText('Empresa asignada')).length).toBeGreaterThanOrEqual(1)
      // El Sheet se cierra y la cabecera refleja la asignación sin recargar
      await waitFor(() =>
        expect(screen.queryByTestId('assign-company-sheet')).not.toBeInTheDocument()
      )
      expect(
        screen.getByText(/Vertical Sanidad · Acme Corp · Sin contacto · Sin template/)
      ).toBeInTheDocument()
      expect(screen.queryByTestId('assign-company-button')).not.toBeInTheDocument()
      // getInterview solo se llamó en la carga inicial: el refresco es local
      expect(vi.mocked(mockApi.api.db.getInterview)).toHaveBeenCalledTimes(1)
    })
  })
})
