/**
 * SPEC-032: Nombre por defecto de captura — comportamiento intacto del Dialog
 * "Editar captura" (AC-07): el Título sigue siendo requerido al editar; el
 * nombre por defecto aplica solo a la creación.
 * Generated by QA Dev agent.
 *
 * Componente aislado (frontera: prop onSubmit). Captura sin empresa: el efecto
 * de contactos no se dispara, así que no hace falta mockear window.api.
 */
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { EditCaptureDialog } from '@/components/captures/EditCaptureDialog'
import type { EditCaptureValues } from '@/hooks/useCaptures'
import type { Interview } from '@/types/domain'

const INTERVIEW: Interview = {
  id: 'i-1',
  discoveryId: 'd-1',
  companyId: null,
  contactIds: [],
  interviewGroupId: null,
  templateId: null,
  title: 'Captura con nombre',
  status: 'draft',
  scriptMarkdown: null,
  objectives: [],
  wavPath: null,
  transcriptPath: null,
  createdAt: '2026-07-10T10:00:00.000Z',
  updatedAt: '2026-07-10T10:00:00.000Z'
}

let onSubmit: ReturnType<typeof vi.fn<(values: EditCaptureValues) => Promise<boolean>>>

beforeEach(() => {
  vi.clearAllMocks()
  onSubmit = vi.fn<(values: EditCaptureValues) => Promise<boolean>>().mockResolvedValue(true)
})

describe('EditCaptureDialog', () => {
  // SPEC-032 · AC-07: la derogación del Título requerido NO alcanza a la
  // edición — vaciar el título sigue mostrando el error y no guarda nada.
  it('keeps the inline "Campo requerido" error and saves nothing when the title is emptied on edit', async () => {
    const user = userEvent.setup()
    render(
      <EditCaptureDialog
        open
        onOpenChange={vi.fn()}
        interview={INTERVIEW}
        templates={[]}
        onSubmit={onSubmit}
      />
    )

    const titleInput = screen.getByLabelText('Título')
    expect(titleInput).toHaveValue('Captura con nombre')
    await user.clear(titleInput)
    await user.click(screen.getByRole('button', { name: 'Guardar' }))

    expect(await screen.findByText('Campo requerido')).toBeInTheDocument()
    expect(titleInput).toHaveAttribute('aria-invalid', 'true')
    expect(onSubmit).not.toHaveBeenCalled()
  })
})
