/**
 * SPEC-020: Capturas — Dialog "Nueva captura" (componente aislado).
 * Generated by QA Dev agent.
 *
 * El Dialog no toca el bridge: valida inline y delega en onSubmit, así que la
 * frontera de mocking es la prop onSubmit. Necesita MemoryRouter por el link
 * "Crear discovery" del aviso sin discoveries.
 */
import { render, screen, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import { NewCaptureDialog } from '@/components/captures/NewCaptureDialog'
import type { NewCaptureValues } from '@/hooks/useCaptures'
import type { Discovery, InterviewTemplate } from '@/types/domain'

const DISCOVERY: Discovery = {
  id: 'd-1',
  name: 'Vertical Sanidad',
  createdAt: '2026-07-01T09:00:00.000Z',
  updatedAt: '2026-07-01T09:00:00.000Z'
}

const TEMPLATE: InterviewTemplate = {
  id: 'tpl-1',
  name: 'Entrevista MDR',
  phase: 'problem',
  blocks: [{ title: 'Contexto', questions: [{ text: '¿Quién lleva el regulatorio?' }] }],
  createdAt: '2026-07-04T09:00:00.000Z',
  updatedAt: '2026-07-04T09:00:00.000Z'
}

let onSubmit: ReturnType<typeof vi.fn<(values: NewCaptureValues) => Promise<boolean>>>

function renderDialog(options: { discoveries?: Discovery[] } = {}): RenderResult {
  const { discoveries = [DISCOVERY] } = options
  return render(
    <MemoryRouter>
      <NewCaptureDialog
        open
        onOpenChange={vi.fn()}
        discoveries={discoveries}
        templates={[TEMPLATE]}
        onSubmit={onSubmit}
      />
    </MemoryRouter>
  )
}

beforeEach(() => {
  vi.clearAllMocks()
  onSubmit = vi.fn<(values: NewCaptureValues) => Promise<boolean>>().mockResolvedValue(true)
})

describe('NewCaptureDialog', () => {
  // SPEC-020 · AC-09
  it('renders Título (required), Discovery (required) and Plantilla defaulting to "Sin template" with name+phase labels', async () => {
    const user = userEvent.setup()
    renderDialog()

    expect(screen.getByRole('heading', { name: 'Nueva captura' })).toBeInTheDocument()
    // Título con el placeholder "Captura dd/mm/aaaa" de la fecha local
    expect(screen.getByLabelText('Título')).toHaveAttribute(
      'placeholder',
      expect.stringMatching(/^Captura \d{2}\/\d{2}\/\d{4}$/)
    )
    // Discovery requerido, con su placeholder hasta elegir
    expect(screen.getByRole('combobox', { name: 'Discovery' })).toHaveTextContent(
      'Selecciona un discovery'
    )
    // Plantilla opcional: default "Sin template" + etiqueta nombre (fase)
    const templateSelect = screen.getByRole('combobox', { name: 'Plantilla' })
    expect(templateSelect).toHaveTextContent('Sin template')
    await user.click(templateSelect)
    expect(await screen.findByRole('option', { name: 'Sin template' })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: 'Entrevista MDR (Problema)' })).toBeInTheDocument()
  })

  // SPEC-020 · AC-10
  it('shows the inline "Campo requerido" error under Título and creates nothing when the title is empty', async () => {
    const user = userEvent.setup()
    renderDialog()

    await user.click(screen.getByRole('combobox', { name: 'Discovery' }))
    await user.click(await screen.findByRole('option', { name: 'Vertical Sanidad' }))
    await user.click(screen.getByRole('button', { name: 'Crear' }))

    expect(await screen.findByText('Campo requerido')).toBeInTheDocument()
    expect(onSubmit).not.toHaveBeenCalled()
  })

  // SPEC-020 · AC-11
  it('shows the inline "Campo requerido" error under Discovery and creates nothing when no discovery is selected', async () => {
    const user = userEvent.setup()
    renderDialog()

    await user.type(screen.getByLabelText('Título'), 'Captura de prueba')
    await user.click(screen.getByRole('button', { name: 'Crear' }))

    expect(await screen.findByText('Campo requerido')).toBeInTheDocument()
    expect(onSubmit).not.toHaveBeenCalled()
  })

  // SPEC-020 · AC-12
  it('disables the Discovery select with "No hay discoveries" and links to create one when there are zero discoveries', () => {
    renderDialog({ discoveries: [] })

    const discoverySelect = screen.getByRole('combobox', { name: 'Discovery' })
    expect(discoverySelect).toBeDisabled()
    expect(discoverySelect).toHaveTextContent('No hay discoveries')
    // Aviso con link que navega a /discoveries
    expect(screen.getByText(/No hay discoveries\./)).toBeInTheDocument()
    expect(screen.getByRole('link', { name: 'Crear discovery' })).toHaveAttribute(
      'href',
      '/discoveries'
    )
  })
})
