// @vitest-environment node
/**
 * SPEC-022: URL de conexión sin diarización (refuerzo de AC-01 en la capa
 * deepgramService) — WebSocket global stubbeado, arnés de SPEC-002.
 * Generated by QA Dev agent.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { DeepgramConnection } from '../../../src/main/deepgramService'

class FakeWebSocket {
  static readonly CONNECTING = 0
  static readonly OPEN = 1
  static readonly CLOSING = 2
  static readonly CLOSED = 3
  static last: FakeWebSocket | null = null

  readonly url: string
  readonly protocols: string[]
  binaryType = 'blob'
  readyState: number = FakeWebSocket.OPEN
  bufferedAmount = 0
  onopen: (() => void) | null = null
  onmessage: ((event: { data: unknown }) => void) | null = null
  onerror: (() => void) | null = null
  onclose: ((event: { code: number }) => void) | null = null

  constructor(url: string, protocols: string[]) {
    this.url = url
    this.protocols = protocols
    FakeWebSocket.last = this
  }

  send(): void {
    return undefined
  }

  close(): void {
    this.readyState = FakeWebSocket.CLOSED
  }
}

const CALLBACKS = {
  onOpen: vi.fn(),
  onResult: vi.fn(),
  onClose: vi.fn(),
  onError: vi.fn()
}

beforeEach(() => {
  FakeWebSocket.last = null
  vi.stubGlobal('WebSocket', FakeWebSocket)
})

afterEach(() => {
  vi.unstubAllGlobals()
})

describe('DeepgramConnection (degradación SPEC-022)', () => {
  // SPEC-022 · AC-01 (refuerzo: URL del fallback sin diarize, demás params intactos)
  it('builds the fallback URL without diarize=true keeping every other stream parameter and the subprotocol auth', () => {
    new DeepgramConnection('dg-key', CALLBACKS, { diarize: false })
    const socket = FakeWebSocket.last
    if (socket === null) {
      throw new Error('DeepgramConnection no creó el WebSocket')
    }

    expect(socket.url).not.toContain('diarize')
    // Los demás parámetros del stream quedan intactos
    expect(socket.url).toContain('encoding=linear16')
    expect(socket.url).toContain('sample_rate=16000')
    expect(socket.url).toContain('channels=2')
    expect(socket.url).toContain('multichannel=true')
    expect(socket.url).toContain('interim_results=true')
    expect(socket.url).toContain('language=es')
    // Autenticación por subprotocolo: la key nunca va en la URL
    expect(socket.protocols).toEqual(['token', 'dg-key'])
  })

  // SPEC-022 · AC-01 (refuerzo: el default sigue siendo la URL histórica exacta)
  it('keeps the historic diarized URL byte-identical when no options are passed', () => {
    new DeepgramConnection('dg-key', CALLBACKS)
    const socket = FakeWebSocket.last
    if (socket === null) {
      throw new Error('DeepgramConnection no creó el WebSocket')
    }

    expect(socket.url).toBe(
      'wss://api.deepgram.com/v1/listen?encoding=linear16&sample_rate=16000&channels=2&multichannel=true&interim_results=true&language=es&diarize=true'
    )
  })
})
