// @vitest-environment node
/**
 * SPEC-022: degradación elegante sin diarización — fallback de conexión en
 * transcriptionService (Node, arnés de SPEC-002: DeepgramConnection mockeada
 * capturando las opciones del constructor, classifyConnectionFailure
 * configurable, persistencia con fs real).
 *
 * La semántica sesión-vs-conexión (una sesión que LLEGÓ a abrir y luego cae
 * NO dispara el fallback) queda fijada por el test existente de SPEC-002
 * AC-11 (tests/unit/spike-transcription/transcriptionService.test.ts: se
 * rinde con 2 instancias) — referenciado en el map, no duplicado aquí.
 * Generated by QA Dev agent.
 */
import { mkdtempSync, readFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import type { WebContents } from 'electron'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { DeepgramCallbacks, DeepgramConnectionOptions } from '../../../src/main/deepgramService'
import {
  persistTranscript,
  resetTranscription,
  startTranscription
} from '../../../src/main/transcriptionService'
import type { TranscriptionStatusEvent } from '../../../src/renderer/src/types/audio'

interface FakeConnection {
  apiKey: string
  callbacks: DeepgramCallbacks
  options: DeepgramConnectionOptions | undefined
  opened: boolean
  isOpen: boolean
  sendAudio: ReturnType<typeof vi.fn>
  sendKeepAlive: ReturnType<typeof vi.fn>
  closeStream: ReturnType<typeof vi.fn>
  terminate: ReturnType<typeof vi.fn>
}

const harness = vi.hoisted(() => ({
  instances: [] as unknown[],
  classify: vi.fn<() => Promise<'auth' | 'other'>>(() => Promise.resolve('other'))
}))

vi.mock('../../../src/main/deepgramService', () => ({
  DeepgramConnection: class {
    apiKey: string
    callbacks: DeepgramCallbacks
    options: DeepgramConnectionOptions | undefined
    opened = false
    isOpen = false
    sendAudio = vi.fn(() => true)
    sendKeepAlive = vi.fn()
    closeStream = vi.fn()
    terminate = vi.fn()

    constructor(
      apiKey: string,
      callbacks: DeepgramCallbacks,
      options?: DeepgramConnectionOptions
    ) {
      this.apiKey = apiKey
      this.callbacks = callbacks
      this.options = options
      harness.instances.push(this)
    }
  },
  classifyConnectionFailure: harness.classify
}))

function getConnection(index: number): FakeConnection {
  const connection = harness.instances[index] as FakeConnection | undefined
  if (connection === undefined) {
    throw new Error(`No se creó la conexión con Deepgram nº ${index + 1}`)
  }
  return connection
}

function createSender(): { sender: WebContents; send: ReturnType<typeof vi.fn> } {
  const send = vi.fn()
  const senderLike = {
    isDestroyed: (): boolean => false,
    send
  }
  return { sender: senderLike as unknown as WebContents, send }
}

function openConnection(connection: FakeConnection): void {
  connection.opened = true
  connection.isOpen = true
  connection.callbacks.onOpen()
}

function statusEvents(send: ReturnType<typeof vi.fn>): TranscriptionStatusEvent[] {
  return send.mock.calls
    .filter((call) => call[0] === 'transcription:status')
    .map((call) => call[1] as TranscriptionStatusEvent)
}

/**
 * Agota los reintentos con diarización sin que ninguna conexión abra:
 * conexión inicial + 1 reintento (MAX_RETRIES) caen sin abrir → la 3ª
 * instancia es el intento único sin diarización (SPEC-022).
 */
async function exhaustDiarizedRetries(): Promise<void> {
  getConnection(0).callbacks.onClose(1006)
  await vi.waitFor(() => expect(harness.instances).toHaveLength(2))
  getConnection(1).callbacks.onClose(1006)
  await vi.waitFor(() => expect(harness.instances).toHaveLength(3))
}

beforeEach(() => {
  vi.clearAllMocks()
  harness.instances.length = 0
  harness.classify.mockImplementation(() => Promise.resolve('other' as const))
  resetTranscription()
  process.env['DEEPGRAM_API_KEY'] = 'dg-test-key'
})

afterEach(() => {
  resetTranscription()
  delete process.env['DEEPGRAM_API_KEY']
})

describe('transcriptionService (degradación SPEC-022)', () => {
  // SPEC-022 · AC-01
  it('attempts exactly one extra connection without diarization after exhausting the never-opened retries', async () => {
    const { sender, send } = createSender()
    startTranscription(sender)

    // Las conexiones normales van CON diarización
    expect(getConnection(0).options).toEqual({ diarize: true })
    await exhaustDiarizedRetries()

    // El reintento intermedio conservó su status actual (SPEC-002 intacto)
    expect(send).toHaveBeenCalledWith('transcription:status', {
      status: 'disconnected',
      error: {
        kind: 'deepgram-connection',
        message: expect.stringContaining('Reintentando la conexión')
      }
    })
    // El reintento normal (2ª conexión) siguió pidiendo diarización
    expect(getConnection(1).options).toEqual({ diarize: true })
    // La 3ª conexión es el fallback SIN diarización, con la misma key
    const fallback = getConnection(2)
    expect(fallback.options).toEqual({ diarize: false })
    expect(fallback.apiKey).toBe('dg-test-key')
    // Intento silencioso: la rendición aún NO se ha emitido
    const surrendered = statusEvents(send).some(
      (event) => event.error?.message.includes('No se pudo restablecer') === true
    )
    expect(surrendered).toBe(false)
  })

  // SPEC-022 · AC-02
  it('continues degraded when the fallback opens: active status carries degraded true and lines flow with speaker null', async () => {
    const { sender, send } = createSender()
    startTranscription(sender)
    await exhaustDiarizedRetries()

    openConnection(getConnection(2))

    // El estado emitido al renderer marca el modo degradado (shape exacto)
    expect(send).toHaveBeenCalledWith('transcription:status', {
      status: 'active',
      degraded: true
    })

    // Los resultados siguen fluyendo; sin diarización el parser ya entrega null
    getConnection(2).callbacks.onResult({
      channelIndex: 0,
      transcript: 'seguimos transcribiendo sin hablantes',
      isFinal: true,
      startSeconds: 0,
      durationSeconds: 1,
      speaker: null
    })
    expect(send).toHaveBeenCalledWith(
      'transcription:result',
      expect.objectContaining({
        channel: 'mic',
        text: 'seguimos transcribiendo sin hablantes',
        isFinal: true,
        speaker: null
      })
    )
  })

  // SPEC-022 · AC-03
  it('gives up with the current literal message when the no-diarization attempt also fails', async () => {
    const { sender, send } = createSender()
    startTranscription(sender)
    await exhaustDiarizedRetries()

    // El fallback tampoco abre: cae → rendición actual, sin más intentos
    getConnection(2).callbacks.onClose(1006)
    await vi.waitFor(() => {
      expect(send).toHaveBeenCalledWith('transcription:status', {
        status: 'disconnected',
        error: {
          kind: 'deepgram-connection',
          message:
            'No se pudo restablecer la conexión con Deepgram (código 1006). La captura continúa sin transcripción; se conservan las líneas ya recibidas.'
        },
        degraded: true
      })
    })
    expect(harness.instances).toHaveLength(3)
  })

  // SPEC-022 · AC-04
  it('does not try the fallback on an auth-classified failure, keeping the current auth message', async () => {
    harness.classify.mockImplementation(() => Promise.resolve('auth' as const))
    const { sender, send } = createSender()
    startTranscription(sender)

    getConnection(0).callbacks.onClose(1006)
    await vi.waitFor(() => {
      expect(send).toHaveBeenCalledWith('transcription:status', {
        status: 'disconnected',
        error: {
          kind: 'deepgram-auth',
          message: 'No se pudo conectar con Deepgram: clave inválida'
        }
      })
    })

    // Cero conexiones extra: ni reintento ni fallback (una key inválida no se
    // arregla quitando la diarización)
    expect(harness.instances).toHaveLength(1)
    expect(statusEvents(send).some((event) => event.degraded === true)).toBe(false)
  })

  // SPEC-022 · AC-05
  it('persists the transcript with the current shape (speaker null lines) when a degraded session stops', async () => {
    const { sender } = createSender()
    startTranscription(sender)
    await exhaustDiarizedRetries()
    openConnection(getConnection(2))
    getConnection(2).callbacks.onResult({
      channelIndex: 1,
      transcript: 'línea degradada del sistema',
      isFinal: true,
      startSeconds: 1,
      durationSeconds: 1,
      speaker: null
    })

    const dir = mkdtempSync(join(tmpdir(), 'maurya-degraded-transcript-'))
    const { transcriptPath, latency } = persistTranscript(join(dir, 'degradada.wav'))

    expect(latency).not.toBeNull()
    if (transcriptPath === null) {
      throw new Error('persistTranscript devolvió null con líneas finales recibidas')
    }
    const persisted = JSON.parse(readFileSync(transcriptPath, 'utf8')) as Record<string, unknown>
    // Forma ACTUAL del archivo: sin campos nuevos por el modo degradado
    expect(Object.keys(persisted)).toEqual(['lines', 'latency', 'assistant', 'consent'])
    const lines = persisted.lines as Array<{ channel: string; text: string; speaker: unknown }>
    expect(lines).toHaveLength(1)
    expect(lines[0].channel).toBe('system')
    expect(lines[0].text).toBe('línea degradada del sistema')
    expect(lines[0].speaker).toBeNull()
  })

  // SPEC-022 · AC-08 (main: el shape del evento de las sesiones normales no cambia)
  it('emits the exact current event shape without any degraded field during a normal session', () => {
    const { sender, send } = createSender()
    startTranscription(sender)
    openConnection(getConnection(0))

    expect(send).toHaveBeenCalledWith('transcription:status', { status: 'connecting' })
    expect(send).toHaveBeenCalledWith('transcription:status', { status: 'active' })
    // Ningún evento de una sesión normal lleva la marca (ni siquiera a false)
    for (const event of statusEvents(send)) {
      expect('degraded' in event).toBe(false)
    }
  })
})
