// @vitest-environment node
/**
 * SPEC-036: ajustes del asistente en vivo — capa de persistencia (singleton
 * assistantSettings con normalización defensiva al default 3 y validación
 * entero 1–5). Store JSON REAL en directorio temporal (patrón persistence,
 * espejo de repository.aiCost.test.ts).
 * Generated by QA Dev agent.
 */
import { mkdtempSync, readFileSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { DbOperationError } from '../../../src/main/db/errors'
import { getAssistantSettings, setAssistantSettings } from '../../../src/main/db/repository'
import { initStore, type DbData } from '../../../src/main/db/store'

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  }
}))

let baseDir = ''
let dbPath = ''

function readDbFile(): DbData & { assistantSettings?: unknown } {
  return JSON.parse(readFileSync(dbPath, 'utf-8')) as DbData & { assistantSettings?: unknown }
}

beforeEach(() => {
  baseDir = mkdtempSync(join(tmpdir(), 'maurya-assistant-settings-db-'))
  dbPath = join(baseDir, 'db.json')
  initStore(baseDir)
})

describe('repository (ajustes del asistente SPEC-036)', () => {
  describe('assistantSettings', () => {
    // SPEC-036 · AC-16 (main: persistencia del tamaño) + AC-15 (default 3 sin dato)
    it('persists the queueSize singleton and reads it back, defaulting to 3 without data', () => {
      // Sin campo persistido → default 3
      expect(getAssistantSettings()).toEqual({ queueSize: 3 })

      expect(setAssistantSettings({ queueSize: 5 })).toEqual({ queueSize: 5 })
      expect(getAssistantSettings()).toEqual({ queueSize: 5 })
      expect(readDbFile().assistantSettings).toEqual({ queueSize: 5 })

      expect(setAssistantSettings({ queueSize: 1 })).toEqual({ queueSize: 1 })
      expect(getAssistantSettings()).toEqual({ queueSize: 1 })
    })

    // SPEC-036 · refuerzo del contrato (entero 1–5): validación sin persistir
    it('rejects non-integer or out-of-range sizes with a validation error persisting nothing', () => {
      for (const invalid of [0, 6, 2.5, Number.NaN]) {
        let caught: unknown = null
        try {
          setAssistantSettings({ queueSize: invalid })
        } catch (error) {
          caught = error
        }
        expect(caught).toBeInstanceOf(DbOperationError)
        expect((caught as DbOperationError).kind).toBe('validation')
        expect((caught as DbOperationError).message).toBe(
          'El tamaño de la cola debe ser un entero entre 1 y 5'
        )
      }
      expect(readDbFile().assistantSettings).toBeUndefined()
    })

    // SPEC-036 · AC-18 (ajuste corrupto o ilegible → default 3 sin crashear)
    it('normalizes a corrupt or unreadable persisted setting to the default 3 without crashing', () => {
      const base = readDbFile()
      for (const corrupt of [
        'garbage',
        { queueSize: 'muchas' },
        { queueSize: 0 },
        { queueSize: 9 },
        42
      ]) {
        writeFileSync(dbPath, JSON.stringify({ ...base, assistantSettings: corrupt }))
        expect(() => initStore(baseDir)).not.toThrow()
        expect(getAssistantSettings()).toEqual({ queueSize: 3 })
      }
    })
  })
})
