// @vitest-environment node
/**
 * SPEC-020: Capturas — capa de persistencia (migración v1, invariantes de
 * integridad, listado global y asignación compuesta atómica), adaptada a v3
 * por SPEC-043: empresas globales, contactIds y encadenado v1→v2→v3.
 * Generated by QA Dev agent.
 *
 * Store JSON REAL en directorio temporal (initStore(baseDir) inyectable,
 * patrón tests/unit/persistence/repository.test.ts). Electron mockeado con un
 * guard que lanza si algo usara app.getPath.
 */
import { mkdtempSync, readFileSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { DbOperationError } from '../../../src/main/db/errors'
import {
  assignInterviewCompany,
  createCompany,
  createContact,
  createDiscovery,
  createInterview,
  createInterviewTemplate,
  createNote,
  deleteDiscovery,
  getInterview,
  getNoteByInterview,
  listAllInterviews,
  listInterviews,
  updateInterview
} from '../../../src/main/db/repository'
import { initStore, type DbData } from '../../../src/main/db/store'
import type { DbErrorKind } from '../../../src/renderer/src/types/domain'

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  }
}))

let baseDir = ''
let dbPath = ''

function readDbFile(): DbData {
  return JSON.parse(readFileSync(dbPath, 'utf-8')) as DbData
}

/** Captura el error tipado de una operación que debe fallar. */
function expectDbError(fn: () => unknown, kind: DbErrorKind): DbOperationError {
  let caught: unknown = null
  try {
    fn()
  } catch (error) {
    caught = error
  }
  expect(caught).toBeInstanceOf(DbOperationError)
  const dbError = caught as DbOperationError
  expect(dbError.kind).toBe(kind)
  return dbError
}

beforeEach(() => {
  baseDir = mkdtempSync(join(tmpdir(), 'maurya-captures-db-'))
  dbPath = join(baseDir, 'db.json')
  initStore(baseDir)
})

describe('repository (SPEC-020 capturas)', () => {
  describe('v1 migration', () => {
    // SPEC-020 · Notas técnicas (migración al cargar el store: backfill de
    // discoveryId desde la empresa; entrevista con empresa irresoluble se
    // elimina junto con su nota), encadenada por SPEC-043 hasta v3
    it('backfills discoveryId from each interview company, drops interviews with unresolvable company along with their notes, and persists a v3 store', () => {
      // db.json v1 escrito a mano: las entrevistas v1 no tienen discoveryId
      const now = '2026-07-01T09:00:00.000Z'
      const v1 = {
        schemaVersion: 1,
        discoveries: [{ id: 'd-1', name: 'Vertical Sanidad', createdAt: now, updatedAt: now }],
        companies: [
          {
            id: 'c-1',
            discoveryId: 'd-1',
            name: 'Acme Corp',
            website: null,
            linkedinUrl: null,
            createdAt: now,
            updatedAt: now
          }
        ],
        contacts: [],
        interviewTemplates: [],
        interviews: [
          {
            id: 'i-valid',
            companyId: 'c-1',
            contactId: null,
            templateId: null,
            title: 'Entrevista válida',
            status: 'draft',
            scriptMarkdown: null,
            objectives: [],
            wavPath: null,
            transcriptPath: null,
            createdAt: now,
            updatedAt: now
          },
          {
            id: 'i-orphan',
            companyId: 'c-ghost',
            contactId: null,
            templateId: null,
            title: 'Entrevista huérfana',
            status: 'draft',
            scriptMarkdown: null,
            objectives: [],
            wavPath: null,
            transcriptPath: null,
            createdAt: now,
            updatedAt: now
          }
        ],
        noteTemplates: [],
        notes: [
          {
            id: 'n-valid',
            interviewId: 'i-valid',
            contentMarkdown: '# Nota válida',
            createdAt: now,
            updatedAt: now
          },
          {
            id: 'n-orphan',
            interviewId: 'i-orphan',
            contentMarkdown: '# Nota huérfana',
            createdAt: now,
            updatedAt: now
          }
        ]
      }
      writeFileSync(dbPath, JSON.stringify(v1))

      initStore(baseDir)

      // Backfill: la entrevista válida gana el discovery de su empresa
      const migrated = getInterview('i-valid')
      expect(migrated.discoveryId).toBe('d-1')
      expect(migrated.companyId).toBe('c-1')
      // SPEC-043: el contactId null v1 se traduce a contactIds vacío
      expect(migrated.contactIds).toEqual([])
      // La huérfana desaparece con su nota; la nota válida sobrevive
      expectDbError(() => getInterview('i-orphan'), 'not-found')
      expect(getNoteByInterview('i-valid')?.id).toBe('n-valid')
      expect(getNoteByInterview('i-orphan')).toBeNull()
      // SPEC-043: v1 encadena v1→v2→v3 y se persiste atómica como v3
      const persisted = readDbFile()
      expect(persisted.schemaVersion).toBe(3)
      expect(persisted.interviews).toHaveLength(1)
      expect(persisted.notes).toHaveLength(1)
    })
  })

  describe('createInterview capture-first', () => {
    // SPEC-020 · AC-13 (main: discoveryId elegido, companyId null y — SPEC-043 —
    // contactIds vacío), draft
    it('creates a capture with the chosen discoveryId, null companyId, empty contactIds and draft status', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })

      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      expect(capture.discoveryId).toBe(discovery.id)
      expect(capture.companyId).toBeNull()
      expect(capture.contactIds).toEqual([])
      expect(capture.status).toBe('draft')
      expect(readDbFile().interviews[0].companyId).toBeNull()
    })

    // SPEC-020 · Notas técnicas (invariantes de contacto), adaptado por
    // SPEC-043: la invariante «empresa ∈ discovery» queda DEROGADA (las
    // empresas son globales y la suite de SPEC-043 verifica la aceptación);
    // siguen vigentes «contacto exige empresa» y «contacto ∈ empresa», ahora
    // sobre contactIds.
    it('rejects with a reference error a contact without company and a contact of another company, persisting nothing', () => {
      const discoveryA = createDiscovery({ name: 'Discovery A' })
      const companyB = createCompany({ name: 'Globex' })
      const contactB = createContact({ companyId: companyB.id, name: 'John Smith' })
      const companyA = createCompany({ name: 'Acme Corp' })

      // Contacto sin empresa
      expectDbError(
        () =>
          createInterview({
            discoveryId: discoveryA.id,
            contactIds: [contactB.id],
            title: 'Mala'
          }),
        'reference'
      )
      // Contacto de OTRA empresa
      expectDbError(
        () =>
          createInterview({
            discoveryId: discoveryA.id,
            companyId: companyA.id,
            contactIds: [contactB.id],
            title: 'Mala'
          }),
        'reference'
      )
      expect(readDbFile().interviews).toEqual([])
    })

    // SPEC-020 · Notas técnicas (updateInterview endurecido: contacto exige
    // empresa), adaptado por SPEC-043 a contactIds
    it('rejects updating a companyless capture with contactIds via updateInterview', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      expectDbError(() => updateInterview(capture.id, { contactIds: [contact.id] }), 'reference')
      expect(getInterview(capture.id).contactIds).toEqual([])
    })
  })

  describe('deleteDiscovery cascade', () => {
    // SPEC-020 · AC-33, adaptado por SPEC-043: la cascada sigue llevándose las
    // capturas del discovery con sus notas, pero las empresas (globales)
    // sobreviven
    it('deletes companyless captures and their notes in cascade when their discovery is deleted', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      createInterview({ discoveryId: discovery.id, companyId: company.id, title: 'De empresa' })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })
      createNote({ interviewId: capture.id, contentMarkdown: '# Nota de la captura' })
      // Otro discovery con su captura: NO debe caer en la cascada
      const otherDiscovery = createDiscovery({ name: 'Otro discovery' })
      const survivor = createInterview({ discoveryId: otherDiscovery.id, title: 'Superviviente' })

      deleteDiscovery(discovery.id)

      const persisted = readDbFile()
      expect(persisted.interviews.map((interview) => interview.id)).toEqual([survivor.id])
      expect(persisted.notes).toEqual([])
      // SPEC-043: la empresa es global y sobrevive a la cascada del discovery
      expect(persisted.companies.map((company) => company.name)).toEqual(['Acme Corp'])
    })
  })

  describe('listAllInterviews', () => {
    // SPEC-020 · AC-03 (main: listado global con contexto resuelto, updatedAt desc)
    it('returns every interview with resolved names (null for missing refs) ordered by updatedAt descending', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })
      const template = createInterviewTemplate({ name: 'Entrevista MDR' })
      const withCompany = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [contact.id],
        templateId: template.id,
        title: 'Entrevista con Acme'
      })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })
      // touched() garantiza updatedAt estrictamente posterior: la editada sube
      updateInterview(withCompany.id, { title: 'Entrevista con Acme (editada)' })

      const items = listAllInterviews()

      expect(items).toHaveLength(2)
      // Orden updatedAt desc: la editada primero
      expect(items[0].interview.id).toBe(withCompany.id)
      expect(items[0].discoveryName).toBe('Vertical Sanidad')
      expect(items[0].companyName).toBe('Acme Corp')
      // SPEC-043: nombres de TODOS los contactos en el orden de contactIds
      expect(items[0].contactNames).toEqual(['Jane Doe'])
      expect(items[0].templateName).toBe('Entrevista MDR')
      // La captura sin empresa viaja con sus referencias en null
      expect(items[1].interview.id).toBe(capture.id)
      expect(items[1].companyName).toBeNull()
      expect(items[1].contactNames).toEqual([])
      expect(items[1].templateName).toBeNull()
    })
  })

  describe('assignInterviewCompany', () => {
    // SPEC-020 · AC-27 (main) + AC-29 (main: la captura pasa a listar bajo la empresa)
    it('assigns an existing company and contact updating the interview, which then lists under that company', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      const result = assignInterviewCompany(capture.id, {
        companyId: company.id,
        contactId: contact.id
      })

      expect(result.interview.companyId).toBe(company.id)
      // SPEC-043: la asignación persiste contactIds = [contacto]
      expect(result.interview.contactIds).toEqual([contact.id])
      expect(result.company.id).toBe(company.id)
      expect(result.contact?.id).toBe(contact.id)
      expect(result.interview.updatedAt > capture.updatedAt).toBe(true)
      // AC-29: la captura aparece entre las entrevistas de esa empresa
      expect(listInterviews(company.id).map((interview) => interview.id)).toContain(capture.id)
      expect(readDbFile().interviews[0].companyId).toBe(company.id)
    })

    // SPEC-020 · AC-28 (main: crear empresa y/o contacto y asignar en UNA
    // operación), adaptado por SPEC-043: la empresa inline nace GLOBAL
    it('creates the inline company as a global company and the inline contact in that company, assigning both', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      const result = assignInterviewCompany(capture.id, {
        newCompany: { name: 'Globex', website: 'https://globex.example' },
        newContact: { name: 'John Smith', position: 'CEO' }
      })

      // SPEC-043: la empresa nueva nace GLOBAL (sin discovery)
      expect(result.company).not.toHaveProperty('discoveryId')
      expect(result.company.name).toBe('Globex')
      expect(result.company.website).toBe('https://globex.example')
      // El contacto nuevo nace en esa empresa
      expect(result.contact?.companyId).toBe(result.company.id)
      expect(result.contact?.position).toBe('CEO')
      expect(result.interview.companyId).toBe(result.company.id)
      expect(result.interview.contactIds).toEqual(
        result.contact !== null ? [result.contact.id] : []
      )
      // Todo persistido en la misma operación
      const persisted = readDbFile()
      expect(persisted.companies.map((company) => company.name)).toContain('Globex')
      expect(persisted.contacts.map((contact) => contact.name)).toContain('John Smith')
    })

    // SPEC-020 · AC-28/AC-30 (main: si algo falla, CERO escrituras — sin estado a medias)
    it('rejects invalid assignments atomically leaving the data file byte-identical', () => {
      const discoveryA = createDiscovery({ name: 'Discovery A' })
      const companyB = createCompany({ name: 'Globex' })
      const companyA = createCompany({ name: 'Acme Corp' })
      const contactB = createContact({ companyId: companyB.id, name: 'John Smith' })
      const capture = createInterview({ discoveryId: discoveryA.id, title: 'Captura suelta' })
      const before = readFileSync(dbPath, 'utf-8')

      // Empresa nueva con nombre vacío (AC-26 en main)
      expectDbError(
        () => assignInterviewCompany(capture.id, { newCompany: { name: '   ' } }),
        'validation'
      )
      // Empresa inexistente (SPEC-043 deroga «empresa de otro discovery»: una
      // empresa existente de cualquier discovery ahora se ACEPTA — verificado
      // en la suite de SPEC-043)
      expectDbError(
        () => assignInterviewCompany(capture.id, { companyId: 'c-inexistente' }),
        'not-found'
      )
      // Contacto de otra empresa
      expectDbError(
        () =>
          assignInterviewCompany(capture.id, { companyId: companyA.id, contactId: contactB.id }),
        'reference'
      )
      // Ni empresa existente ni nueva (input malformado)
      expectDbError(() => assignInterviewCompany(capture.id, {}), 'validation')

      // Sin estado a medias: el archivo no cambió ni un byte
      expect(readFileSync(dbPath, 'utf-8')).toBe(before)
      expect(getInterview(capture.id).companyId).toBeNull()
    })
  })
})
