// @vitest-environment node
/**
 * SPEC-058: marcas del banner de onboarding en el repositorio (store REAL
 * sobre directorio temporal, patrón SPEC-006/025). confirmInterviewObjectives
 * y hideInterviewOnboarding son mutaciones dedicadas main-only: fijan su
 * timestamp ISO y persisten; el patch genérico de updateInterview NUNCA las
 * escribe (patrón aiUsage/objectiveResults), y — a diferencia de
 * objectiveResults — editar `objectives` NO descarta objectivesConfirmedAt
 * (invariante explícita de la spec: el banner guía, no bloquea).
 * Generated by QA Dev agent.
 */
import { mkdtempSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import * as repository from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'
import type { Interview, UpdateInterviewPatch } from '../../../src/renderer/src/types/domain'

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

function seedInterview(): Interview {
  const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
  return repository.createInterview({
    discoveryId: discovery.id,
    title: 'Discovery con Acme'
  })
}

beforeEach(() => {
  initStore(mkdtempSync(join(tmpdir(), 'maurya-repo-onboarding-')))
})

describe('repository onboarding marks', () => {
  // SPEC-058 · AC-18 (persistencia de la confirmación)
  it('confirmInterviewObjectives sets an ISO timestamp, persists it and does not bump updatedAt', () => {
    const created = seedInterview()
    expect(created.objectivesConfirmedAt ?? null).toBeNull()

    const confirmed = repository.confirmInterviewObjectives(created.id)
    expect(typeof confirmed.objectivesConfirmedAt).toBe('string')
    expect(Number.isNaN(Date.parse(confirmed.objectivesConfirmedAt ?? ''))).toBe(false)
    // Es una marca de guiado, no una edición: no reordena el listado
    expect(confirmed.updatedAt).toBe(created.updatedAt)
    expect(repository.getInterview(created.id).objectivesConfirmedAt).toBe(
      confirmed.objectivesConfirmedAt
    )
  })

  // SPEC-058 · AC-24 (persistencia del ocultado)
  it('hideInterviewOnboarding sets an ISO timestamp and persists it', () => {
    const created = seedInterview()
    expect(created.onboardingHiddenAt ?? null).toBeNull()

    const hidden = repository.hideInterviewOnboarding(created.id)
    expect(typeof hidden.onboardingHiddenAt).toBe('string')
    expect(Number.isNaN(Date.parse(hidden.onboardingHiddenAt ?? ''))).toBe(false)
    expect(repository.getInterview(created.id).onboardingHiddenAt).toBe(hidden.onboardingHiddenAt)
  })

  // SPEC-058 · AC-26 (el fallo del canal nace aquí: id inexistente → error)
  it('both marks throw for a missing interview and write nothing', () => {
    expect(() => repository.confirmInterviewObjectives('missing')).toThrowError(/entrevista/)
    expect(() => repository.hideInterviewOnboarding('missing')).toThrowError(/entrevista/)
  })

  // SPEC-058 · Notas técnicas: NO escribibles por el patch genérico
  it('updateInterview cannot write the onboarding marks through the generic patch', () => {
    const created = seedInterview()
    const malicious = {
      title: 'Título nuevo',
      objectivesConfirmedAt: '2020-01-01T00:00:00.000Z',
      onboardingHiddenAt: '2020-01-01T00:00:00.000Z'
    } as UpdateInterviewPatch

    const updated = repository.updateInterview(created.id, malicious)
    expect(updated.title).toBe('Título nuevo')
    expect(updated.objectivesConfirmedAt ?? null).toBeNull()
    expect(updated.onboardingHiddenAt ?? null).toBeNull()
  })

  // SPEC-058 · Notas técnicas: editar objectives NO descarta la confirmación
  // (a diferencia de objectiveResults/objectiveOverrides, SPEC-025/028)
  it('editing the objectives keeps objectivesConfirmedAt', () => {
    const created = seedInterview()
    repository.updateInterview(created.id, {
      scriptMarkdown: '# Guión',
      objectives: ['Objetivo cero'],
      status: 'prepared'
    })
    const confirmed = repository.confirmInterviewObjectives(created.id)

    const edited = repository.updateInterview(created.id, {
      objectives: ['Objetivo cero', 'Objetivo nuevo']
    })
    expect(edited.objectivesConfirmedAt).toBe(confirmed.objectivesConfirmedAt)
  })
})
