// @vitest-environment node
/**
 * SPEC-043: Modelo de datos v3 — empresas globales, objetivos del discovery,
 * entrevistas con N contactos y grupo opcional, asignación diferida v3 y
 * cascadas v3 (empresa → SET NULL, discovery → sin tocar empresas/contactos).
 * Generated by QA Dev agent.
 *
 * Store JSON REAL en directorio temporal (initStore(baseDir) inyectable,
 * patrón tests/unit/persistence/repository.test.ts). Electron mockeado con un
 * guard que lanza si algo usara app.getPath.
 */
import { mkdtempSync, readFileSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { DbOperationError } from '../../../src/main/db/errors'
import {
  assignInterviewCompany,
  createCompany,
  createContact,
  createDiscovery,
  createInterview,
  createInterviewGroup,
  createNote,
  deleteCompany,
  deleteContact,
  deleteDiscovery,
  getContact,
  getDiscovery,
  getInterview,
  getNoteByInterview,
  listAllInterviews,
  listCompanies,
  listContacts,
  updateDiscovery,
  updateInterview
} from '../../../src/main/db/repository'
import { initStore, type DbData } from '../../../src/main/db/store'
import type { DbErrorKind } from '../../../src/renderer/src/types/domain'

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  }
}))

let baseDir = ''
let dbPath = ''

function readDbFile(): DbData {
  return JSON.parse(readFileSync(dbPath, 'utf-8')) as DbData
}

/** Captura el error tipado de una operación que debe fallar. */
function expectDbError(fn: () => unknown, kind: DbErrorKind): DbOperationError {
  let caught: unknown = null
  try {
    fn()
  } catch (error) {
    caught = error
  }
  expect(caught).toBeInstanceOf(DbOperationError)
  const dbError = caught as DbOperationError
  expect(dbError.kind).toBe(kind)
  return dbError
}

beforeEach(() => {
  baseDir = mkdtempSync(join(tmpdir(), 'maurya-v3-db-'))
  dbPath = join(baseDir, 'db.json')
  initStore(baseDir)
})

describe('repository (SPEC-043 modelo v3)', () => {
  describe('global companies', () => {
    // SPEC-043 · AC-01
    it('creates a company without a discovery persisting no discoveryId and website/linkedinUrl/context per input (absent to null)', () => {
      const full = createCompany({
        name: 'Acme Corp',
        website: 'https://acme.example',
        linkedinUrl: 'https://linkedin.com/company/acme',
        context: 'Fabricante de dispositivos médicos'
      })
      const minimal = createCompany({ name: 'Globex' })

      expect(full.website).toBe('https://acme.example')
      expect(full.linkedinUrl).toBe('https://linkedin.com/company/acme')
      expect(full.context).toBe('Fabricante de dispositivos médicos')
      expect(minimal.website).toBeNull()
      expect(minimal.linkedinUrl).toBeNull()
      expect(minimal.context).toBeNull()
      // Sin campo discoveryId, tampoco en el JSON persistido
      const persisted = readDbFile().companies
      expect(persisted).toHaveLength(2)
      for (const company of persisted) {
        expect(company).not.toHaveProperty('discoveryId')
      }
    })

    // SPEC-043 · AC-02
    it('lists every company in the system regardless of which discoveries use them', () => {
      const companyA = createCompany({ name: 'Acme Corp' })
      const companyB = createCompany({ name: 'Globex' })
      // Empresas usadas por entrevistas de discoveries distintos
      const discoveryA = createDiscovery({ name: 'Discovery A' })
      const discoveryB = createDiscovery({ name: 'Discovery B' })
      createInterview({ discoveryId: discoveryA.id, companyId: companyA.id, title: 'En A' })
      createInterview({ discoveryId: discoveryB.id, companyId: companyB.id, title: 'En B' })

      // El listado ya no se filtra por discovery: TODAS las del sistema
      expect(listCompanies()).toEqual([companyA, companyB])
    })

    // SPEC-043 · AC-03
    it('rejects a company with empty or whitespace-only name with a validation error without persisting anything', () => {
      expectDbError(() => createCompany({ name: '' }), 'validation')
      expectDbError(() => createCompany({ name: '   ' }), 'validation')
      expect(readDbFile().companies).toEqual([])
    })

    // SPEC-043 · AC-04
    it('keeps companies and their contacts alive when a discovery whose interviews used them is deleted', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })
      const interview = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [contact.id],
        title: 'Entrevista con Acme'
      })
      createNote({ interviewId: interview.id, contentMarkdown: '# Notas' })

      deleteDiscovery(discovery.id)

      const persisted = readDbFile()
      // Solo caen las entrevistas del discovery y sus notas
      expect(persisted.interviews).toEqual([])
      expect(persisted.notes).toEqual([])
      // Las empresas y sus contactos SOBREVIVEN
      expect(persisted.companies).toEqual([company])
      expect(persisted.contacts).toEqual([contact])
    })
  })

  describe('company deletion (SET NULL hacia entrevistas)', () => {
    // SPEC-043 · AC-05
    it('deletes a company cascading its contacts while each interview survives with null companyId, empty contactIds and its data and note intact', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })
      const otherCompany = createCompany({ name: 'Globex' })
      const otherContact = createContact({ companyId: otherCompany.id, name: 'John Smith' })
      const interview = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [contact.id],
        title: 'Entrevista con Acme'
      })
      updateInterview(interview.id, {
        scriptMarkdown: '# Guión adaptado',
        objectives: ['Objetivo uno'],
        wavPath: '/tmp/maurya-recordings/acme.wav',
        transcriptPath: '/tmp/maurya-recordings/acme.transcript.json'
      })
      const note = createNote({ interviewId: interview.id, contentMarkdown: '# Notas' })
      const untouched = createInterview({
        discoveryId: discovery.id,
        companyId: otherCompany.id,
        contactIds: [otherContact.id],
        title: 'Entrevista con Globex'
      })

      deleteCompany(company.id)

      // Contactos de la empresa en cascada; la entrevista sobrevive en SET NULL
      expectDbError(() => getContact(contact.id), 'not-found')
      const survivor = getInterview(interview.id)
      expect(survivor.companyId).toBeNull()
      expect(survivor.contactIds).toEqual([])
      // Conservando guión, objetivos, WAV, transcript y su nota
      expect(survivor.scriptMarkdown).toBe('# Guión adaptado')
      expect(survivor.objectives).toEqual(['Objetivo uno'])
      expect(survivor.wavPath).toBe('/tmp/maurya-recordings/acme.wav')
      expect(survivor.transcriptPath).toBe('/tmp/maurya-recordings/acme.transcript.json')
      expect(getNoteByInterview(interview.id)?.id).toBe(note.id)
      // La entrevista de OTRA empresa no se toca
      expect(getInterview(untouched.id).companyId).toBe(otherCompany.id)
      expect(getInterview(untouched.id).contactIds).toEqual([otherContact.id])
      expect(readDbFile().companies).toEqual([otherCompany])
    })

    // SPEC-043 · AC-06
    it('rejects deleting a nonexistent company with a not-found error without persisting anything', () => {
      createCompany({ name: 'Acme Corp' })
      const before = readFileSync(dbPath, 'utf-8')

      expectDbError(() => deleteCompany('empresa-inexistente'), 'not-found')

      expect(readFileSync(dbPath, 'utf-8')).toBe(before)
    })
  })

  describe('discovery objectives', () => {
    // SPEC-043 · AC-15
    it('creates a discovery persisting the objectives free text, or null when absent', () => {
      const withObjectives = createDiscovery({
        name: 'Vertical Sanidad',
        objectives: 'Validar el dolor del registro manual en clínicas'
      })
      const without = createDiscovery({ name: 'Vertical Legal' })

      expect(withObjectives.objectives).toBe('Validar el dolor del registro manual en clínicas')
      expect(without.objectives).toBeNull()
      const persisted = readDbFile().discoveries
      expect(persisted[0].objectives).toBe('Validar el dolor del registro manual en clínicas')
      expect(persisted[1].objectives).toBeNull()
    })

    // SPEC-043 · AC-16
    it('updates objectives to a text and back to null persisting the change with updatedAt strictly forward', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })

      const withText = updateDiscovery(discovery.id, { objectives: 'Nuevo objetivo del discovery' })
      expect(withText.objectives).toBe('Nuevo objetivo del discovery')
      expect(withText.updatedAt > discovery.updatedAt).toBe(true)
      expect(getDiscovery(discovery.id).objectives).toBe('Nuevo objetivo del discovery')

      const cleared = updateDiscovery(discovery.id, { objectives: null })
      expect(cleared.objectives).toBeNull()
      expect(cleared.updatedAt > withText.updatedAt).toBe(true)
      expect(readDbFile().discoveries[0].objectives).toBeNull()
    })
  })

  describe('interviews with N contacts and optional group', () => {
    // SPEC-043 · AC-17
    it('creates an interview with two contacts of its company preserving the given contactIds order and null interviewGroupId when absent', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const jane = createContact({ companyId: company.id, name: 'Jane Doe' })
      const john = createContact({ companyId: company.id, name: 'John Smith' })

      const interview = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        // Orden dado por el caller (no alfabético ni de creación)
        contactIds: [john.id, jane.id],
        title: 'Entrevista doble'
      })

      expect(interview.contactIds).toEqual([john.id, jane.id])
      expect(interview.interviewGroupId).toBeNull()
      expect(readDbFile().interviews[0].contactIds).toEqual([john.id, jane.id])
    })

    // SPEC-043 · AC-18 (create y update)
    it('rejects contactIds including a contact of another company with a reference error on create and update, persisting nothing', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const own = createContact({ companyId: company.id, name: 'Jane Doe' })
      const otherCompany = createCompany({ name: 'Globex' })
      const foreign = createContact({ companyId: otherCompany.id, name: 'John Smith' })

      expectDbError(
        () =>
          createInterview({
            discoveryId: discovery.id,
            companyId: company.id,
            contactIds: [own.id, foreign.id],
            title: 'Mala'
          }),
        'reference'
      )
      expect(readDbFile().interviews).toEqual([])

      const interview = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [own.id],
        title: 'Buena'
      })
      expectDbError(
        () => updateInterview(interview.id, { contactIds: [own.id, foreign.id] }),
        'reference'
      )
      expect(getInterview(interview.id).contactIds).toEqual([own.id])
    })

    // SPEC-043 · AC-19 (create y update)
    it('rejects non-empty contactIds with a null companyId with a reference error on create and update, persisting nothing', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })

      expectDbError(
        () =>
          createInterview({
            discoveryId: discovery.id,
            contactIds: [contact.id],
            title: 'Sin empresa'
          }),
        'reference'
      )
      expect(readDbFile().interviews).toEqual([])

      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })
      expectDbError(() => updateInterview(capture.id, { contactIds: [contact.id] }), 'reference')
      expect(getInterview(capture.id).contactIds).toEqual([])
    })

    // SPEC-043 · AC-20 (create y update)
    it('rejects duplicated ids inside contactIds with a validation error on create and update, persisting nothing', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })

      expectDbError(
        () =>
          createInterview({
            discoveryId: discovery.id,
            companyId: company.id,
            contactIds: [contact.id, contact.id],
            title: 'Duplicada'
          }),
        'validation'
      )
      expect(readDbFile().interviews).toEqual([])

      const interview = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [contact.id],
        title: 'Buena'
      })
      expectDbError(
        () => updateInterview(interview.id, { contactIds: [contact.id, contact.id] }),
        'validation'
      )
      expect(getInterview(interview.id).contactIds).toEqual([contact.id])
    })

    // SPEC-043 · AC-21
    it('rejects creating an interview of discovery B with a group of discovery A with a reference error, persisting nothing', () => {
      const discoveryA = createDiscovery({ name: 'Discovery A' })
      const discoveryB = createDiscovery({ name: 'Discovery B' })
      const groupA = createInterviewGroup({ discoveryId: discoveryA.id, name: 'Grupo de A' })

      expectDbError(
        () =>
          createInterview({
            discoveryId: discoveryB.id,
            title: 'Cruzada',
            interviewGroupId: groupA.id
          }),
        'reference'
      )
      expect(readDbFile().interviews).toEqual([])
    })

    // SPEC-043 · AC-22
    it('creates an interview with a group of its own discovery persisting the reference', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const group = createInterviewGroup({ discoveryId: discovery.id, name: 'General' })

      const interview = createInterview({
        discoveryId: discovery.id,
        title: 'Entrevista agrupada',
        interviewGroupId: group.id
      })

      expect(interview.interviewGroupId).toBe(group.id)
      expect(readDbFile().interviews[0].interviewGroupId).toBe(group.id)
    })

    // SPEC-043 · AC-23
    it('removes a deleted contact id from the contactIds of every interview keeping the remaining contacts', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const company = createCompany({ name: 'Acme Corp' })
      const jane = createContact({ companyId: company.id, name: 'Jane Doe' })
      const john = createContact({ companyId: company.id, name: 'John Smith' })
      const first = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [jane.id, john.id],
        title: 'Primera'
      })
      const second = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [john.id],
        title: 'Segunda'
      })

      deleteContact(john.id)

      // Cada entrevista sobrevive con el id retirado y los demás conservados
      expect(getInterview(first.id).contactIds).toEqual([jane.id])
      expect(getInterview(second.id).contactIds).toEqual([])
      expect(listContacts(company.id)).toEqual([getContact(jane.id)])
    })
  })

  describe('deferred company assignment (v3)', () => {
    // SPEC-043 · AC-24
    it('accepts assigning any existing company of the system (even one used by another discovery) with contactIds [contacto] or []', () => {
      const discoveryA = createDiscovery({ name: 'Discovery A' })
      const discoveryB = createDiscovery({ name: 'Discovery B' })
      const company = createCompany({ name: 'Globex' })
      const contact = createContact({ companyId: company.id, name: 'John Smith' })
      // La empresa ya se usa en entrevistas del discovery B…
      createInterview({ discoveryId: discoveryB.id, companyId: company.id, title: 'En B' })
      // …y aun así se acepta en una captura del discovery A (derogada la
      // invariante SPEC-020 «empresa ∈ discovery de la captura»)
      const withContact = createInterview({ discoveryId: discoveryA.id, title: 'Captura A1' })
      const withoutContact = createInterview({ discoveryId: discoveryA.id, title: 'Captura A2' })

      // SPEC-046: el input de la asignación viaja con contactIds (N marcados)
      const assigned = assignInterviewCompany(withContact.id, {
        companyId: company.id,
        contactIds: [contact.id]
      })
      const assignedBare = assignInterviewCompany(withoutContact.id, { companyId: company.id })

      expect(assigned.interview.companyId).toBe(company.id)
      expect(assigned.interview.contactIds).toEqual([contact.id])
      expect(assignedBare.interview.companyId).toBe(company.id)
      expect(assignedBare.interview.contactIds).toEqual([])
    })

    // SPEC-043 · AC-25
    it('creates the inline company as GLOBAL and points the interview at it in a single atomic mutation', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      const result = assignInterviewCompany(capture.id, {
        newCompany: { name: 'Globex', website: 'https://globex.example' }
      })

      // Empresa GLOBAL: sin discovery, ni en el resultado ni en el JSON
      expect(result.company).not.toHaveProperty('discoveryId')
      const persisted = readDbFile()
      expect(persisted.companies).toHaveLength(1)
      expect(persisted.companies[0]).not.toHaveProperty('discoveryId')
      expect(persisted.interviews[0].companyId).toBe(result.company.id)

      // Atomicidad: si la parte del contacto falla, tampoco nace la empresa
      const otherCapture = createInterview({ discoveryId: discovery.id, title: 'Otra captura' })
      const before = readFileSync(dbPath, 'utf-8')
      expectDbError(
        () =>
          assignInterviewCompany(otherCapture.id, {
            newCompany: { name: 'Initech' },
            newContact: { name: '   ' }
          }),
        'validation'
      )
      expect(readFileSync(dbPath, 'utf-8')).toBe(before)
    })

    // SPEC-043 · AC-26
    it('resolves the names of ALL the contacts of each capture in contactIds order, omitting broken references defensively', () => {
      const now = '2026-07-01T09:00:00.000Z'
      // Archivo v3 escrito a mano con referencias rotas (contacto fantasma en
      // medio, template fantasma): un dato inconsistente nunca rompe el listado
      writeFileSync(
        dbPath,
        JSON.stringify({
          schemaVersion: 3,
          discoveries: [
            {
              id: 'd-1',
              name: 'Vertical Sanidad',
              objectives: null,
              createdAt: now,
              updatedAt: now
            }
          ],
          companies: [
            {
              id: 'c-1',
              name: 'Acme Corp',
              website: null,
              linkedinUrl: null,
              context: null,
              createdAt: now,
              updatedAt: now
            }
          ],
          contacts: [
            {
              id: 'ct-1',
              companyId: 'c-1',
              name: 'Jane Doe',
              position: null,
              linkedinUrl: null,
              context: null,
              createdAt: now,
              updatedAt: now
            },
            {
              id: 'ct-2',
              companyId: 'c-1',
              name: 'John Smith',
              position: null,
              linkedinUrl: null,
              context: null,
              createdAt: now,
              updatedAt: now
            }
          ],
          interviewTemplates: [],
          interviewGroups: [],
          interviews: [
            {
              id: 'i-1',
              discoveryId: 'd-1',
              companyId: 'c-1',
              // ct-fantasma en medio: se OMITE conservando el orden del resto
              contactIds: ['ct-2', 'ct-fantasma', 'ct-1'],
              interviewGroupId: null,
              templateId: 'tpl-fantasma',
              title: 'Entrevista doble',
              status: 'draft',
              scriptMarkdown: null,
              objectives: [],
              wavPath: null,
              transcriptPath: null,
              createdAt: now,
              updatedAt: now
            }
          ],
          noteTemplates: [],
          notes: []
        })
      )
      initStore(baseDir)

      const items = listAllInterviews()

      expect(items).toHaveLength(1)
      // Nombres de TODOS los contactos en el orden de contactIds (roto omitido)
      expect(items[0].contactNames).toEqual(['John Smith', 'Jane Doe'])
      // El resto del contexto resuelto: discovery, empresa y template (roto → null)
      expect(items[0].discoveryName).toBe('Vertical Sanidad')
      expect(items[0].companyName).toBe('Acme Corp')
      expect(items[0].templateName).toBeNull()
    })
  })

  describe('discovery cascade (v3)', () => {
    // SPEC-043 · AC-34
    it('deletes a discovery cascading its groups, its interviews (with and without group) and their notes, but no company nor contact', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const otherDiscovery = createDiscovery({ name: 'Otro discovery' })
      const company = createCompany({ name: 'Acme Corp' })
      const contact = createContact({ companyId: company.id, name: 'Jane Doe' })
      const group = createInterviewGroup({ discoveryId: discovery.id, name: 'General' })
      const survivorGroup = createInterviewGroup({
        discoveryId: otherDiscovery.id,
        name: 'Grupo superviviente'
      })
      const grouped = createInterview({
        discoveryId: discovery.id,
        companyId: company.id,
        contactIds: [contact.id],
        interviewGroupId: group.id,
        title: 'Agrupada'
      })
      const ungrouped = createInterview({ discoveryId: discovery.id, title: 'Sin grupo' })
      createNote({ interviewId: grouped.id, contentMarkdown: '# Nota agrupada' })
      createNote({ interviewId: ungrouped.id, contentMarkdown: '# Nota suelta' })
      const survivorInterview = createInterview({
        discoveryId: otherDiscovery.id,
        title: 'Superviviente',
        interviewGroupId: survivorGroup.id
      })

      deleteDiscovery(discovery.id)

      const persisted = readDbFile()
      // Caen sus entrevistas (con y sin grupo), las notas de estas y sus grupos
      expect(persisted.interviews.map((interview) => interview.id)).toEqual([survivorInterview.id])
      expect(persisted.notes).toEqual([])
      expect(persisted.interviewGroups.map((item) => item.id)).toEqual([survivorGroup.id])
      // Y NINGUNA empresa ni contacto
      expect(persisted.companies).toEqual([company])
      expect(persisted.contacts).toEqual([contact])
    })
  })
})
