// @vitest-environment node
/**
 * SPEC-021: coste de IA — capa de persistencia (singleton aiCostSettings con
 * normalización defensiva y validación; acumulador aiUsage que no toca
 * updatedAt). Store JSON REAL en directorio temporal (patrón persistence).
 * Generated by QA Dev agent.
 */
import { mkdtempSync, readFileSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { DbOperationError } from '../../../src/main/db/errors'
import {
  addInterviewAiUsage,
  createDiscovery,
  createInterview,
  getAiCostSettings,
  getInterview,
  setAiCostSettings
} from '../../../src/main/db/repository'
import { initStore, type DbData } from '../../../src/main/db/store'

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  }
}))

let baseDir = ''
let dbPath = ''

function readDbFile(): DbData & { aiCostSettings?: unknown } {
  return JSON.parse(readFileSync(dbPath, 'utf-8')) as DbData & { aiCostSettings?: unknown }
}

beforeEach(() => {
  baseDir = mkdtempSync(join(tmpdir(), 'maurya-aicost-db-'))
  dbPath = join(baseDir, 'db.json')
  initStore(baseDir)
})

describe('repository (coste de IA SPEC-021)', () => {
  describe('aiCostSettings', () => {
    // SPEC-021 · AC-09 (main: persistencia del límite; vacío = sin límite)
    it('persists the limit singleton and reads it back, with null clearing the limit', () => {
      // Sin campo persistido → sin límite
      expect(getAiCostSettings()).toEqual({ limitUsd: null })

      expect(setAiCostSettings({ limitUsd: 2.5 })).toEqual({ limitUsd: 2.5 })
      expect(getAiCostSettings()).toEqual({ limitUsd: 2.5 })
      expect(readDbFile().aiCostSettings).toEqual({ limitUsd: 2.5 })

      // Vaciar el campo persiste "sin límite"
      expect(setAiCostSettings({ limitUsd: null })).toEqual({ limitUsd: null })
      expect(getAiCostSettings()).toEqual({ limitUsd: null })
    })

    // SPEC-021 · AC-10 (main: validación con el literal del AC, sin persistir)
    it('rejects non-positive or non-finite limits with the exact validation message persisting nothing', () => {
      for (const invalid of [-1, 0, Number.NaN, Number.POSITIVE_INFINITY]) {
        let caught: unknown = null
        try {
          setAiCostSettings({ limitUsd: invalid })
        } catch (error) {
          caught = error
        }
        expect(caught).toBeInstanceOf(DbOperationError)
        expect((caught as DbOperationError).kind).toBe('validation')
        expect((caught as DbOperationError).message).toBe(
          'Introduce un importe positivo o deja el campo vacío'
        )
      }
      expect(readDbFile().aiCostSettings).toBeUndefined()
    })

    // SPEC-021 · AC-18 (ajuste corrupto o ilegible → sin límite sin crashear)
    it('normalizes a corrupt or unreadable persisted setting to "no limit" without crashing', () => {
      const base = readDbFile()
      for (const corrupt of ['garbage', { limitUsd: 'mucho' }, { limitUsd: -5 }, 42]) {
        writeFileSync(dbPath, JSON.stringify({ ...base, aiCostSettings: corrupt }))
        expect(() => initStore(baseDir)).not.toThrow()
        expect(getAiCostSettings()).toEqual({ limitUsd: null })
      }
    })
  })

  describe('addInterviewAiUsage', () => {
    // SPEC-021 · AC-01/AC-03 (main: acumulación campo a campo sin tocar updatedAt)
    it('accumulates the usage field by field from an absent aiUsage without touching updatedAt', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const interview = createInterview({ discoveryId: discovery.id, title: 'Captura medida' })

      const first = addInterviewAiUsage(interview.id, {
        calls: 1,
        inputTokens: 1000,
        outputTokens: 500,
        estimatedCostUsd: 0.0175
      })
      expect(first.aiUsage).toEqual({
        calls: 1,
        inputTokens: 1000,
        outputTokens: 500,
        estimatedCostUsd: 0.0175
      })

      const second = addInterviewAiUsage(interview.id, {
        calls: 4,
        inputTokens: 200,
        outputTokens: 100,
        estimatedCostUsd: 0.0035
      })
      expect(second.aiUsage).toMatchObject({
        calls: 5,
        inputTokens: 1200,
        outputTokens: 600
      })
      // Suma en coma flotante: tolerancia estándar
      expect(second.aiUsage?.estimatedCostUsd).toBeCloseTo(0.021, 10)
      // La medición NO es una edición del usuario: updatedAt intacto (el
      // listado de capturas por updatedAt desc no se reordena)
      expect(second.updatedAt).toBe(interview.updatedAt)
      // Persistido en disco
      expect(getInterview(interview.id).aiUsage?.calls).toBe(5)
      expect(readDbFile().interviews[0].aiUsage?.calls).toBe(5)
    })
  })
})
