// @vitest-environment node
/**
 * SPEC-046: Entrevistas con N participantes — asignación diferida de empresa
 * con múltiples contactos (`assignInterviewCompany` con `contactIds` +
 * `newContact` que se SUMA), invariante v3 reutilizada (duplicados →
 * validation, pertenencia → reference), atomicidad de la mutación única y
 * resultado `contacts` en el orden persistido.
 * Generated by QA Dev agent.
 *
 * Store JSON REAL en directorio temporal (initStore(baseDir) inyectable,
 * patrón tests/unit/persistence/repository.captures.test.ts). Electron
 * mockeado con un guard que lanza si algo usara app.getPath.
 */
import { mkdtempSync, readFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { DbOperationError } from '../../../src/main/db/errors'
import {
  assignInterviewCompany,
  createCompany,
  createContact,
  createDiscovery,
  createInterview,
  getInterview
} from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'
import type { Contact, Discovery } from '../../../src/renderer/src/types/domain'
import type { DbErrorKind } from '../../../src/renderer/src/types/domain'

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  }
}))

let baseDir = ''
let dbPath = ''

/** Captura el error tipado de una operación que debe fallar. */
function expectDbError(fn: () => unknown, kind: DbErrorKind): DbOperationError {
  let caught: unknown = null
  try {
    fn()
  } catch (error) {
    caught = error
  }
  expect(caught).toBeInstanceOf(DbOperationError)
  const dbError = caught as DbOperationError
  expect(dbError.kind).toBe(kind)
  return dbError
}

interface Seeded {
  discovery: Discovery
  companyId: string
  jane: Contact
  john: Contact
}

/** Discovery + empresa con dos contactos (Jane y John). */
function seedCompanyWithContacts(): Seeded {
  const discovery = createDiscovery({ name: 'Vertical Sanidad' })
  const company = createCompany({ name: 'Acme Corp' })
  const jane = createContact({ companyId: company.id, name: 'Jane Doe', position: 'CTO' })
  const john = createContact({ companyId: company.id, name: 'John Smith' })
  return { discovery, companyId: company.id, jane, john }
}

beforeEach(() => {
  baseDir = mkdtempSync(join(tmpdir(), 'maurya-participants-db-'))
  dbPath = join(baseDir, 'db.json')
  initStore(baseDir)
})

describe('repository (SPEC-046 participantes)', () => {
  describe('assignInterviewCompany with N contacts', () => {
    // SPEC-046 · AC-25 (main: los N marcados quedan en contactIds en una
    // única mutación) — el resultado lleva contacts en el orden persistido
    it('assigns two marked contacts persisting contactIds in the given order and returns contacts resolved in that order', () => {
      const { discovery, companyId, jane, john } = seedCompanyWithContacts()
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      // Orden de marcado inverso al de alta: el persistido es el DEL INPUT
      const result = assignInterviewCompany(capture.id, {
        companyId,
        contactIds: [john.id, jane.id]
      })

      expect(result.interview.companyId).toBe(companyId)
      expect(result.interview.contactIds).toEqual([john.id, jane.id])
      expect(result.contacts.map((contact) => contact.id)).toEqual([john.id, jane.id])
      expect(result.contacts.map((contact) => contact.name)).toEqual(['John Smith', 'Jane Doe'])
      expect(getInterview(capture.id).contactIds).toEqual([john.id, jane.id])
    })

    // SPEC-046 · AC-23 (main: el contacto nuevo inline se SUMA a los marcados,
    // al final — deroga la exclusión mutua contactId/newContact de SPEC-020)
    it('appends the inline new contact after the marked ones as another participant of the same company', () => {
      const { discovery, companyId, jane, john } = seedCompanyWithContacts()
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      const result = assignInterviewCompany(capture.id, {
        companyId,
        contactIds: [jane.id, john.id],
        newContact: { name: 'Ada López', position: 'CEO' }
      })

      // Marcados primero, el nuevo inline al final
      expect(result.contacts).toHaveLength(3)
      expect(result.contacts.slice(0, 2).map((contact) => contact.id)).toEqual([jane.id, john.id])
      const created = result.contacts[2]
      expect(created.name).toBe('Ada López')
      expect(created.companyId).toBe(companyId)
      expect(result.interview.contactIds).toEqual([jane.id, john.id, created.id])
    })

    // SPEC-046 · AC-25 (main: la invariante v3 sigue vigente — ids duplicados
    // en la lista de marcados → validation, sin escrituras)
    it('rejects duplicated ids inside contactIds with a validation error persisting nothing', () => {
      const { discovery, companyId, jane } = seedCompanyWithContacts()
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })
      const before = readFileSync(dbPath, 'utf-8')

      expectDbError(
        () =>
          assignInterviewCompany(capture.id, {
            companyId,
            contactIds: [jane.id, jane.id]
          }),
        'validation'
      )

      expect(readFileSync(dbPath, 'utf-8')).toBe(before)
      expect(getInterview(capture.id).companyId).toBeNull()
    })

    // SPEC-046 · AC-25 (main: contacto de OTRA empresa entre los marcados →
    // reference, cero escrituras — invariante v3 vía assertInterviewContacts)
    it('rejects a marked contact belonging to another company with a reference error persisting nothing', () => {
      const { discovery, companyId, jane } = seedCompanyWithContacts()
      const otherCompany = createCompany({ name: 'Globex' })
      const foreign = createContact({ companyId: otherCompany.id, name: 'Intruso Ajeno' })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })
      const before = readFileSync(dbPath, 'utf-8')

      expectDbError(
        () =>
          assignInterviewCompany(capture.id, {
            companyId,
            contactIds: [jane.id, foreign.id]
          }),
        'reference'
      )

      expect(readFileSync(dbPath, 'utf-8')).toBe(before)
      expect(getInterview(capture.id).companyId).toBeNull()
    })

    // SPEC-046 · AC-24 (main: con empresa NUEVA inline los contactIds marcados
    // no pueden existir — la validación lanza reference de forma natural y la
    // empresa nueva tampoco nace: atomicidad del mutate único)
    it('rejects a new inline company combined with marked contactIds with a reference error, creating neither', () => {
      const { discovery, jane } = seedCompanyWithContacts()
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })
      const before = readFileSync(dbPath, 'utf-8')

      expectDbError(
        () =>
          assignInterviewCompany(capture.id, {
            newCompany: { name: 'Initech' },
            contactIds: [jane.id]
          }),
        'reference'
      )

      // Atomicidad: ni la empresa nueva ni cambio alguno en la entrevista
      expect(readFileSync(dbPath, 'utf-8')).toBe(before)
      expect(getInterview(capture.id).companyId).toBeNull()
      expect(getInterview(capture.id).contactIds).toEqual([])
    })

    // SPEC-046 · AC-24 (main: con empresa nueva el único participante posible
    // es el contacto nuevo inline — comportamiento SPEC-020 conservado)
    it('assigns a new inline company whose only participant is the inline new contact', () => {
      const discovery = createDiscovery({ name: 'Vertical Sanidad' })
      const capture = createInterview({ discoveryId: discovery.id, title: 'Captura suelta' })

      const result = assignInterviewCompany(capture.id, {
        newCompany: { name: 'Globex' },
        contactIds: [],
        newContact: { name: 'John Smith' }
      })

      expect(result.company.name).toBe('Globex')
      expect(result.contacts).toHaveLength(1)
      expect(result.contacts[0].name).toBe('John Smith')
      expect(result.contacts[0].companyId).toBe(result.company.id)
      expect(result.interview.contactIds).toEqual([result.contacts[0].id])
    })
  })
})
