/**
 * SPEC-039: acciones por pregunta en el panel del asistente (mitad UI) — tres
 * acciones por ítem pendiente («Marcar respondida», «Descartar pregunta»,
 * «Anclar pregunta») y por ítem anclado (con «Desanclar pregunta»), click en
 * descartar/respondida → resolveItem(id, outcome) sin confirmación ni Toast,
 * y desaparición del ítem al reflejarse el evento de main (única fuente de
 * verdad: la mutación se simula re-emitiendo la cola sin él).
 * Generated by QA Dev agent.
 *
 * Montado vía InterviewDetailPage con la grabación en curso (arnés SPEC-016/
 * 036) y eventos inyectados con emitAssistantUpdate.
 */
import { act, render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import {
  acquireMicrophoneStream,
  acquireSystemAudioStream,
  listAudioInputDevices
} from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { AssistantQueue, AssistantQueueItem } from '@/types/assistant'
import type { Company, Interview } from '@/types/domain'
import { createFakeAudioStream } from '../../helpers/fakeMediaStream'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = vi.fn()
    stop = vi.fn()
    getLevels = vi.fn(() => ({ microphone: 0, system: 0 }))
    readonly durationSeconds = 0
    readonly samplesWritten = 0
  }
}))

let mockApi: MockApiHandle

const COMPANY: Company = {
  id: 'c-1',
  discoveryId: 'd-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const INTERVIEW: Interview = {
  id: 'i-1',
  discoveryId: 'd-1',
  companyId: 'c-1',
  contactId: null,
  templateId: null,
  title: 'Discovery con Acme',
  status: 'draft',
  scriptMarkdown: null,
  objectives: [],
  wavPath: null,
  transcriptPath: null,
  createdAt: '2026-07-04T10:00:00.000Z',
  updatedAt: '2026-07-04T10:00:00.000Z'
}

const QUESTION_1 = '¿Cuándo fue la última vez que pasó?'
const QUESTION_2 = '¿Quién más participó en esa decisión?'

function queueItem(overrides: Partial<AssistantQueueItem> = {}): AssistantQueueItem {
  return {
    id: 'q-1',
    action: 'continue',
    suggestedQuestion: QUESTION_1,
    reason: 'Ya hay material concreto para avanzar',
    alarms: [],
    ...overrides
  }
}

function emitQueue(queue: AssistantQueue): void {
  act(() => {
    mockApi.emitAssistantUpdate({ state: 'active', queue, objectivesMet: [] })
  })
}

function renderDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route
            path="/discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
            element={<InterviewDetailPage />}
          />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

/** Arranca la grabación atravesando el aviso de consentimiento (SPEC-019). */
async function startRecording(user: ReturnType<typeof userEvent.setup>): Promise<void> {
  await user.click(await screen.findByRole('button', { name: 'Iniciar grabación' }))
  const consent = await screen.findByRole('alertdialog')
  await user.click(within(consent).getByRole('button', { name: 'Entendido, iniciar grabación' }))
  await screen.findByRole('button', { name: 'Detener' })
}

beforeEach(() => {
  vi.clearAllMocks()
  window.localStorage.clear()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: INTERVIEW })
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  vi.mocked(acquireMicrophoneStream).mockResolvedValue(createFakeAudioStream().stream)
  vi.mocked(acquireSystemAudioStream).mockResolvedValue(createFakeAudioStream().stream)
  // Auto-stop al desmontar (cleanup de RecordingSection): resolución mínima
  vi.mocked(mockApi.api.recording.stop).mockResolvedValue({
    filePath: '/tmp/maurya-recordings/entrevista.wav',
    durationSeconds: 5,
    sizeBytes: 44,
    sampleRate: 16000,
    channels: 2,
    transcriptPath: null,
    latency: null,
    interview: null
  })
})

describe('AssistantPanel (acciones por pregunta SPEC-039)', () => {
  describe('actions offered per item', () => {
    // SPEC-039 · AC-01 (pendiente: Marcar respondida + Descartar + Anclar, por aria-label)
    it('offers Marcar respondida, Descartar pregunta and Anclar pregunta on a pending item', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)

      emitQueue({ pending: [queueItem()], pinned: [] })

      const item = await screen.findByTestId('assistant-queue-item')
      const answered = within(item).getByRole('button', { name: 'Marcar respondida' })
      const discard = within(item).getByRole('button', { name: 'Descartar pregunta' })
      expect(answered).toHaveAttribute('data-testid', 'assistant-item-answered')
      expect(discard).toHaveAttribute('data-testid', 'assistant-item-discard')
      expect(within(item).getByRole('button', { name: 'Anclar pregunta' })).toBeInTheDocument()
      // Anclar solo existe en pendientes: sin Desanclar aquí
      expect(
        within(item).queryByRole('button', { name: 'Desanclar pregunta' })
      ).not.toBeInTheDocument()
    })

    // SPEC-039 · AC-02 (anclada: mismas acciones pero con Desanclar en vez de Anclar)
    it('offers Marcar respondida, Descartar pregunta and Desanclar pregunta on a pinned item only', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)

      emitQueue({
        pending: [queueItem({ id: 'q-2', suggestedQuestion: QUESTION_2 })],
        pinned: [queueItem()]
      })

      const pinnedItem = await screen.findByTestId('assistant-pinned-item')
      expect(
        within(pinnedItem).getByRole('button', { name: 'Marcar respondida' })
      ).toBeInTheDocument()
      expect(
        within(pinnedItem).getByRole('button', { name: 'Descartar pregunta' })
      ).toBeInTheDocument()
      expect(
        within(pinnedItem).getByRole('button', { name: 'Desanclar pregunta' })
      ).toBeInTheDocument()
      // Desanclar solo existe en ancladas y anclar solo en pendientes
      expect(
        within(pinnedItem).queryByRole('button', { name: 'Anclar pregunta' })
      ).not.toBeInTheDocument()
      const pendingItem = screen.getByTestId('assistant-queue-item')
      expect(
        within(pendingItem).getByRole('button', { name: 'Anclar pregunta' })
      ).toBeInTheDocument()
      expect(
        within(pendingItem).queryByRole('button', { name: 'Desanclar pregunta' })
      ).not.toBeInTheDocument()
    })
  })

  describe('discard and answered clicks', () => {
    // SPEC-039 · AC-03 (Descartar → resolveItem(id, 'discarded'), sin confirmación ni Toast)
    it('calls resolveItem with discarded on the discard button and removes the item when main re-emits the queue', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)
      emitQueue({ pending: [queueItem()], pinned: [] })
      const item = await screen.findByTestId('assistant-queue-item')

      await user.click(within(item).getByRole('button', { name: 'Descartar pregunta' }))

      expect(vi.mocked(mockApi.api.assistant.resolveItem)).toHaveBeenCalledWith(
        'q-1',
        'discarded'
      )
      // Sin confirmación (ningún AlertDialog) ni Toast de sonner
      expect(screen.queryByRole('alertdialog')).not.toBeInTheDocument()
      expect(document.querySelector('[data-sonner-toast]')).toBeNull()

      // Main confirma re-emitiendo la cola SIN la pregunta (sin estado optimista)
      emitQueue({ pending: [], pinned: [] })
      await waitFor(() =>
        expect(screen.queryByTestId('assistant-queue-item')).not.toBeInTheDocument()
      )
      expect(screen.queryByText(QUESTION_1)).not.toBeInTheDocument()
    })

    // SPEC-039 · AC-04 (Marcar respondida → resolveItem(id, 'answered') y desaparece)
    it('calls resolveItem with answered on the answered button and removes the item when main re-emits the queue', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)
      emitQueue({
        pending: [queueItem({ id: 'q-2', suggestedQuestion: QUESTION_2 }), queueItem()],
        pinned: []
      })
      const items = await screen.findAllByTestId('assistant-queue-item')

      await user.click(within(items[0]).getByRole('button', { name: 'Marcar respondida' }))

      expect(vi.mocked(mockApi.api.assistant.resolveItem)).toHaveBeenCalledWith('q-2', 'answered')

      // Main re-emite la cola sin la respondida: solo queda la otra pregunta
      emitQueue({ pending: [queueItem()], pinned: [] })
      await waitFor(() => expect(screen.queryByText(QUESTION_2)).not.toBeInTheDocument())
      expect(screen.getByText(QUESTION_1)).toBeInTheDocument()
      expect(screen.getAllByTestId('assistant-queue-item')).toHaveLength(1)
    })
  })
})
