/**
 * SPEC-036: cola de preguntas en el panel del asistente (mitad UI) — ítems de
 * la cola con badge/chips/pregunta/porqué, orden más reciente primero, sección
 * «Ancladas» condicional sin porqué, anclar/desanclar por aria-label y la cola
 * intacta tras la pausa por límite (SPEC-021).
 * Generated by QA Dev agent.
 *
 * Montado vía InterviewDetailPage con la grabación en curso (arnés SPEC-016) y
 * eventos inyectados con emitAssistantUpdate; main es la única fuente de
 * verdad de la cola, así que cada mutación se simula re-emitiendo el evento.
 */
import { act, render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import {
  acquireMicrophoneStream,
  acquireSystemAudioStream,
  listAudioInputDevices
} from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { AssistantQueue, AssistantQueueItem } from '@/types/assistant'
import type { Company, Interview } from '@/types/domain'
import { createFakeAudioStream } from '../../helpers/fakeMediaStream'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = vi.fn()
    stop = vi.fn()
    getLevels = vi.fn(() => ({ microphone: 0, system: 0 }))
    readonly durationSeconds = 0
    readonly samplesWritten = 0
  }
}))

let mockApi: MockApiHandle

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const INTERVIEW: Interview = {
  id: 'i-1',
  discoveryId: 'd-1',
  companyId: 'c-1',
  contactIds: [],
  interviewGroupId: null,
  templateId: null,
  title: 'Discovery con Acme',
  status: 'draft',
  scriptMarkdown: null,
  objectives: [],
  wavPath: null,
  transcriptPath: null,
  createdAt: '2026-07-04T10:00:00.000Z',
  updatedAt: '2026-07-04T10:00:00.000Z'
}

const QUESTION_1 = '¿Cuándo fue la última vez que pasó?'
const QUESTION_2 = '¿Quién más participó en esa decisión?'

function queueItem(overrides: Partial<AssistantQueueItem> = {}): AssistantQueueItem {
  return {
    id: 'q-1',
    action: 'continue',
    suggestedQuestion: QUESTION_1,
    reason: 'Ya hay material concreto para avanzar',
    alarms: [],
    ...overrides
  }
}

function emitQueue(queue: AssistantQueue, state: 'active' | 'analyzing' = 'active'): void {
  act(() => {
    mockApi.emitAssistantUpdate({ state, queue, objectivesMet: [] })
  })
}

function renderDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route
            path="/discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
            element={<InterviewDetailPage />}
          />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

/** Arranca la grabación atravesando el aviso de consentimiento (SPEC-019). */
async function startRecording(user: ReturnType<typeof userEvent.setup>): Promise<void> {
  await user.click(await screen.findByRole('button', { name: 'Iniciar grabación' }))
  const consent = await screen.findByRole('alertdialog')
  await user.click(within(consent).getByRole('button', { name: 'Entendido, iniciar grabación' }))
  await screen.findByRole('button', { name: 'Detener' })
}

beforeEach(() => {
  vi.clearAllMocks()
  window.localStorage.clear()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: INTERVIEW })
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  vi.mocked(acquireMicrophoneStream).mockResolvedValue(createFakeAudioStream().stream)
  vi.mocked(acquireSystemAudioStream).mockResolvedValue(createFakeAudioStream().stream)
  // Auto-stop al desmontar (cleanup de RecordingSection): resolución mínima
  vi.mocked(mockApi.api.recording.stop).mockResolvedValue({
    filePath: '/tmp/maurya-recordings/entrevista.wav',
    durationSeconds: 5,
    sizeBytes: 44,
    sampleRate: 16000,
    channels: 2,
    transcriptPath: null,
    latency: null,
    interview: null
  })
})

describe('AssistantPanel (cola SPEC-036)', () => {
  describe('pending queue', () => {
    // SPEC-036 · AC-01 (UI: ítem completo con badge, chips, pregunta, porqué y anclar)
    it('renders a pending item with its action badge, alarm chips, question, reason and pin button', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)

      emitQueue({
        pending: [
          queueItem({
            action: 'dig_deeper',
            reason: 'Falta un caso concreto: pide el último episodio',
            alarms: ['compliment', 'generic']
          })
        ],
        pinned: []
      })

      const item = await screen.findByTestId('assistant-queue-item')
      expect(within(item).getByText('Profundiza')).toBeInTheDocument()
      expect(within(item).getByText('Cumplido')).toBeInTheDocument()
      expect(within(item).getByText('Genérico')).toBeInTheDocument()
      expect(within(item).getByText(QUESTION_1)).toBeInTheDocument()
      expect(
        within(item).getByText('Falta un caso concreto: pide el último episodio')
      ).toBeInTheDocument()
      expect(within(item).getByRole('button', { name: 'Anclar pregunta' })).toBeInTheDocument()
    })

    // SPEC-036 · AC-02 (UI: ambas visibles, la más reciente primero)
    it('shows both queued questions with the most recent first when a second one arrives', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)

      emitQueue({ pending: [queueItem()], pinned: [] })
      await screen.findByText(QUESTION_1)
      // Main re-emite la cola completa con la nueva candidata al frente
      emitQueue({
        pending: [queueItem({ id: 'q-2', suggestedQuestion: QUESTION_2 }), queueItem()],
        pinned: []
      })

      const items = await screen.findAllByTestId('assistant-queue-item')
      expect(items).toHaveLength(2)
      expect(within(items[0]).getByText(QUESTION_2)).toBeInTheDocument()
      expect(within(items[1]).getByText(QUESTION_1)).toBeInTheDocument()
    })

    // SPEC-036 · AC-19 (UI: «Analizando…» convive con la cola sin ocultarla)
    it('keeps the queued questions visible under the Analizando indicator', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)

      emitQueue({ pending: [queueItem()], pinned: [] })
      await screen.findByText(QUESTION_1)
      emitQueue({ pending: [queueItem()], pinned: [] }, 'analyzing')

      expect(await screen.findByText('Analizando…')).toBeInTheDocument()
      expect(screen.getByText(QUESTION_1)).toBeInTheDocument()
    })
  })

  describe('pinned section', () => {
    // SPEC-036 · AC-09 (UI: sin ancladas la sección no se renderiza)
    it('does not render the Ancladas section when nothing is pinned', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)

      emitQueue({ pending: [queueItem()], pinned: [] })

      await screen.findByTestId('assistant-queue-item')
      expect(screen.queryByTestId('assistant-pinned-section')).not.toBeInTheDocument()
      expect(screen.queryByText('Ancladas')).not.toBeInTheDocument()
    })

    // SPEC-036 · AC-08 (UI: anclar → setPinned(id, true) y la pregunta pasa a «Ancladas»)
    it('calls setPinned on the pin button and moves the question to the Ancladas section without its reason', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)
      emitQueue({ pending: [queueItem()], pinned: [] })
      const item = await screen.findByTestId('assistant-queue-item')

      await user.click(within(item).getByRole('button', { name: 'Anclar pregunta' }))
      expect(vi.mocked(mockApi.api.assistant.setPinned)).toHaveBeenCalledWith('q-1', true)

      // Main confirma re-emitiendo la cola mutada (sin estado optimista)
      emitQueue({ pending: [], pinned: [queueItem()] })

      const section = await screen.findByTestId('assistant-pinned-section')
      expect(within(section).getByText('Ancladas')).toBeInTheDocument()
      const pinnedItem = within(section).getByTestId('assistant-pinned-item')
      expect(within(pinnedItem).getByText(QUESTION_1)).toBeInTheDocument()
      // Los ítems anclados omiten el porqué (máxima compacidad)
      expect(
        within(pinnedItem).queryByText('Ya hay material concreto para avanzar')
      ).not.toBeInTheDocument()
      expect(
        within(pinnedItem).getByRole('button', { name: 'Desanclar pregunta' })
      ).toBeInTheDocument()
      // Ya no queda ningún ítem pendiente
      expect(screen.queryByTestId('assistant-queue-item')).not.toBeInTheDocument()
    })

    // SPEC-036 · AC-11 (UI: desanclar → setPinned(id, false) y vuelve a pendientes)
    it('calls setPinned on the unpin button and returns the question to the pending list', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)
      emitQueue({ pending: [], pinned: [queueItem()] })
      const section = await screen.findByTestId('assistant-pinned-section')

      await user.click(within(section).getByRole('button', { name: 'Desanclar pregunta' }))
      expect(vi.mocked(mockApi.api.assistant.setPinned)).toHaveBeenCalledWith('q-1', false)

      emitQueue({ pending: [queueItem()], pinned: [] })

      const item = await screen.findByTestId('assistant-queue-item')
      expect(within(item).getByText(QUESTION_1)).toBeInTheDocument()
      await waitFor(() =>
        expect(screen.queryByTestId('assistant-pinned-section')).not.toBeInTheDocument()
      )
    })
  })

  describe('pause by cost limit (SPEC-021 regression)', () => {
    // SPEC-036 · AC-21 (el Alert sustituye a la lista y la cola reaparece intacta)
    it('hides the queue behind the paused alert and restores it intact after resuming', async () => {
      const user = userEvent.setup()
      renderDetail()
      await startRecording(user)
      const queue: AssistantQueue = {
        pending: [queueItem({ id: 'q-2', suggestedQuestion: QUESTION_2 }), queueItem()],
        pinned: []
      }
      emitQueue(queue)
      await screen.findByText(QUESTION_2)

      // Pausa por límite: el evento transporta la cola pero el Alert la sustituye
      act(() => {
        mockApi.emitAssistantUpdate({
          state: 'paused',
          queue,
          objectivesMet: [],
          pauseLimitUsd: 1
        })
      })
      const alert = await screen.findByTestId('assistant-paused-alert')
      expect(screen.queryByText(QUESTION_1)).not.toBeInTheDocument()
      expect(screen.queryByText(QUESTION_2)).not.toBeInTheDocument()

      await user.click(within(alert).getByRole('button', { name: 'Reanudar asistente' }))
      expect(vi.mocked(mockApi.api.assistant.resume)).toHaveBeenCalledTimes(1)

      // Main confirma la reanudación con la MISMA cola: reaparece intacta
      emitQueue(queue)
      expect(await screen.findByText(QUESTION_2)).toBeInTheDocument()
      expect(screen.getByText(QUESTION_1)).toBeInTheDocument()
      expect(screen.queryByTestId('assistant-paused-alert')).not.toBeInTheDocument()
    })
  })
})
