// @vitest-environment node
/**
 * SPEC-038: detección en vivo de preguntas de la cola ya respondidas —
 * resolución determinista inmediata cuando el entrevistador (canal mic)
 * formula una pregunta casi idéntica a una pendiente (métrica SPEC-037, sin
 * llamada al LLM, ancladas exentas, solo líneas finales), primera barrera
 * reforzada en el prompt (revisión una a una + respondidas sin formularse) y
 * regresión del mecanismo resolvedQueueIndexes de SPEC-036 y de la
 * byte-estabilidad de SPEC-023.
 * Generated by QA Dev agent.
 *
 * Arnés de SPEC-016/021/036/037 (SDK y Deepgram mockeados con clases de error
 * espejo, store/repository y transcriptionService REALES, fake timers solo de
 * Date).
 */
import { mkdtempSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import type { WebContents } from 'electron'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  MIN_INTERVAL_MS,
  setAssistantPinned,
  startAssistant,
  stopAssistant
} from '../../../src/main/assistantService'
import * as repository from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'
import type { DeepgramCallbacks } from '../../../src/main/deepgramService'
import { resetTranscription, startTranscription } from '../../../src/main/transcriptionService'
import type {
  AssistantQueue,
  AssistantUpdateEvent
} from '../../../src/renderer/src/types/assistant'

const harness = vi.hoisted(() => {
  /** Jerarquía espejo de la del SDK: instanceof debe funcionar en mapSdkError. */
  class APIError extends Error {}
  class AuthenticationError extends APIError {}
  class RateLimitError extends APIError {}
  class APIConnectionError extends APIError {}
  return {
    create: vi.fn(),
    dgInstances: [] as unknown[],
    errors: { APIError, AuthenticationError, RateLimitError, APIConnectionError }
  }
})

vi.mock('@anthropic-ai/sdk', () => {
  class MockAnthropic {
    static APIError = harness.errors.APIError
    static AuthenticationError = harness.errors.AuthenticationError
    static RateLimitError = harness.errors.RateLimitError
    static APIConnectionError = harness.errors.APIConnectionError
    readonly messages = { create: harness.create }
  }
  return { default: MockAnthropic }
})

vi.mock('../../../src/main/deepgramService', () => ({
  DeepgramConnection: class {
    apiKey: string
    callbacks: DeepgramCallbacks
    opened = false
    isOpen = false
    sendAudio = vi.fn(() => true)
    sendKeepAlive = vi.fn()
    closeStream = vi.fn()
    terminate = vi.fn()

    constructor(apiKey: string, callbacks: DeepgramCallbacks) {
      this.apiKey = apiKey
      this.callbacks = callbacks
      harness.dgInstances.push(this)
    }
  },
  classifyConnectionFailure: vi.fn(() => Promise.resolve('other' as const))
}))

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

interface FakeConnection {
  callbacks: DeepgramCallbacks
  opened: boolean
  isOpen: boolean
}

/** Parámetros relevantes de una llamada create del asistente. */
interface CreateParams {
  system: unknown
  messages: Array<{ role: string; content: string }>
}

function createCall(index: number): CreateParams {
  return harness.create.mock.calls[index][0] as CreateParams
}

/** Respuesta del SDK con bloque thinking + bloque text (el JSON va en text). */
function sdkResponse(payload: Record<string, unknown>): unknown {
  return {
    stop_reason: 'end_turn',
    content: [
      { type: 'thinking', thinking: 'razonamiento' },
      { type: 'text', text: JSON.stringify(payload) }
    ]
  }
}

function analysisPayload(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    action: 'continue',
    suggestedQuestion: '¿Cuándo fue la última vez que pasó?',
    reason: 'Ya hay material concreto para avanzar',
    alarms: [],
    objectivesMet: [],
    resolvedQueueIndexes: [],
    ...overrides
  }
}

function createSender(): { sender: WebContents; send: ReturnType<typeof vi.fn> } {
  const send = vi.fn()
  const senderLike = {
    isDestroyed: (): boolean => false,
    send
  }
  return { sender: senderLike as unknown as WebContents, send }
}

function assistantEvents(send: ReturnType<typeof vi.fn>): AssistantUpdateEvent[] {
  return send.mock.calls
    .filter((call) => call[0] === 'assistant:update')
    .map((call) => call[1] as AssistantUpdateEvent)
}

const BASE_TIME_MS = 1_000_000_000

let send: ReturnType<typeof vi.fn>
let connection: FakeConnection
let lineCounter = 0
let analysisCount = 0

/** Inyecta una línea por la vía pública. channelIndex 0 = mic, 1 = system. */
function feedLine(channelIndex: number, text: string, isFinal = true): void {
  lineCounter += 1
  connection.callbacks.onResult({
    channelIndex,
    transcript: text,
    isFinal,
    startSeconds: lineCounter,
    durationSeconds: 1,
    speaker: 0
  })
}

/** Línea final de relleno (alterna canales, texto neutro). */
function feedFinal(): void {
  feedLine(lineCounter % 2, `Línea de conversación ${lineCounter + 1}`)
}

/** Último estado de la cola emitido por main (fuente de verdad del renderer). */
function lastQueue(): AssistantQueue {
  const queue = assistantEvents(send).at(-1)?.queue
  if (queue === undefined) {
    throw new Error('sin eventos del asistente todavía')
  }
  return queue
}

function pendingQuestions(): string[] {
  return lastQueue().pending.map((item) => item.suggestedQuestion)
}

/** Arranca transcripción + asistente sobre una entrevista con objetivos y guión. */
function startSession(): void {
  const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
  const interview = repository.createInterview({
    discoveryId: discovery.id,
    title: 'Entrevista con resolución en vivo'
  })
  repository.updateInterview(interview.id, {
    objectives: ['Objetivo cero', 'Objetivo uno'],
    scriptMarkdown: '# Guión de la entrevista'
  })

  const transcriptionSender = createSender()
  startTranscription(transcriptionSender.sender)
  connection = harness.dgInstances[0] as FakeConnection
  connection.opened = true
  connection.isOpen = true
  connection.callbacks.onOpen()

  const assistantSender = createSender()
  send = assistantSender.send
  startAssistant(assistantSender.sender, interview.id)
}

/**
 * Ejecuta UN análisis completo: avanza la ventana de 20 s si no es el
 * primero, inyecta 3 líneas finales y espera analyzing→active.
 */
async function analyze(overrides: Record<string, unknown> = {}): Promise<void> {
  analysisCount += 1
  const expectedCalls = analysisCount
  const eventsBefore = assistantEvents(send).length
  harness.create.mockResolvedValueOnce(sdkResponse(analysisPayload(overrides)))
  if (expectedCalls > 1) {
    vi.setSystemTime(BASE_TIME_MS + (expectedCalls - 1) * (MIN_INTERVAL_MS + 1000))
  }
  feedFinal()
  feedFinal()
  feedFinal()
  await vi.waitFor(() => expect(harness.create).toHaveBeenCalledTimes(expectedCalls))
  await vi.waitFor(() => {
    const events = assistantEvents(send)
    expect(events.length).toBeGreaterThanOrEqual(eventsBefore + 2)
    expect(events.at(-1)?.state).toBe('active')
  })
}

/** Texto plano del prompt de sistema (todos los bloques concatenados). */
function systemText(index: number): string {
  const blocks = createCall(index).system as Array<{ text: string }>
  return blocks.map((block) => block.text).join('\n')
}

const TOOL_QUESTION = '¿Cuánto pagasteis por la última herramienta que comprasteis?'
const TOOL_QUESTION_ASKED = '¿Y cuánto pagasteis por esa última herramienta que comprasteis?'

beforeEach(() => {
  vi.clearAllMocks()
  harness.dgInstances.length = 0
  lineCounter = 0
  analysisCount = 0
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(BASE_TIME_MS)
  initStore(mkdtempSync(join(tmpdir(), 'maurya-assistant-live-resolution-')))
  process.env['ANTHROPIC_API_KEY'] = 'sk-ant-test'
  process.env['DEEPGRAM_API_KEY'] = 'dg-test'
})

afterEach(() => {
  stopAssistant()
  resetTranscription()
  vi.useRealTimers()
  delete process.env['ANTHROPIC_API_KEY']
  delete process.env['DEEPGRAM_API_KEY']
})

describe('assistantService (resolución en vivo SPEC-038)', () => {
  describe('deterministic resolution on interviewer asking (mic)', () => {
    // SPEC-038 · AC-01 (la formulación por mic resuelve al instante sin LLM)
    it('removes a pending question immediately when a final mic line asks it, emitting the update without any LLM call', async () => {
      startSession()
      await analyze({ suggestedQuestion: TOOL_QUESTION })

      feedLine(0, TOOL_QUESTION_ASKED)

      const lastEvent = assistantEvents(send).at(-1)
      expect(lastEvent?.queue.pending).toEqual([])
      expect(lastEvent?.state).toBe('idle')
      // Sin llamada extra al LLM: solo el análisis que encoló la pregunta
      expect(harness.create).toHaveBeenCalledTimes(1)
    })

    // SPEC-038 · AC-02 (las ancladas nunca se auto-resuelven, tampoco por mic)
    it('keeps a pinned question intact when a final mic line asks it', async () => {
      startSession()
      await analyze({ suggestedQuestion: TOOL_QUESTION })
      setAssistantPinned(lastQueue().pending[0].id, true)

      feedLine(0, TOOL_QUESTION_ASKED)

      expect(lastQueue().pinned.map((item) => item.suggestedQuestion)).toEqual([TOOL_QUESTION])
      expect(pendingQuestions()).toEqual([])
    })

    // SPEC-038 · AC-03 (una línea del interlocutor no formula preguntas de la cola)
    it('keeps the pending question when a similar final line arrives on the system channel', async () => {
      startSession()
      await analyze({ suggestedQuestion: TOOL_QUESTION })

      feedLine(1, TOOL_QUESTION_ASKED)

      expect(pendingQuestions()).toEqual([TOOL_QUESTION])
    })

    // SPEC-038 · AC-04 (una línea mic de otro tema no resuelve nada)
    it('keeps the pending question when the final mic line targets another topic', async () => {
      startSession()
      await analyze({ suggestedQuestion: TOOL_QUESTION })

      feedLine(0, 'Vale, ¿y cómo organizáis el calendario del equipo cada semana?')

      expect(pendingQuestions()).toEqual([TOOL_QUESTION])
    })

    // SPEC-038 · AC-05 (una línea puede resolver varias pendientes a la vez)
    it('removes every pending question matched by the same final mic line', async () => {
      startSession()
      await analyze({ suggestedQuestion: '¿Cuánto pagasteis por la herramienta de citas?' })
      await analyze({ suggestedQuestion: '¿Quién decidió la compra de la herramienta?' })
      expect(pendingQuestions()).toHaveLength(2)

      feedLine(0, '¿Cuánto pagasteis por la herramienta de citas y quién decidió esa compra?')

      expect(pendingQuestions()).toEqual([])
    })

    // SPEC-038 · AC-06 (la línea que resuelve sigue contando como material nuevo)
    it('still counts the resolving mic line toward the analysis triggers without extra calls', async () => {
      startSession()
      await analyze({ suggestedQuestion: TOOL_QUESTION })

      feedLine(0, TOOL_QUESTION_ASKED) // resuelve y cuenta como línea nueva 1/3
      expect(harness.create).toHaveBeenCalledTimes(1)

      harness.create.mockResolvedValueOnce(
        sdkResponse(analysisPayload({ suggestedQuestion: '¿Qué pasó la última semana?' }))
      )
      vi.setSystemTime(BASE_TIME_MS + 10 * (MIN_INTERVAL_MS + 1000))
      feedFinal() // 2/3
      feedFinal() // 3/3 → dispara

      await vi.waitFor(() => expect(harness.create).toHaveBeenCalledTimes(2))
    })

    // SPEC-038 · AC-07 (las interim no resuelven: solo líneas finales)
    it('ignores interim mic lines even when they match a pending question', async () => {
      startSession()
      await analyze({ suggestedQuestion: TOOL_QUESTION })

      feedLine(0, TOOL_QUESTION_ASKED, false)

      expect(pendingQuestions()).toEqual([TOOL_QUESTION])
      expect(harness.create).toHaveBeenCalledTimes(1)
    })
  })

  describe('prompt first barrier', () => {
    // SPEC-038 · AC-08 (revisión una a una + respondidas sin formularse)
    it('instructs the model to review every queued question and mark answered ones even if never asked verbatim', async () => {
      startSession()
      await analyze()

      const text = systemText(0)
      expect(text).toContain('en CADA análisis revisa UNA A UNA las preguntas en cola')
      expect(text).toContain(
        'aunque la formulación difiera o la respuesta haya llegado sin que nadie hiciera la pregunta'
      )
    })

    // SPEC-038 · AC-09 (la Tarea pide primero revisar la cola y después la jugada)
    it('asks first for the queue review and then for the next move in the user task section', async () => {
      startSession()
      await analyze()

      expect(createCall(0).messages[0].content).toContain(
        '## Tarea\nPrimero revisa la cola de preguntas y marca en `resolvedQueueIndexes` las que el interlocutor ya haya respondido; después analiza la conversación y decide la siguiente jugada del entrevistador.'
      )
    })
  })

  describe('regression (SPEC-023/036/037 invariants)', () => {
    // SPEC-038 · AC-10 (prefijo cacheado byte-idéntico entre llamadas)
    it('keeps the system blocks byte-identical across analyses after the live-resolution change', async () => {
      startSession()
      await analyze({ suggestedQuestion: '¿Pregunta sobre herramientas de agenda?' })
      await analyze({ suggestedQuestion: '¿Pregunta sobre presupuesto anual disponible?' })

      expect(JSON.stringify(createCall(1).system)).toBe(JSON.stringify(createCall(0).system))
    })

    // SPEC-038 · AC-11 (resolvedQueueIndexes del análisis sigue resolviendo por id)
    it('still resolves pending questions marked by the analysis through snapshot indexes', async () => {
      startSession()
      await analyze({ suggestedQuestion: '¿Pregunta sobre herramientas de agenda?' })
      await analyze({ suggestedQuestion: '¿Pregunta sobre presupuesto anual disponible?' })

      // Snapshot en el 3er análisis: [presupuesto (0), herramientas (1)]
      await analyze({
        suggestedQuestion: '¿Pregunta sobre decisiones internas del equipo?',
        resolvedQueueIndexes: [1]
      })

      expect(pendingQuestions()).toEqual([
        '¿Pregunta sobre decisiones internas del equipo?',
        '¿Pregunta sobre presupuesto anual disponible?'
      ])
    })

    // SPEC-038 · AC-12 (un índice anclado devuelto por el análisis se ignora)
    it('ignores an analysis-resolved index that points to a pinned question', async () => {
      startSession()
      await analyze({ suggestedQuestion: '¿Pregunta sobre herramientas de agenda?' })
      setAssistantPinned(lastQueue().pending[0].id, true)

      await analyze({
        suggestedQuestion: '¿Pregunta sobre presupuesto anual disponible?',
        resolvedQueueIndexes: [0]
      })

      expect(lastQueue().pinned.map((item) => item.suggestedQuestion)).toEqual([
        '¿Pregunta sobre herramientas de agenda?'
      ])
      expect(pendingQuestions()).toEqual(['¿Pregunta sobre presupuesto anual disponible?'])
    })

    // SPEC-038 · AC-13 (la resolución por formulación no toca suggestionCount)
    it('keeps suggestionCount counting only accepted candidates after a live resolution', async () => {
      startSession()
      await analyze({ suggestedQuestion: TOOL_QUESTION })

      feedLine(0, TOOL_QUESTION_ASKED)

      expect(stopAssistant()?.suggestionCount).toBe(1)
    })
  })
})
