// @vitest-environment node
/**
 * SPEC-024-iter-1: sello ad-hoc real del bundle — hook afterPack de
 * electron-builder (build/afterPack.js, CommonJS) que firma el .app con
 * entitlements y verifica el sello ANTES de generar los artefactos.
 * Generated by QA Dev agent.
 *
 * child_process va mockeado (vi.mock aplica también al require del CJS
 * inlinado por vite-node): aquí se fija la ORQUESTACIÓN del hook (guard de
 * plataforma, ruta del .app, orden firmar→verificar, propagación del fallo);
 * el sello REAL del bundle (codesign sobre el .app generado) es la
 * verificación del orquestador (MANUAL en el map, ya en curso).
 */
import { readFileSync } from 'fs'
import { join } from 'path'
import { beforeEach, describe, expect, it, vi } from 'vitest'
// Hook CommonJS de electron-builder (build/afterPack.js, sin declaración de
// tipos — TS lo resuelve como any con noImplicitAny:false); se tipa
// localmente con AfterPackHook
import afterPackUntyped from '../../../build/afterPack.js'

const harness = vi.hoisted(() => ({
  execFileSync: vi.fn()
}))

vi.mock('child_process', () => ({ execFileSync: harness.execFileSync }))
vi.mock('node:child_process', () => ({ execFileSync: harness.execFileSync }))

/** Firma del hook (contrato afterPack de electron-builder, campos usados). */
type AfterPackHook = (context: {
  electronPlatformName: string
  appOutDir?: string
  packager?: { appInfo: { productFilename: string } }
}) => void

const afterPack = afterPackUntyped as AfterPackHook

const ROOT = process.cwd()

function darwinContext(): Parameters<AfterPackHook>[0] {
  return {
    electronPlatformName: 'darwin',
    appOutDir: '/tmp/maurya-dist/mac-arm64',
    packager: { appInfo: { productFilename: 'Maurya' } }
  }
}

beforeEach(() => {
  vi.clearAllMocks()
  vi.spyOn(console, 'log').mockImplementation(() => undefined)
})

describe('afterPack hook (SPEC-024-iter-1)', () => {
  // SPEC-024-iter-1 · registro del hook (línea ACTIVA del yml, no comentario)
  it('registers build/afterPack.js as the active afterPack hook in electron-builder.yml', () => {
    const activeLines = readFileSync(join(ROOT, 'electron-builder.yml'), 'utf8')
      .split(/\r?\n/)
      .filter((line) => !line.trim().startsWith('#'))
    expect(activeLines).toContain('afterPack: build/afterPack.js')
  })

  // SPEC-024-iter-1 · forma del hook (CommonJS cargable por electron-builder)
  it('ships build/afterPack.js as a loadable CommonJS module exporting a function', () => {
    expect(typeof afterPack).toBe('function')
  })

  // SPEC-024-iter-1 · guard de plataforma (no-op fuera de macOS)
  it('is a no-op outside darwin: never invokes codesign and never throws', () => {
    // Contexto mínimo A PROPÓSITO (sin appOutDir/packager): si el guard no
    // cortara antes, la construcción de la ruta lanzaría
    expect(() => afterPack({ electronPlatformName: 'win32' })).not.toThrow()
    expect(() => afterPack({ electronPlatformName: 'linux' })).not.toThrow()
    expect(harness.execFileSync).not.toHaveBeenCalled()
  })

  // SPEC-024-iter-1 · sello ad-hoc con entitlements + verificación, en orden
  it('signs <appOutDir>/<productFilename>.app ad-hoc with the repo entitlements and then verifies the seal', () => {
    afterPack(darwinContext())

    expect(harness.execFileSync).toHaveBeenCalledTimes(2)
    // 1º: firma ad-hoc (--sign -) forzada y profunda con los entitlements del repo
    expect(harness.execFileSync).toHaveBeenNthCalledWith(
      1,
      'codesign',
      [
        '--force',
        '--deep',
        '--sign',
        '-',
        '--entitlements',
        expect.stringMatching(/build\/entitlements\.mac\.plist$/),
        '/tmp/maurya-dist/mac-arm64/Maurya.app'
      ],
      { stdio: 'inherit' }
    )
    // 2º: verificación estricta del sello sobre el mismo .app
    expect(harness.execFileSync).toHaveBeenNthCalledWith(
      2,
      'codesign',
      ['--verify', '--deep', '--strict', '/tmp/maurya-dist/mac-arm64/Maurya.app'],
      { stdio: 'inherit' }
    )
  })

  // SPEC-024-iter-1 · el fallo de codesign deja el build en rojo (lanza)
  it('propagates a codesign failure so the build goes red instead of packaging an unsealed bundle', () => {
    harness.execFileSync.mockImplementationOnce(() => {
      throw new Error('codesign: falló la firma')
    })

    expect(() => afterPack(darwinContext())).toThrow('codesign: falló la firma')
    // Falla la firma → la verificación ya no se intenta
    expect(harness.execFileSync).toHaveBeenCalledTimes(1)
  })
})
