// @vitest-environment node
/**
 * SPEC-024: empaquetado macOS y hardening final — entitlements listos para
 * firma real, camino a Developer ID documentado sin activar, versión 1.0.0 y
 * categoría de app en extendInfo.
 * Generated by QA Dev agent.
 *
 * Los archivos de configuración del repo son las fixtures (fs + texto, misma
 * convención que tests/unit/packaging/packagingConfig.test.ts de SPEC-005:
 * config estable verificada con substrings/regex, sin parser YAML). La
 * verificación del bundle REAL (build, plutil, codesign, humo) la ejecuta el
 * orquestador tras esta QA — MANUAL en el map.
 */
import { readFileSync } from 'fs'
import { join } from 'path'
import { describe, expect, it } from 'vitest'

const ROOT = process.cwd()

function readText(relativePath: string): string {
  return readFileSync(join(ROOT, relativePath), 'utf8')
}

/**
 * Extrae el bloque anidado bajo una clave YAML (líneas siguientes con más
 * indentación que la clave), sin parser: suficiente para config estable.
 * (Convención de packagingConfig.test.ts, SPEC-005.)
 */
function extractYamlBlock(yml: string, key: string): string {
  const lines = yml.split(/\r?\n/)
  const startIndex = lines.findIndex((line) => line.trim() === `${key}:`)
  if (startIndex === -1) {
    throw new Error(`No se encontró la clave YAML "${key}:"`)
  }
  const keyIndent = lines[startIndex].length - lines[startIndex].trimStart().length
  const block: string[] = []
  for (const line of lines.slice(startIndex + 1)) {
    const indent = line.length - line.trimStart().length
    if (line.trim() !== '' && indent <= keyIndent) {
      break
    }
    block.push(line)
  }
  return block.join('\n')
}

/** Líneas ACTIVAS (no comentario) del yml: lo configurado de verdad. */
function activeYamlLines(yml: string): string {
  return yml
    .split(/\r?\n/)
    .filter((line) => !line.trim().startsWith('#'))
    .join('\n')
}

/** Líneas de COMENTARIO del yml: la documentación del camino a firma real. */
function commentYamlLines(yml: string): string {
  return yml
    .split(/\r?\n/)
    .filter((line) => line.trim().startsWith('#'))
    .join('\n')
}

describe('packaging hardening (SPEC-024)', () => {
  describe('entitlements for real signing', () => {
    // SPEC-024 · AC-01
    it('declares device.audio-input and keeps allow-jit in build/entitlements.mac.plist', () => {
      const plist = readText('build/entitlements.mac.plist')

      // Micrófono: exigido por el hardened runtime cuando haya firma real
      expect(plist).toMatch(/<key>com\.apple\.security\.device\.audio-input<\/key>\s*<true\/>/)
      // Electron necesita JIT: se conserva
      expect(plist).toMatch(/<key>com\.apple\.security\.cs\.allow-jit<\/key>\s*<true\/>/)
    })

    // SPEC-024 · AC-02
    it('removes the scaffold entitlements that weaken the hardened runtime', () => {
      const plist = readText('build/entitlements.mac.plist')

      expect(plist).not.toContain('com.apple.security.cs.allow-unsigned-executable-memory')
      expect(plist).not.toContain('com.apple.security.cs.allow-dyld-environment-variables')
    })
  })

  describe('signing path documentation', () => {
    // SPEC-024 · AC-03
    it('keeps ad-hoc signing active while documenting the Developer ID / notarization path as comments', () => {
      const yml = readText('electron-builder.yml')
      const active = activeYamlLines(yml)
      const comments = commentYamlLines(yml)

      // La configuración ACTIVA sigue siendo ad-hoc
      expect(active).toContain('identity: null')
      expect(active).toContain('notarize: false')
      // La activación real vive SOLO en comentarios (documentada, no activa)
      expect(active).not.toContain('notarize: true')
      expect(active).not.toContain('Developer ID')
      expect(comments).toContain('Developer ID Application')
      expect(comments).toContain('notarize: true')
      // Variables de entorno del camino a notarización
      expect(comments).toContain('APPLE_ID')
      expect(comments).toContain('APPLE_APP_SPECIFIC_PASSWORD')
      expect(comments).toContain('APPLE_TEAM_ID')
    })
  })

  describe('MVP version and metadata', () => {
    // SPEC-024 · AC-04 — el literal 1.0.0 quedó derogado por decisión humana
    // (commit c913135 «chore: bump versión a 0.2.0 para empaquetado», 2026-07):
    // el contrato vigente es semver limpio + artefacto derivado de la versión.
    it('keeps a clean semver version in package.json deriving the artifact name (1.0.0 derogated by human bump)', () => {
      const packageJson = JSON.parse(readText('package.json')) as { version?: string }
      expect(packageJson.version).toMatch(/^\d+\.\d+\.\d+$/)

      // El nombre de artefacto deriva de productName + version (sin literal viejo)
      const yml = readText('electron-builder.yml')
      expect(yml).toContain('artifactName: ${productName}-${version}.${ext}')
      expect(yml).not.toContain('0.1.0')
    })

    // SPEC-024 · AC-05
    it('declares LSApplicationCategoryType in the extendInfo MAP keeping both TCC descriptions intact', () => {
      const yml = readText('electron-builder.yml')
      const extendInfo = extractYamlBlock(yml, 'extendInfo')

      // Categoría de la app, como entrada de MAP (no de lista — nota SPEC-005)
      expect(extendInfo).toMatch(
        /^\s+LSApplicationCategoryType: public\.app-category\.productivity$/m
      )
      expect(extendInfo).not.toMatch(/^\s*-\s*LSApplicationCategoryType/m)
      // Las descripciones TCC existentes no cambian
      expect(extendInfo).toMatch(/^\s+NSMicrophoneUsageDescription:/m)
      expect(extendInfo).toMatch(/^\s+NSAudioCaptureUsageDescription:/m)
      expect(extendInfo).toMatch(/micrófono/i)
      expect(extendInfo).toMatch(/audio del sistema/i)
    })
  })
})
