/**
 * SPEC-039: diálogo «Preguntas descartadas» al finalizar la grabación —
 * apertura al llegar el StopResult con ≥1 pregunta descartada en
 * questionOutcomes (integración real vía InterviewDetailPage →
 * RecordingSectionView), guardado de motivos → setInterviewDiscardReasons con
 * los índices REALES del array completo + Toast «Motivos guardados», «Omitir»
 * cierra sin llamada y sin descartadas el Dialog no se abre.
 * Generated by QA Dev agent.
 *
 * Arnés de RecordingSection (SPEC-015): servicios del spike mockeados +
 * bridge window.api; el flujo atraviesa el consentimiento (SPEC-019) y la
 * parada real («Detener» → recording.stop → result con la Interview).
 */
import { act, render, screen, waitFor, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import {
  acquireMicrophoneStream,
  acquireSystemAudioStream,
  listAudioInputDevices
} from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { StopResult } from '@/types/audio'
import type { Company, Interview, InterviewQuestionOutcome } from '@/types/domain'
import { createFakeAudioStream } from '../../helpers/fakeMediaStream'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = vi.fn()
    stop = vi.fn()
    getLevels = vi.fn(() => ({ microphone: 0, system: 0 }))
    readonly durationSeconds = 0
    readonly samplesWritten = 0
  }
}))

let mockApi: MockApiHandle

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactIds: [],
    interviewGroupId: null,
    templateId: null,
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

const WAV_PATH = '/tmp/maurya-recordings/entrevista-i-1.wav'
const TRANSCRIPT_PATH = '/tmp/maurya-recordings/entrevista-i-1.transcript.json'

const DISCARDED_1 = '¿Cuándo fue la última vez que pasó?'
const ANSWERED_1 = '¿Quién decidió la compra de la herramienta?'
const DISCARDED_2 = '¿Cuánto pagasteis por la solución actual?'

/** Outcomes de la parada: descartadas en los índices REALES 0 y 2. */
const OUTCOMES: InterviewQuestionOutcome[] = [
  { question: DISCARDED_1, outcome: 'discarded' },
  { question: ANSWERED_1, outcome: 'answered' },
  { question: DISCARDED_2, outcome: 'discarded' }
]

function stopResult(outcomes: InterviewQuestionOutcome[] | null): StopResult {
  return {
    filePath: WAV_PATH,
    durationSeconds: 95,
    sizeBytes: 44 + 95 * 16000 * 4,
    sampleRate: 16000,
    channels: 2,
    transcriptPath: TRANSCRIPT_PATH,
    latency: null,
    interview: interview({
      wavPath: WAV_PATH,
      transcriptPath: TRANSCRIPT_PATH,
      status: 'recorded',
      questionOutcomes: outcomes
    })
  }
}

function renderDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route
            path="/discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
            element={<InterviewDetailPage />}
          />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

/** Arranca la grabación atravesando el aviso de consentimiento (SPEC-019). */
async function startRecording(user: ReturnType<typeof userEvent.setup>): Promise<void> {
  await user.click(await screen.findByRole('button', { name: 'Iniciar grabación' }))
  const consent = await screen.findByRole('alertdialog')
  await user.click(within(consent).getByRole('button', { name: 'Entendido, iniciar grabación' }))
  await screen.findByRole('button', { name: 'Detener' })
}

/** Graba y detiene: el StopResult configurado llega al renderer. */
async function recordAndStop(user: ReturnType<typeof userEvent.setup>): Promise<void> {
  await startRecording(user)
  await user.click(screen.getByRole('button', { name: 'Detener' }))
  expect((await screen.findAllByText('Grabación guardada')).length).toBeGreaterThanOrEqual(1)
}

beforeEach(() => {
  vi.clearAllMocks()
  window.localStorage.clear()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: interview() })
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  vi.mocked(acquireMicrophoneStream).mockResolvedValue(createFakeAudioStream().stream)
  vi.mocked(acquireSystemAudioStream).mockResolvedValue(createFakeAudioStream().stream)
  vi.mocked(mockApi.api.recording.stop).mockResolvedValue(stopResult(OUTCOMES))
})

describe('DiscardReasonsDialog (motivos al finalizar SPEC-039)', () => {
  // SPEC-039 · AC-16 (la parada con descartadas abre el Dialog con sus Textareas)
  it('opens the Preguntas descartadas dialog after stopping with each discarded question and an optional reason textarea', async () => {
    const user = userEvent.setup()
    renderDetail()

    await recordAndStop(user)

    const dialog = await screen.findByTestId('discard-reasons-dialog')
    expect(
      within(dialog).getByRole('heading', { name: 'Preguntas descartadas' })
    ).toBeInTheDocument()
    expect(
      within(dialog).getByText(
        'Deja constancia de por qué las descartaste; se tendrá en cuenta en la nota y en los objetivos.'
      )
    ).toBeInTheDocument()
    // Una entrada por DESCARTADA (las respondidas no piden motivo)
    expect(within(dialog).getByText(DISCARDED_1)).toBeInTheDocument()
    expect(within(dialog).getByText(DISCARDED_2)).toBeInTheDocument()
    expect(within(dialog).queryByText(ANSWERED_1)).not.toBeInTheDocument()
    const inputs = within(dialog).getAllByTestId('discard-reason-input')
    expect(inputs).toHaveLength(2)
    expect(inputs[0]).toHaveAttribute('placeholder', '¿Por qué la descartaste? (opcional)')
    expect(within(dialog).getByTestId('discard-reasons-save')).toHaveTextContent('Guardar motivos')
    expect(within(dialog).getByTestId('discard-reasons-skip')).toHaveTextContent('Omitir')
  })

  // SPEC-039 · AC-17 (Guardar motivos → setInterviewDiscardReasons + Toast)
  it('persists the written reasons with their real questionOutcomes indexes and shows the Motivos guardados toast on save', async () => {
    const user = userEvent.setup()
    const updated = interview({
      wavPath: WAV_PATH,
      transcriptPath: TRANSCRIPT_PATH,
      status: 'recorded',
      questionOutcomes: [
        { question: DISCARDED_1, outcome: 'discarded', reason: 'Ya la respondió antes' },
        { question: ANSWERED_1, outcome: 'answered' },
        { question: DISCARDED_2, outcome: 'discarded', reason: 'Se nos acabó el tiempo' }
      ]
    })
    vi.mocked(mockApi.api.db.setInterviewDiscardReasons).mockResolvedValue({
      ok: true,
      data: updated
    })
    renderDetail()
    await recordAndStop(user)
    const dialog = await screen.findByTestId('discard-reasons-dialog')
    const inputs = within(dialog).getAllByTestId('discard-reason-input')

    await user.type(inputs[0], 'Ya la respondió antes')
    await user.type(inputs[1], 'Se nos acabó el tiempo')
    await user.click(within(dialog).getByTestId('discard-reasons-save'))

    // Los índices apuntan al array questionOutcomes COMPLETO (0 y 2)
    expect(vi.mocked(mockApi.api.db.setInterviewDiscardReasons)).toHaveBeenCalledWith('i-1', [
      { index: 0, reason: 'Ya la respondió antes' },
      { index: 2, reason: 'Se nos acabó el tiempo' }
    ])
    expect((await screen.findAllByText('Motivos guardados')).length).toBeGreaterThanOrEqual(1)
    await waitFor(() =>
      expect(screen.queryByTestId('discard-reasons-dialog')).not.toBeInTheDocument()
    )
  })

  // SPEC-039 · AC-18 (Omitir cierra sin persistir ningún motivo)
  it('closes without persisting anything when Omitir is pressed', async () => {
    const user = userEvent.setup()
    renderDetail()
    await recordAndStop(user)
    const dialog = await screen.findByTestId('discard-reasons-dialog')

    await user.click(within(dialog).getByTestId('discard-reasons-skip'))

    await waitFor(() =>
      expect(screen.queryByTestId('discard-reasons-dialog')).not.toBeInTheDocument()
    )
    expect(vi.mocked(mockApi.api.db.setInterviewDiscardReasons)).not.toHaveBeenCalled()
    // Sin Toast de guardado
    expect(screen.queryByText('Motivos guardados')).not.toBeInTheDocument()
  })

  // SPEC-039 · AC-19 (parada sin descartadas: el Dialog no se abre)
  it('does not open the dialog when the stop result has no discarded questions', async () => {
    const user = userEvent.setup()
    // Solo respondidas: no hay motivos que pedir
    vi.mocked(mockApi.api.recording.stop).mockResolvedValue(
      stopResult([{ question: ANSWERED_1, outcome: 'answered' }])
    )
    renderDetail()

    await recordAndStop(user)

    // La apertura es diferida (setTimeout 0): drenar la cola antes de asertar
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 20))
    })
    expect(screen.queryByTestId('discard-reasons-dialog')).not.toBeInTheDocument()
    // El resto de la parada sigue intacto (resumen persistente)
    expect(await screen.findByText(WAV_PATH)).toBeInTheDocument()
  })
})
