/**
 * SPEC-049: Permisos no concedidos visibles — botón «Abrir Ajustes del Sistema».
 * Tests unitarios del componente OpenSettingsButton: única fuente de la lógica
 * de visibilidad (mismo criterio que PermissionBadges: estado distinto de
 * `granted`, incluido snapshot null) y de destino (un solo botón; primer
 * permiso no concedido, micrófono con prioridad).
 * Frontera de mocking: permissionsService (openPrivacySettings).
 * Generated by QA Dev agent.
 */
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { OpenSettingsButton } from '@/components/recording/OpenSettingsButton'
import { openPrivacySettings } from '@/services/permissionsService'
import type { PermissionsSnapshot } from '@/types/audio'

vi.mock('@/services/permissionsService', () => ({
  openPrivacySettings: vi.fn()
}))

const GRANTED: PermissionsSnapshot = { microphone: 'granted', systemAudio: 'granted' }
const MIC_DENIED: PermissionsSnapshot = { microphone: 'denied', systemAudio: 'granted' }
const SYSTEM_DENIED: PermissionsSnapshot = { microphone: 'granted', systemAudio: 'denied' }
const BOTH_DENIED: PermissionsSnapshot = { microphone: 'denied', systemAudio: 'denied' }

beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(openPrivacySettings).mockResolvedValue(undefined)
})

describe('OpenSettingsButton', () => {
  // SPEC-049 · AC-03
  it('hides the "Abrir Ajustes del Sistema" button when both permissions are granted', () => {
    render(<OpenSettingsButton permissions={GRANTED} />)

    expect(screen.queryByTestId('open-settings-button')).not.toBeInTheDocument()
    expect(
      screen.queryByRole('button', { name: 'Abrir Ajustes del Sistema' })
    ).not.toBeInTheDocument()
  })

  // SPEC-049 · AC-04
  it('opens the microphone Settings pane when the microphone permission is not granted', async () => {
    const user = userEvent.setup()
    render(<OpenSettingsButton permissions={MIC_DENIED} />)

    await user.click(screen.getByRole('button', { name: 'Abrir Ajustes del Sistema' }))

    expect(vi.mocked(openPrivacySettings)).toHaveBeenCalledWith('microphone')
  })

  // SPEC-049 · AC-05
  it('opens the system audio Settings pane when only the system audio permission is not granted', async () => {
    const user = userEvent.setup()
    render(<OpenSettingsButton permissions={SYSTEM_DENIED} />)

    await user.click(screen.getByRole('button', { name: 'Abrir Ajustes del Sistema' }))

    expect(vi.mocked(openPrivacySettings)).toHaveBeenCalledWith('systemAudio')
  })

  // SPEC-049 · AC-06
  it('opens the microphone Settings pane with priority when both permissions are not granted', async () => {
    const user = userEvent.setup()
    render(<OpenSettingsButton permissions={BOTH_DENIED} />)

    await user.click(screen.getByRole('button', { name: 'Abrir Ajustes del Sistema' }))

    // El micrófono tiene prioridad: es el primer paso del flujo de concesión
    expect(vi.mocked(openPrivacySettings)).toHaveBeenCalledWith('microphone')
    expect(vi.mocked(openPrivacySettings)).not.toHaveBeenCalledWith('systemAudio')
  })

  // SPEC-049 · AC-07
  it('shows the button while the permissions snapshot is still null, like the badges paint "No concedido"', () => {
    render(<OpenSettingsButton permissions={null} />)

    const button = screen.getByTestId('open-settings-button')
    expect(button).toHaveTextContent('Abrir Ajustes del Sistema')
  })

  // SPEC-049 · AC-08
  it('removes the button when the pending permission becomes granted after a snapshot refresh', () => {
    const { rerender } = render(<OpenSettingsButton permissions={SYSTEM_DENIED} />)
    expect(screen.getByTestId('open-settings-button')).toBeInTheDocument()

    // El snapshot refrescado llega con ambos permisos concedidos
    rerender(<OpenSettingsButton permissions={GRANTED} />)

    expect(screen.queryByTestId('open-settings-button')).not.toBeInTheDocument()
  })
})
