/**
 * SPEC-049: Permisos no concedidos visibles — botón «Abrir Ajustes del Sistema».
 * Criterio de visibilidad actualizado por SPEC-055-iter-2 (AC-01/AC-03): el
 * botón aparece solo con algún permiso en denegación dura (denied/restricted);
 * con permisos pendientes (not-determined o snapshot null) no hay fila de
 * Maurya en Ajustes que activar y el botón no se muestra. El destino se
 * mantiene (primer permiso denegado, micrófono con prioridad).
 * Frontera de mocking: permissionsService (openPrivacySettings).
 * Generated by QA Dev agent.
 */
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { OpenSettingsButton } from '@/components/recording/OpenSettingsButton'
import { openPrivacySettings } from '@/services/permissionsService'
import type { PermissionsSnapshot } from '@/types/audio'

vi.mock('@/services/permissionsService', () => ({
  openPrivacySettings: vi.fn()
}))

const GRANTED: PermissionsSnapshot = { microphone: 'granted', systemAudio: 'granted' }
const PENDING: PermissionsSnapshot = {
  microphone: 'not-determined',
  systemAudio: 'not-determined'
}
const MIC_DENIED: PermissionsSnapshot = { microphone: 'denied', systemAudio: 'granted' }
const SYSTEM_DENIED: PermissionsSnapshot = { microphone: 'granted', systemAudio: 'denied' }
const BOTH_DENIED: PermissionsSnapshot = { microphone: 'denied', systemAudio: 'restricted' }

beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(openPrivacySettings).mockResolvedValue(undefined)
})

describe('OpenSettingsButton', () => {
  // SPEC-049 · AC-03 (criterio SPEC-055-iter-2)
  it('hides the "Abrir Ajustes del Sistema" button when both permissions are granted', () => {
    render(<OpenSettingsButton permissions={GRANTED} />)

    expect(screen.queryByTestId('open-settings-button')).not.toBeInTheDocument()
    expect(
      screen.queryByRole('button', { name: 'Abrir Ajustes del Sistema' })
    ).not.toBeInTheDocument()
  })

  // SPEC-055-iter-2 · AC-01: pendiente ≠ denegado — sin botones correctivos
  it('hides the button while permissions are pending (not-determined) or the snapshot is still null', () => {
    const { unmount } = render(<OpenSettingsButton permissions={PENDING} />)
    expect(screen.queryByTestId('open-settings-button')).not.toBeInTheDocument()
    unmount()

    render(<OpenSettingsButton permissions={null} />)
    expect(screen.queryByTestId('open-settings-button')).not.toBeInTheDocument()
  })

  // SPEC-049 · AC-04 (criterio SPEC-055-iter-2 · AC-03)
  it('opens the microphone Settings pane when the microphone permission is denied', async () => {
    const user = userEvent.setup()
    render(<OpenSettingsButton permissions={MIC_DENIED} />)

    await user.click(screen.getByRole('button', { name: 'Abrir Ajustes del Sistema' }))

    expect(vi.mocked(openPrivacySettings)).toHaveBeenCalledWith('microphone')
  })

  // SPEC-049 · AC-05 (criterio SPEC-055-iter-2 · AC-03)
  it('opens the system audio Settings pane when only the system audio permission is denied', async () => {
    const user = userEvent.setup()
    render(<OpenSettingsButton permissions={SYSTEM_DENIED} />)

    await user.click(screen.getByRole('button', { name: 'Abrir Ajustes del Sistema' }))

    expect(vi.mocked(openPrivacySettings)).toHaveBeenCalledWith('systemAudio')
  })

  // SPEC-049 · AC-06: micrófono con prioridad (denied + restricted)
  it('opens the microphone Settings pane with priority when both permissions are denied', async () => {
    const user = userEvent.setup()
    render(<OpenSettingsButton permissions={BOTH_DENIED} />)

    await user.click(screen.getByRole('button', { name: 'Abrir Ajustes del Sistema' }))

    expect(vi.mocked(openPrivacySettings)).toHaveBeenCalledWith('microphone')
    expect(vi.mocked(openPrivacySettings)).not.toHaveBeenCalledWith('systemAudio')
  })

  // SPEC-049 · AC-08
  it('removes the button when the denied permission becomes granted after a snapshot refresh', () => {
    const { rerender } = render(<OpenSettingsButton permissions={SYSTEM_DENIED} />)
    expect(screen.getByTestId('open-settings-button')).toBeInTheDocument()

    // El snapshot refrescado llega con ambos permisos concedidos
    rerender(<OpenSettingsButton permissions={GRANTED} />)

    expect(screen.queryByTestId('open-settings-button')).not.toBeInTheDocument()
  })
})
