// @vitest-environment node
/**
 * SPEC-021: medición del coste de IA — módulo puro src/main/aiCost.ts
 * (tarifas, cálculo, redondeo del límite, extracción defensiva del usage y
 * registro best-effort que jamás lanza).
 * Generated by QA Dev agent.
 */
import { mkdtempSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import type Anthropic from '@anthropic-ai/sdk'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import {
  computeCostUsd,
  extractUsage,
  INPUT_USD_PER_MTOK,
  OUTPUT_USD_PER_MTOK,
  recordInterviewUsage,
  roundUpUsd
} from '../../../src/main/aiCost'
import * as repository from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  }
}))

/** Respuesta mínima del SDK con (o sin) bloque usage, para extractUsage. */
function sdkMessage(usage?: unknown): Anthropic.Message {
  return { usage } as unknown as Anthropic.Message
}

beforeEach(() => {
  initStore(mkdtempSync(join(tmpdir(), 'maurya-aicost-')))
})

afterEach(() => {
  vi.restoreAllMocks()
})

describe('aiCost', () => {
  // SPEC-021 · refuerzo de AC-01..AC-03 (tarifa única de claude-opus-4-8)
  it('computes the estimated cost with the claude-opus-4-8 rates ($5 input / $25 output per MTok)', () => {
    expect(INPUT_USD_PER_MTOK).toBe(5)
    expect(OUTPUT_USD_PER_MTOK).toBe(25)
    expect(computeCostUsd(1_000_000, 0)).toBe(5)
    expect(computeCostUsd(0, 1_000_000)).toBe(25)
    // 1000 in + 500 out → 0.005 + 0.0125 = 0.0175
    expect(computeCostUsd(1000, 500)).toBeCloseTo(0.0175, 10)
    expect(computeCostUsd(0, 0)).toBe(0)
  })

  // SPEC-021 · refuerzo de AC-11 (la comparación con el límite pausa ANTES de excederlo)
  it('rounds up to 2 decimals for the limit comparison', () => {
    expect(roundUpUsd(0.001)).toBe(0.01)
    expect(roundUpUsd(1.111)).toBe(1.12)
    expect(roundUpUsd(1.1)).toBe(1.1)
    expect(roundUpUsd(0)).toBe(0)
  })

  // SPEC-021 · AC-16 (extracción defensiva del bloque usage)
  it('extracts the token usage from the response and degrades to 0 tokens when the usage block is missing or malformed', () => {
    expect(extractUsage(sdkMessage({ input_tokens: 1200, output_tokens: 340 }))).toEqual({
      inputTokens: 1200,
      outputTokens: 340
    })
    // Sin bloque de uso (caso anómalo del SDK) → 0 tokens sin lanzar
    expect(extractUsage(sdkMessage(undefined))).toEqual({ inputTokens: 0, outputTokens: 0 })
    // Bloque malformado → cada campo degrada por separado
    expect(extractUsage(sdkMessage({ input_tokens: 'x', output_tokens: 7 }))).toEqual({
      inputTokens: 0,
      outputTokens: 7
    })
  })

  // SPEC-021 · AC-17 (best-effort: el fallo de medición se loguea y JAMÁS lanza)
  it('records the usage delta on the interview and never throws on failure, logging to console instead', () => {
    const discovery = repository.createDiscovery({ name: 'Vertical Sanidad' })
    const interview = repository.createInterview({
      discoveryId: discovery.id,
      title: 'Captura medida'
    })

    // Camino feliz: registra una llamada con su coste calculado
    recordInterviewUsage(interview.id, { inputTokens: 1000, outputTokens: 500 })
    expect(repository.getInterview(interview.id).aiUsage).toEqual({
      calls: 1,
      inputTokens: 1000,
      outputTokens: 500,
      estimatedCostUsd: computeCostUsd(1000, 500)
    })

    // `calls` explícito (volcado de una sesión completa del asistente)
    recordInterviewUsage(interview.id, { inputTokens: 100, outputTokens: 50, calls: 4 })
    expect(repository.getInterview(interview.id).aiUsage?.calls).toBe(5)

    // Fallo (entrevista inexistente): no lanza, loguea y no escribe nada
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => undefined)
    expect(() =>
      recordInterviewUsage('no-existe', { inputTokens: 10, outputTokens: 10 })
    ).not.toThrow()
    expect(consoleError).toHaveBeenCalledTimes(1)
    expect(repository.getInterview(interview.id).aiUsage?.calls).toBe(5)
  })
})
