// @vitest-environment node
/**
 * SPEC-021: coste de IA en el asistente proactivo — acumulación por análisis
 * exitoso, gate de límite DESPUÉS de los guards de SPEC-016, evento 'paused'
 * único con su límite, "Reanudar" desactiva el límite para la sesión y el
 * summary/transcript llevan el usage.
 * Generated by QA Dev agent.
 *
 * Mismo arnés que assistantService.test.ts (SPEC-016): SDK y Deepgram
 * mockeados, store/repository y transcriptionService REALES, fake timers solo
 * de Date. Las respuestas del SDK llevan aquí bloque usage configurable.
 */
import { mkdtempSync, readFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import type { WebContents } from 'electron'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { computeCostUsd } from '../../../src/main/aiCost'
import {
  MIN_INTERVAL_MS,
  resumeAssistantLimit,
  startAssistant,
  stopAssistant
} from '../../../src/main/assistantService'
import * as repository from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'
import type { DeepgramCallbacks } from '../../../src/main/deepgramService'
import {
  persistTranscript,
  resetTranscription,
  startTranscription
} from '../../../src/main/transcriptionService'
import type {
  AssistantSessionSummary,
  AssistantUpdateEvent
} from '../../../src/renderer/src/types/assistant'

const harness = vi.hoisted(() => {
  /** Jerarquía espejo de la del SDK: instanceof debe funcionar en mapSdkError. */
  class APIError extends Error {}
  class AuthenticationError extends APIError {}
  class RateLimitError extends APIError {}
  class APIConnectionError extends APIError {}
  return {
    create: vi.fn(),
    dgInstances: [] as unknown[],
    errors: { APIError, AuthenticationError, RateLimitError, APIConnectionError }
  }
})

vi.mock('@anthropic-ai/sdk', () => {
  class MockAnthropic {
    static APIError = harness.errors.APIError
    static AuthenticationError = harness.errors.AuthenticationError
    static RateLimitError = harness.errors.RateLimitError
    static APIConnectionError = harness.errors.APIConnectionError
    readonly messages = { create: harness.create }
  }
  return { default: MockAnthropic }
})

vi.mock('../../../src/main/deepgramService', () => ({
  DeepgramConnection: class {
    apiKey: string
    callbacks: DeepgramCallbacks
    opened = false
    isOpen = false
    sendAudio = vi.fn(() => true)
    sendKeepAlive = vi.fn()
    closeStream = vi.fn()
    terminate = vi.fn()

    constructor(apiKey: string, callbacks: DeepgramCallbacks) {
      this.apiKey = apiKey
      this.callbacks = callbacks
      harness.dgInstances.push(this)
    }
  },
  classifyConnectionFailure: vi.fn(() => Promise.resolve('other' as const))
}))

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

interface FakeConnection {
  callbacks: DeepgramCallbacks
  opened: boolean
  isOpen: boolean
}

/** Respuesta del SDK con bloque usage configurable (SPEC-021). */
function sdkResponse(payload: Record<string, unknown>, usage?: unknown): unknown {
  return {
    stop_reason: 'end_turn',
    usage,
    content: [
      { type: 'thinking', thinking: 'razonamiento' },
      { type: 'text', text: JSON.stringify(payload) }
    ]
  }
}

function analysisPayload(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    action: 'continue',
    suggestedQuestion: '¿Cuándo fue la última vez que pasó?',
    reason: 'Ya hay material concreto para avanzar',
    alarms: [],
    objectivesMet: [],
    ...overrides
  }
}

function createSender(): { sender: WebContents; send: ReturnType<typeof vi.fn> } {
  const send = vi.fn()
  const senderLike = {
    isDestroyed: (): boolean => false,
    send
  }
  return { sender: senderLike as unknown as WebContents, send }
}

function assistantEvents(send: ReturnType<typeof vi.fn>): AssistantUpdateEvent[] {
  return send.mock.calls
    .filter((call) => call[0] === 'assistant:update')
    .map((call) => call[1] as AssistantUpdateEvent)
}

const BASE_TIME_MS = 1_000_000_000

let send: ReturnType<typeof vi.fn>
let connection: FakeConnection
let interviewId = ''
let lineCounter = 0

/** Inyecta una línea final por la vía pública (transcripción real mockeada). */
function feedFinal(): void {
  lineCounter += 1
  connection.callbacks.onResult({
    channelIndex: lineCounter % 2,
    transcript: `Línea de conversación ${lineCounter}`,
    isFinal: true,
    startSeconds: lineCounter,
    durationSeconds: 1,
    speaker: 0
  })
}

async function waitForCreateCalls(count: number): Promise<void> {
  await vi.waitFor(() => expect(harness.create).toHaveBeenCalledTimes(count))
}

async function waitForActive(): Promise<void> {
  await vi.waitFor(() => {
    const events = assistantEvents(send)
    expect(events.at(-1)?.state).toBe('active')
  })
}

/**
 * Arranca sesión de transcripción + asistente sobre una CAPTURA sin empresa.
 * `persistedUsd` pre-carga aiUsage en la entrevista (base del gate de límite).
 */
function startSession(options: { limitUsd?: number | null; persistedUsd?: number } = {}): void {
  const { limitUsd, persistedUsd } = options
  const discovery = repository.createDiscovery({ name: 'Vertical Sanidad' })
  const interview = repository.createInterview({
    discoveryId: discovery.id,
    title: 'Captura medida'
  })
  interviewId = interview.id
  if (persistedUsd !== undefined) {
    repository.addInterviewAiUsage(interviewId, {
      calls: 1,
      inputTokens: 0,
      outputTokens: 0,
      estimatedCostUsd: persistedUsd
    })
  }
  if (limitUsd !== undefined) {
    repository.setAiCostSettings({ limitUsd })
  }

  const transcriptionSender = createSender()
  startTranscription(transcriptionSender.sender)
  connection = harness.dgInstances[0] as FakeConnection
  connection.opened = true
  connection.isOpen = true
  connection.callbacks.onOpen()

  const assistantSender = createSender()
  send = assistantSender.send
  startAssistant(assistantSender.sender, interviewId)
}

beforeEach(() => {
  vi.clearAllMocks()
  harness.dgInstances.length = 0
  lineCounter = 0
  vi.useFakeTimers({ toFake: ['Date'] })
  vi.setSystemTime(BASE_TIME_MS)
  initStore(mkdtempSync(join(tmpdir(), 'maurya-assistant-aicost-')))
  process.env['ANTHROPIC_API_KEY'] = 'sk-ant-test'
  process.env['DEEPGRAM_API_KEY'] = 'dg-test'
})

afterEach(() => {
  stopAssistant()
  resetTranscription()
  vi.useRealTimers()
  delete process.env['ANTHROPIC_API_KEY']
  delete process.env['DEEPGRAM_API_KEY']
})

describe('assistantService (coste de IA SPEC-021)', () => {
  // SPEC-021 · AC-03 (acumulación por análisis + summary + transcript.json)
  it('accumulates the usage of each successful analysis in the session, returns it in the stop summary and persists it in the transcript assistant block', async () => {
    harness.create.mockResolvedValue(
      sdkResponse(analysisPayload(), { input_tokens: 1000, output_tokens: 500 })
    )
    startSession()

    feedFinal()
    feedFinal()
    feedFinal()
    await waitForCreateCalls(1)
    await waitForActive()
    // El evento 'active' lleva el acumulado de la sesión tras cada análisis
    expect(assistantEvents(send).at(-1)?.usage).toEqual({
      calls: 1,
      inputTokens: 1000,
      outputTokens: 500,
      estimatedCostUsd: computeCostUsd(1000, 500)
    })

    vi.setSystemTime(BASE_TIME_MS + MIN_INTERVAL_MS + 1000)
    feedFinal()
    feedFinal()
    feedFinal()
    await waitForCreateCalls(2)
    await vi.waitFor(() => {
      expect(assistantEvents(send).at(-1)?.usage?.calls).toBe(2)
    })

    const summary = stopAssistant()
    expect(summary?.usage).toEqual({
      calls: 2,
      inputTokens: 2000,
      outputTokens: 1000,
      estimatedCostUsd: computeCostUsd(2000, 1000)
    })

    // El bloque assistant del transcript.json registra el total de la sesión
    const dir = mkdtempSync(join(tmpdir(), 'maurya-aicost-transcript-'))
    const { transcriptPath } = persistTranscript(join(dir, 'captura.wav'), summary)
    if (transcriptPath === null) {
      throw new Error('persistTranscript devolvió null con líneas finales recibidas')
    }
    const persisted = JSON.parse(readFileSync(transcriptPath, 'utf8')) as {
      assistant: AssistantSessionSummary | null
    }
    expect(persisted.assistant?.usage).toEqual(summary?.usage)
  })

  // SPEC-021 · AC-04 (asistente: un análisis fallido no acumula nada)
  it('does not accumulate usage when the analysis call fails', async () => {
    harness.create.mockRejectedValueOnce(
      new harness.errors.APIConnectionError('sin conexión con la API')
    )
    startSession()

    feedFinal()
    feedFinal()
    feedFinal()
    await waitForCreateCalls(1)
    await vi.waitFor(() => {
      expect(assistantEvents(send).at(-1)?.state).toBe('error')
    })

    // El evento de error no lleva usage (0 análisis exitosos) y el summary va a ceros
    expect(assistantEvents(send).at(-1)?.usage).toBeUndefined()
    expect(stopAssistant()?.usage).toEqual({
      calls: 0,
      inputTokens: 0,
      outputTokens: 0,
      estimatedCostUsd: 0
    })
  })

  // SPEC-021 · AC-11 (main: gate tras los guards de SPEC-016 + evento 'paused' único)
  it('pauses the assistant when persisted+session cost reaches the limit, after the SPEC-016 triggers and emitting a single paused event', async () => {
    harness.create.mockResolvedValue(sdkResponse(analysisPayload()))
    // Acumulado persistido (0.02) ya por encima del límite (0.01)
    startSession({ limitUsd: 0.01, persistedUsd: 0.02 })

    // Los disparadores de SPEC-016 van PRIMERO: con 2 líneas ni analiza ni pausa
    feedFinal()
    feedFinal()
    expect(assistantEvents(send).some((event) => event.state === 'paused')).toBe(false)

    // Con material suficiente, el gate pausa SIN llamar al LLM
    feedFinal()
    await vi.waitFor(() => {
      expect(assistantEvents(send).at(-1)?.state).toBe('paused')
    })
    expect(harness.create).not.toHaveBeenCalled()
    // El evento lleva el límite que provocó la pausa (sin usage: 0 análisis)
    expect(assistantEvents(send).at(-1)).toEqual({
      state: 'paused',
      objectivesMet: [],
      pauseLimitUsd: 0.01
    })

    // Más material tras la pausa: sigue sin llamar y el evento 'paused' es ÚNICO
    vi.setSystemTime(BASE_TIME_MS + MIN_INTERVAL_MS * 2)
    feedFinal()
    feedFinal()
    feedFinal()
    expect(harness.create).not.toHaveBeenCalled()
    expect(assistantEvents(send).filter((event) => event.state === 'paused')).toHaveLength(1)
  })

  // SPEC-021 · AC-12 (main: "Reanudar" desactiva el límite para el resto de la sesión)
  it('resumes analyses after resumeAssistantLimit and never re-pauses in the same session even beyond the limit', async () => {
    // Cada análisis cuesta ~$0.30 (10k in + 10k out): supera el límite de sobra
    harness.create.mockResolvedValue(
      sdkResponse(analysisPayload(), { input_tokens: 10_000, output_tokens: 10_000 })
    )
    startSession({ limitUsd: 0.01, persistedUsd: 0.02 })
    feedFinal()
    feedFinal()
    feedFinal()
    await vi.waitFor(() => {
      expect(assistantEvents(send).at(-1)?.state).toBe('paused')
    })

    const eventsBeforeResume = assistantEvents(send).length
    resumeAssistantLimit()

    // Vuelve del estado pausado (sin sugerencia previa → idle) y analiza
    expect(assistantEvents(send)[eventsBeforeResume]?.state).toBe('idle')
    await waitForCreateCalls(1)
    await waitForActive()

    // Con el coste de sesión ya MUY por encima del límite, no vuelve a pausar
    vi.setSystemTime(BASE_TIME_MS + MIN_INTERVAL_MS + 1000)
    feedFinal()
    feedFinal()
    feedFinal()
    await waitForCreateCalls(2)
    expect(assistantEvents(send).filter((event) => event.state === 'paused')).toHaveLength(1)
  })

  // SPEC-021 · AC-15 (sin límite configurado: nunca pausa y la medición funciona)
  it('never pauses by cost without a configured limit while the measurement keeps working', async () => {
    harness.create.mockResolvedValue(
      sdkResponse(analysisPayload(), { input_tokens: 100_000, output_tokens: 100_000 })
    )
    // Sin límite (default) y con gasto persistido previo alto
    startSession({ persistedUsd: 5 })

    feedFinal()
    feedFinal()
    feedFinal()
    await waitForCreateCalls(1)
    await waitForActive()

    expect(assistantEvents(send).some((event) => event.state === 'paused')).toBe(false)
    expect(assistantEvents(send).at(-1)?.usage).toEqual({
      calls: 1,
      inputTokens: 100_000,
      outputTokens: 100_000,
      estimatedCostUsd: computeCostUsd(100_000, 100_000)
    })
  })
})
