/**
 * SPEC-021: segmento de coste de IA en la cabecera del detalle (compartido
 * por InterviewDetailPage y CaptureDetailPage vía AiCostInline).
 * Generated by QA Dev agent.
 *
 * Mocks del spike (las páginas montan RecordingSection) + bridge window.api.
 * Nota de resolución del plan (Riesgo 1): sin aiUsage o a cero se muestra el
 * texto muted "Sin datos de coste" — mandan los ACs sobre el wireframe — y
 * jamás un importe "~$0.00".
 */
import { render, screen, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { CaptureDetailPage } from '@/pages/CaptureDetailPage'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import { listAudioInputDevices } from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { AiUsage, Company, Discovery, Interview } from '@/types/domain'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = vi.fn()
    stop = vi.fn()
    getLevels = vi.fn()
  }
}))

let mockApi: MockApiHandle

const DISCOVERY: Discovery = {
  id: 'd-1',
  name: 'Vertical Sanidad',
  createdAt: '2026-07-01T09:00:00.000Z',
  updatedAt: '2026-07-01T09:00:00.000Z'
}

const COMPANY: Company = {
  id: 'c-1',
  discoveryId: 'd-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

/** Desglose del Tooltip: 6 llamadas, 12.3k in, 2.1k out → coste 0.34. */
const USAGE: AiUsage = {
  calls: 6,
  inputTokens: 12_345,
  outputTokens: 2_100,
  estimatedCostUsd: 0.34
}

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactId: null,
    templateId: null,
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

function setInterview(value: Interview): void {
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: value })
}

function renderInterviewDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route
            path="/discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
            element={<InterviewDetailPage />}
          />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

function renderCaptureDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/captures/i-1']}>
        <Routes>
          <Route path="/captures/:id" element={<CaptureDetailPage />} />
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

beforeEach(() => {
  vi.clearAllMocks()
  mockApi = installMockApi()
  setInterview(interview())
  vi.mocked(mockApi.api.db.getDiscovery).mockResolvedValue({ ok: true, data: DISCOVERY })
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
})

describe('detail header AI cost (SPEC-021)', () => {
  // SPEC-021 · AC-07 (InterviewDetailPage: importe + Tooltip con el desglose)
  it('shows "IA ~$0.34" in the interview header refs row with a tooltip breaking down calls and tokens', async () => {
    setInterview(interview({ aiUsage: USAGE }))
    const user = userEvent.setup()
    renderInterviewDetail()

    const segment = await screen.findByTestId('interview-ai-cost')
    expect(segment).toHaveTextContent('IA ~$0.34')

    await user.hover(segment)
    const breakdown = await screen.findAllByText(
      '6 llamadas · 12.3k tokens entrada · 2.1k tokens salida'
    )
    expect(breakdown.length).toBeGreaterThanOrEqual(1)
  })

  // SPEC-021 · AC-07 (refuerzo: CaptureDetailPage comparte la cabecera con coste)
  it('shows the same cost segment in the capture detail header', async () => {
    setInterview(interview({ companyId: null, title: 'Captura medida', aiUsage: USAGE }))
    renderCaptureDetail()

    await screen.findByRole('heading', { level: 1, name: 'Captura medida' })
    expect(screen.getByTestId('interview-ai-cost')).toHaveTextContent('IA ~$0.34')
  })

  // SPEC-021 · AC-05 (entrevista anterior a la spec, sin campo aiUsage)
  it('shows "Sin datos de coste" without errors for a pre-spec interview with no aiUsage field', async () => {
    setInterview(interview())
    renderInterviewDetail()

    expect(
      await screen.findByRole('heading', { level: 1, name: 'Discovery con Acme' })
    ).toBeInTheDocument()
    expect(screen.getByText('Sin datos de coste')).toBeInTheDocument()
    expect(screen.queryByTestId('interview-ai-cost')).not.toBeInTheDocument()
  })

  // SPEC-021 · AC-08 (aiUsage a cero: sin "~$0.00" ruidoso)
  it('renders no amount at all when aiUsage exists but is at zero', async () => {
    setInterview(
      interview({
        aiUsage: { calls: 0, inputTokens: 0, outputTokens: 0, estimatedCostUsd: 0 }
      })
    )
    renderInterviewDetail()

    await screen.findByRole('heading', { level: 1, name: 'Discovery con Acme' })
    expect(screen.queryByTestId('interview-ai-cost')).not.toBeInTheDocument()
    expect(screen.queryByText(/~\$/)).not.toBeInTheDocument()
    expect(screen.getByText('Sin datos de coste')).toBeInTheDocument()
  })
})
