// @vitest-environment node
/**
 * SPEC-021: medición del coste en las generaciones manuales (guión y nota) —
 * registro tras parseo válido, fallo del LLM sin acumular, generación no
 * bloqueada por el límite y respuesta sin bloque usage.
 * Generated by QA Dev agent.
 *
 * Mismo arnés que llmService/noteService (SDK de Anthropic mockeado con
 * clases de error espejo; store/repository REALES en directorio temporal).
 */
import { mkdtempSync, writeFileSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { computeCostUsd } from '../../../src/main/aiCost'
import * as repository from '../../../src/main/db/repository'
import { initStore } from '../../../src/main/db/store'
import { generateInterviewScript, LlmOperationError } from '../../../src/main/llmService'
import { generateInterviewNote } from '../../../src/main/noteService'
import type { Interview } from '../../../src/renderer/src/types/domain'

const harness = vi.hoisted(() => {
  /** Jerarquía espejo de la del SDK: instanceof debe funcionar en mapSdkError. */
  class APIError extends Error {}
  class AuthenticationError extends APIError {}
  class RateLimitError extends APIError {}
  class APIConnectionError extends APIError {}
  return {
    create: vi.fn(),
    showSaveDialog: vi.fn(),
    errors: { APIError, AuthenticationError, RateLimitError, APIConnectionError }
  }
})

vi.mock('@anthropic-ai/sdk', () => {
  class MockAnthropic {
    static APIError = harness.errors.APIError
    static AuthenticationError = harness.errors.AuthenticationError
    static RateLimitError = harness.errors.RateLimitError
    static APIConnectionError = harness.errors.APIConnectionError
    readonly messages = { create: harness.create }
  }
  return { default: MockAnthropic }
})

vi.mock('electron', () => ({
  app: {
    getPath: (): string => {
      throw new Error('app.getPath no debe usarse en tests: initStore recibe baseDir inyectado')
    }
  },
  dialog: {
    showSaveDialog: harness.showSaveDialog
  },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

/**
 * Respuesta del SDK con bloque usage configurable (SPEC-021: los tokens se
 * leen de response.usage; `usage: undefined` simula el caso anómalo sin bloque).
 */
function sdkResponse(payload: Record<string, unknown>, usage?: unknown): unknown {
  return {
    stop_reason: 'end_turn',
    usage,
    content: [
      { type: 'thinking', thinking: 'razonamiento' },
      { type: 'text', text: JSON.stringify(payload) }
    ]
  }
}

const SCRIPT_JSON = {
  scriptMarkdown: '# Guión adaptado',
  objectives: ['Objetivo uno', 'Objetivo dos', 'Objetivo tres']
}

const NOTE_JSON = {
  sections: [{ title: 'Dolores', contentMarkdown: 'Registro manual detectado.' }]
}

interface Seeded {
  interview: Interview
  noteTemplateId: string
}

/** Discovery + captura con template de guión, note-template y transcript real. */
function seedInterview(): Seeded {
  const discovery = repository.createDiscovery({ name: 'Vertical Sanidad' })
  const template = repository.createInterviewTemplate({
    name: 'Entrevista de problema',
    blocks: [{ title: 'Contexto', questions: [{ text: '¿Quién lleva el regulatorio?' }] }]
  })
  const noteTemplate = repository.createNoteTemplate({
    name: 'Notas discovery',
    sections: [{ title: 'Dolores', description: 'Problemas detectados' }]
  })
  const interview = repository.createInterview({
    discoveryId: discovery.id,
    title: 'Captura medida',
    templateId: template.id
  })
  const dir = mkdtempSync(join(tmpdir(), 'maurya-gen-transcript-'))
  const transcriptPath = join(dir, 'captura.transcript.json')
  writeFileSync(
    transcriptPath,
    JSON.stringify({
      lines: [
        {
          channel: 'mic',
          speaker: 0,
          text: '¿Cómo gestionáis hoy el registro?',
          startMs: 0,
          endMs: 1000,
          receivedAtMs: 1100
        }
      ],
      latency: null,
      assistant: null,
      consent: null
    })
  )
  repository.updateInterview(interview.id, { transcriptPath, status: 'recorded' })
  return { interview: repository.getInterview(interview.id), noteTemplateId: noteTemplate.id }
}

let dataDir = ''

beforeEach(() => {
  vi.clearAllMocks()
  dataDir = mkdtempSync(join(tmpdir(), 'maurya-gen-aicost-'))
  initStore(dataDir)
  process.env['ANTHROPIC_API_KEY'] = 'sk-ant-test'
})

afterEach(() => {
  delete process.env['ANTHROPIC_API_KEY']
})

describe('generation cost measurement (SPEC-021)', () => {
  // SPEC-021 · AC-01
  it('records the script generation tokens and persists the interview aiUsage accumulate', async () => {
    const { interview } = seedInterview()
    harness.create.mockResolvedValue(
      sdkResponse(SCRIPT_JSON, { input_tokens: 1000, output_tokens: 500 })
    )

    const updated = await generateInterviewScript(interview.id)

    // La Interview devuelta YA incluye el aiUsage (la cabecera refresca sin
    // recargar), con el desglose byTask de la revisión de coste 2026-07
    expect(updated.aiUsage).toMatchObject({
      calls: 1,
      inputTokens: 1000,
      outputTokens: 500,
      estimatedCostUsd: computeCostUsd('claude-opus-4-8', 1000, 500)
    })
    expect(updated.aiUsage?.byTask?.scriptGeneration).toMatchObject({
      calls: 1,
      inputTokens: 1000,
      outputTokens: 500
    })
    expect(updated.status).toBe('prepared')
    expect(repository.getInterview(interview.id).aiUsage?.calls).toBe(1)
  })

  // SPEC-021 · AC-02
  it('adds the note generation usage to the same interview accumulate as the script', async () => {
    const { interview, noteTemplateId } = seedInterview()
    harness.create.mockResolvedValueOnce(
      sdkResponse(SCRIPT_JSON, { input_tokens: 1000, output_tokens: 500 })
    )
    await generateInterviewScript(interview.id)

    harness.create.mockResolvedValueOnce(
      sdkResponse(NOTE_JSON, { input_tokens: 3000, output_tokens: 700 })
    )
    const result = await generateInterviewNote(interview.id, noteTemplateId)

    expect(result.interview.aiUsage).toMatchObject({
      calls: 2,
      inputTokens: 4000,
      outputTokens: 1200
    })
    expect(result.interview.aiUsage?.estimatedCostUsd).toBeCloseTo(
      computeCostUsd('claude-opus-4-8', 1000, 500) + computeCostUsd('claude-opus-4-8', 3000, 700),
      10
    )
    // Cada generación queda atribuida a su tarea (revisión de coste 2026-07)
    expect(result.interview.aiUsage?.byTask?.scriptGeneration?.calls).toBe(1)
    expect(result.interview.aiUsage?.byTask?.noteGeneration?.calls).toBe(1)
  })

  // SPEC-021 · AC-04 (generaciones manuales: una llamada que falla no mide nada)
  it('leaves the accumulate untouched when the LLM call fails', async () => {
    const { interview } = seedInterview()
    harness.create.mockRejectedValueOnce(new harness.errors.APIConnectionError('sin conexión'))

    const caught = await generateInterviewScript(interview.id).then(
      () => null,
      (error: unknown) => error
    )

    expect(caught).toBeInstanceOf(LlmOperationError)
    expect(repository.getInterview(interview.id).aiUsage).toBeUndefined()

    // Una respuesta con formato inválido tampoco mide (el registro va tras el parseo)
    harness.create.mockResolvedValueOnce(sdkResponse({ nada: true }, { input_tokens: 999 }))
    await generateInterviewScript(interview.id).catch(() => null)
    expect(repository.getInterview(interview.id).aiUsage).toBeUndefined()
  })

  // SPEC-021 · AC-14 (el límite solo pausa el asistente: las manuales se ejecutan)
  it('runs the manual generation even when the interview cost already reached the configured limit', async () => {
    const { interview } = seedInterview()
    repository.setAiCostSettings({ limitUsd: 0.01 })
    // Acumulado ya por encima del límite
    repository.addInterviewAiUsage(interview.id, {
      calls: 3,
      inputTokens: 10_000,
      outputTokens: 5_000,
      estimatedCostUsd: 0.5
    })
    harness.create.mockResolvedValue(
      sdkResponse(SCRIPT_JSON, { input_tokens: 100, output_tokens: 50 })
    )

    const updated = await generateInterviewScript(interview.id)

    // La generación manual NO se bloquea y sigue midiendo
    expect(harness.create).toHaveBeenCalledTimes(1)
    expect(updated.status).toBe('prepared')
    expect(updated.aiUsage?.calls).toBe(4)
  })

  // SPEC-021 · AC-16 (respuesta sin bloque usage → llamada con 0 tokens, todo sigue)
  it('counts the call with 0 tokens without breaking the generation when the response has no usage block', async () => {
    const { interview } = seedInterview()
    harness.create.mockResolvedValue(sdkResponse(SCRIPT_JSON, undefined))

    const updated = await generateInterviewScript(interview.id)

    expect(updated.status).toBe('prepared')
    expect(updated.aiUsage).toMatchObject({
      calls: 1,
      inputTokens: 0,
      outputTokens: 0,
      estimatedCostUsd: 0
    })
  })
})
