/**
 * SPEC-059 (AC-01..AC-07): los dos botones de desacople en las páginas de
 * detalle — «Abrir asistente en ventana» en la cabecera de la sección del
 * asistente y «Abrir guión en ventana» en la cabecera de la sección Guión,
 * ambos SOLO durante la grabación, y el del asistente deshabilitado con
 * Tooltip explicativo en `no-key`.
 * Generated by QA Dev agent.
 *
 * Arnés heredado de AssistantLiveSection.test.tsx (SPEC-041): páginas reales
 * bajo <Layout/> con los servicios del spike mockeados
 * (permissionsService/captureService/wavRecorderService) y el bridge
 * window.api como frontera; el estado del asistente se inyecta con
 * emitAssistantUpdate.
 *
 * Lecciones aplicadas: nunca se cuentan botones de la sección (se filtra por
 * el data-testid nuevo, lección SPEC-058 §1); máximo UN hover de tooltip por
 * `it` (la grace area de Radix queda anclada tras el primer unhover) y el
 * texto del TooltipContent se renderiza DOS veces en jsdom → findAllByText;
 * el heading «Guión» es asíncrono (NoteScriptSections resuelve la nota) →
 * findByRole.
 */
import { act, render, screen, within, type RenderResult } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { Layout } from '@/components/layout/Layout'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { CaptureDetailPage } from '@/pages/CaptureDetailPage'
import { InterviewDetailPage } from '@/pages/InterviewDetailPage'
import {
  acquireMicrophoneStream,
  acquireSystemAudioStream,
  listAudioInputDevices
} from '@/services/captureService'
import { getPermissionsStatus } from '@/services/permissionsService'
import type { Company, Discovery, Interview } from '@/types/domain'
import { createFakeAudioStream } from '../../helpers/fakeMediaStream'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

vi.mock('@/services/permissionsService', () => ({
  getPermissionsStatus: vi.fn(),
  requestMicrophoneAccess: vi.fn(),
  openPrivacySettings: vi.fn()
}))

vi.mock('@/services/captureService', () => ({
  DEFAULT_DEVICE_ID: '__default__',
  acquireMicrophoneStream: vi.fn(),
  acquireSystemAudioStream: vi.fn(),
  listAudioInputDevices: vi.fn(),
  stopStream: vi.fn()
}))

vi.mock('@/services/wavRecorderService', () => ({
  CAPTURE_SAMPLE_RATE: 16000,
  WavRecorderService: class {
    start = vi.fn()
    stop = vi.fn()
    getLevels = vi.fn(() => ({ microphone: 0, system: 0 }))
    readonly durationSeconds = 0
    readonly samplesWritten = 0
  }
}))

let mockApi: MockApiHandle

const NO_KEY_REASON =
  'Configura tu clave de Anthropic en Ajustes para abrir el asistente en una ventana'

const COMPANY: Company = {
  id: 'c-1',
  name: 'Acme Corp',
  website: null,
  linkedinUrl: null,
  createdAt: '2026-07-02T12:00:00.000Z',
  updatedAt: '2026-07-02T12:00:00.000Z'
}

const DISCOVERY: Discovery = {
  id: 'd-1',
  name: 'Vertical Sanidad',
  objectives: null,
  createdAt: '2026-07-01T09:00:00.000Z',
  updatedAt: '2026-07-01T09:00:00.000Z'
}

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactIds: [],
    interviewGroupId: null,
    templateId: 'tpl-1',
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: null,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

/** Captura sin empresa (SPEC-020): el detalle de captura de la misma sesión. */
function capture(overrides: Partial<Interview> = {}): Interview {
  return interview({ companyId: null, title: 'Captura sin empresa', ...overrides })
}

function renderInterviewDetail(): RenderResult {
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/discoveries/d-1/companies/c-1/interviews/i-1']}>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route
              path="discoveries/:discoveryId/companies/:companyId/interviews/:interviewId"
              element={<InterviewDetailPage />}
            />
          </Route>
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

function renderCaptureDetail(): RenderResult {
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: capture() })
  vi.mocked(mockApi.api.db.getDiscovery).mockResolvedValue({ ok: true, data: DISCOVERY })
  return render(
    <TooltipProvider>
      <MemoryRouter initialEntries={['/captures/i-1']}>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route path="captures/:id" element={<CaptureDetailPage />} />
          </Route>
        </Routes>
      </MemoryRouter>
      <Toaster />
    </TooltipProvider>
  )
}

/** Arranca la grabación de entrevista atravesando el consentimiento (SPEC-019). */
async function startRecording(user: ReturnType<typeof userEvent.setup>): Promise<void> {
  await user.click(await screen.findByRole('button', { name: 'Iniciar grabación' }))
  const consent = await screen.findByRole('alertdialog')
  await user.click(within(consent).getByRole('button', { name: 'Entendido, iniciar grabación' }))
  await screen.findByRole('button', { name: 'Detener' })
}

/** Arranca la captura desde el botón de la cabecera (SPEC-034) + consentimiento. */
async function startFromHeader(user: ReturnType<typeof userEvent.setup>): Promise<void> {
  await user.click(await screen.findByTestId('topbar-start-button'))
  const consent = await screen.findByRole('alertdialog')
  await user.click(within(consent).getByRole('button', { name: 'Entendido, iniciar grabación' }))
  await screen.findByRole('button', { name: 'Detener' })
}

/** La sección Guión completa (el heading vive en su cabecera). */
async function scriptSection(): Promise<HTMLElement> {
  const heading = await screen.findByRole('heading', { name: 'Guión' })
  const section = heading.closest('section')
  if (section === null) {
    throw new Error('El heading «Guión» no está dentro de una <section>')
  }
  return section
}

beforeEach(() => {
  vi.clearAllMocks()
  window.localStorage.clear()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: interview() })
  vi.mocked(mockApi.api.db.getCompany).mockResolvedValue({ ok: true, data: COMPANY })
  vi.mocked(mockApi.api.llm.getStatus).mockResolvedValue({
    ok: true,
    data: { hasAnthropicKey: true }
  })
  vi.mocked(listAudioInputDevices).mockResolvedValue([])
  vi.mocked(getPermissionsStatus).mockResolvedValue({
    microphone: 'granted',
    systemAudio: 'granted'
  })
  vi.mocked(acquireMicrophoneStream).mockResolvedValue(createFakeAudioStream().stream)
  vi.mocked(acquireSystemAudioStream).mockResolvedValue(createFakeAudioStream().stream)
})

describe('DetachWindowButton en las páginas de detalle (SPEC-059)', () => {
  describe('interview detail', () => {
    // SPEC-059 · AC-01
    it('shows an icon-only «Abrir asistente en ventana» button in the assistant section header while recording', async () => {
      const user = userEvent.setup()
      renderInterviewDetail()
      await startRecording(user)

      const section = await screen.findByTestId('assistant-live-section')
      const button = within(section).getByTestId('detach-assistant-button')
      expect(button).toHaveAccessibleName('Abrir asistente en ventana')
      // Icon-only: sin texto visible que compita con el contenido glanceable
      expect(button.textContent).toBe('')
      expect(button).toBeEnabled()
    })

    // SPEC-059 · AC-02
    it('shows the «Abrir guión en ventana» button next to the existing Guión header controls while recording', async () => {
      const user = userEvent.setup()
      renderInterviewDetail()
      await startRecording(user)

      const section = await scriptSection()
      const button = within(section).getByTestId('detach-script-button')
      expect(button).toHaveAccessibleName('Abrir guión en ventana')
      expect(button.textContent).toBe('')
      // Junto a los controles existentes: comparte el contenedor de la fila de
      // cabecera con el botón de generación. Hay DOS «Generar guión» en la
      // sección (cabecera + empty state, lección SPEC-014) → se filtra por el
      // contenedor, sin contar los botones de la sección
      const controls = button.closest('div')
      expect(controls).not.toBeNull()
      expect(
        within(controls as HTMLElement).getAllByRole('button', { name: 'Generar guión' })
      ).toHaveLength(1)
    })

    // SPEC-059 · AC-04
    it('does not render either detach button without a recording in progress', async () => {
      renderInterviewDetail()

      // Ancla de sincronización: la página está en preparación
      expect(await screen.findByRole('button', { name: 'Iniciar grabación' })).toBeInTheDocument()
      const section = await scriptSection()
      expect(within(section).queryByTestId('detach-script-button')).not.toBeInTheDocument()
      expect(screen.queryByTestId('detach-assistant-button')).not.toBeInTheDocument()
    })

    // SPEC-059 · AC-05
    it('disables the assistant detach button with an explanatory Tooltip while the assistant is in no-key', async () => {
      const user = userEvent.setup()
      renderInterviewDetail()
      await startRecording(user)
      act(() => {
        mockApi.emitAssistantUpdate({
          state: 'no-key',
          queue: { pending: [], pinned: [] },
          objectivesMet: []
        })
      })

      const section = await screen.findByTestId('assistant-live-section')
      const button = within(section).getByTestId('detach-assistant-button')
      expect(button).toBeDisabled()
      // Único hover del test: el span envoltorio es el trigger (los elementos
      // disabled no disparan hover). Radix duplica el contenido → findAllByText
      await user.hover(button.parentElement as HTMLElement)
      expect((await screen.findAllByText(NO_KEY_REASON)).length).toBeGreaterThanOrEqual(1)
      expect(vi.mocked(mockApi.api.window.openDetached)).not.toHaveBeenCalled()
    })

    // SPEC-059 · AC-06
    it('asks main to open the assistant window for the interview when the assistant button is pressed', async () => {
      const user = userEvent.setup()
      renderInterviewDetail()
      await startRecording(user)

      const section = await screen.findByTestId('assistant-live-section')
      await user.click(within(section).getByTestId('detach-assistant-button'))

      expect(vi.mocked(mockApi.api.window.openDetached)).toHaveBeenCalledWith('assistant', 'i-1')
    })

    // SPEC-059 · AC-07
    it('asks main to open the script window for the interview when the script button is pressed', async () => {
      const user = userEvent.setup()
      renderInterviewDetail()
      await startRecording(user)

      const section = await scriptSection()
      await user.click(within(section).getByTestId('detach-script-button'))

      expect(vi.mocked(mockApi.api.window.openDetached)).toHaveBeenCalledWith('script', 'i-1')
    })
  })

  describe('capture detail', () => {
    // SPEC-059 · AC-03
    it('renders both detach buttons on the capture detail while recording, wired to the same capture', async () => {
      const user = userEvent.setup()
      renderCaptureDetail()
      await startFromHeader(user)

      const assistantSection = await screen.findByTestId('assistant-live-section')
      const assistantButton = within(assistantSection).getByTestId('detach-assistant-button')
      expect(assistantButton).toHaveAccessibleName('Abrir asistente en ventana')
      const section = await scriptSection()
      const scriptButton = within(section).getByTestId('detach-script-button')
      expect(scriptButton).toHaveAccessibleName('Abrir guión en ventana')

      await user.click(scriptButton)
      expect(vi.mocked(mockApi.api.window.openDetached)).toHaveBeenCalledWith('script', 'i-1')
    })

    // SPEC-059 · AC-04 (variante captura)
    it('does not render the script detach button on the capture detail without a recording in progress', async () => {
      renderCaptureDetail()

      expect(await screen.findByTestId('topbar-start-button')).toBeInTheDocument()
      const section = await scriptSection()
      expect(within(section).queryByTestId('detach-script-button')).not.toBeInTheDocument()
      expect(screen.queryByTestId('detach-assistant-button')).not.toBeInTheDocument()
    })
  })
})
