/**
 * SPEC-062: las rutas /detached/* del HashRouter real (App.tsx) — el mismo
 * hash que main construye con `detachedWindowHash` debe resolver a la vista
 * del componente y FUERA del Layout (sin sidebar ni top bar), sin que el splat
 * 404 del Layout las capture. Una desincronización aquí sería un fallo mudo
 * (ventana en blanco o 404 dentro de la ventana secundaria).
 * Generated by QA Dev agent.
 *
 * Frontera de mocking: bridge window.api (installMockApi). Se monta <App/>
 * entero con el hash puesto a mano, que es exactamente lo que hace la ventana
 * secundaria al cargar.
 */
import { render, screen } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import App from '@/App'
import { detachedWindowHash } from '@/types/detached'
import type { Interview } from '@/types/domain'
import { installProseMirrorJsdomPolyfills } from '../../helpers/prosemirrorJsdom'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

const INTERVIEW: Interview = {
  id: 'i-1',
  discoveryId: 'd-1',
  companyId: 'c-1',
  contactIds: [],
  interviewGroupId: null,
  templateId: 'tpl-1',
  title: 'Discovery con Acme',
  status: 'draft',
  scriptMarkdown: '# Guión adaptado',
  objectives: [],
  wavPath: null,
  transcriptPath: null,
  createdAt: '2026-07-04T10:00:00.000Z',
  updatedAt: '2026-07-04T10:00:00.000Z'
}

beforeEach(() => {
  vi.clearAllMocks()
  installProseMirrorJsdomPolyfills()
  mockApi = installMockApi()
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue({ ok: true, data: INTERVIEW })
})

describe('rutas /detached/* del router real (SPEC-062)', () => {
  it('resolves the assistant hash built by main to the assistant window view, outside the Layout', async () => {
    window.location.hash = `#${detachedWindowHash('assistant', 'i-1')}`

    render(<App />)

    expect(await screen.findByTestId('assistant-window-root')).toBeInTheDocument()
    expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
    expect(screen.queryByRole('banner')).not.toBeInTheDocument()
    // No cae en el splat 404 del Layout
    expect(screen.queryByText('Página no encontrada')).not.toBeInTheDocument()
  })

  it('resolves the script hash built by main to the script window view, outside the Layout', async () => {
    window.location.hash = `#${detachedWindowHash('script', 'i-1')}`

    render(<App />)

    expect(await screen.findByTestId('script-window-root')).toBeInTheDocument()
    expect(await screen.findByTestId('script-window-markdown')).toBeInTheDocument()
    expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
    expect(screen.queryByRole('banner')).not.toBeInTheDocument()
    expect(screen.queryByText('Página no encontrada')).not.toBeInTheDocument()
  })
})
