// @vitest-environment node
/**
 * SPEC-059: señal `db:interview-updated` — main difunde la entrevista
 * persistida por los caminos que tocan el guión para que la ventana
 * desacoplada muestre la versión nueva sin reabrirla. Aquí se cubre el camino
 * del GUARDADO MANUAL (`db:interview:update`, src/main/db/ipc.ts), que no
 * difunda cuando la mutación falla, que los demás canales de mutación no
 * amplíen la superficie, y que el disparo AUTOMÁTICO de SPEC-033 NO emita la
 * señal (invariante «nada duplicado»).
 * Generated by QA Dev agent.
 *
 * `electron` mockeado: ipcMain captura los handlers registrados y
 * BrowserWindow.getAllWindows devuelve dos ventanas falsas que registran los
 * envíos (patrón scriptAutoGenerationService.test.ts). Store y repository
 * REALES sobre un directorio temporal.
 */
import { mkdtempSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import type { IpcMainInvokeEvent } from 'electron'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { registerDbIpcHandlers } from '../../../src/main/db/ipc'
import * as repository from '../../../src/main/db/repository'
import { generateInterviewScript } from '../../../src/main/llmService'
import { autoGenerateInterviewScript } from '../../../src/main/scriptAutoGenerationService'
import type { DbResult, Interview } from '../../../src/renderer/src/types/domain'

const harness = vi.hoisted(() => ({
  storeDir: '',
  /** Handlers registrados por registerDbIpcHandlers, por canal. */
  handlers: new Map<string, (event: unknown, ...args: unknown[]) => unknown>(),
  /** Envíos a las ventanas: { ventana, canal, payload }. */
  sent: [] as Array<{ window: number; channel: string; payload: unknown }>
}))

vi.mock('electron', () => ({
  app: {
    getPath: (): string => harness.storeDir
  },
  ipcMain: {
    handle: (channel: string, listener: (event: unknown, ...args: unknown[]) => unknown): void => {
      harness.handlers.set(channel, listener)
    },
    on: (): void => undefined
  },
  BrowserWindow: {
    getAllWindows: (): unknown[] =>
      [0, 1].map((index) => ({
        webContents: {
          isDestroyed: (): boolean => false,
          send: (channel: string, payload: unknown): void => {
            harness.sent.push({ window: index, channel, payload })
          }
        }
      }))
  },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

// La generación en sí no es el objeto de esta suite: solo el camino automático
// y lo que emite (o deja de emitir) al terminar.
vi.mock('../../../src/main/llmService', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../../../src/main/llmService')>()),
  generateInterviewScript: vi.fn()
}))

function callHandler<T>(channel: string, ...args: unknown[]): T {
  const handler = harness.handlers.get(channel)
  if (handler === undefined) {
    throw new Error(`Canal no registrado: ${channel}`)
  }
  return handler({} as IpcMainInvokeEvent, ...args) as T
}

function broadcasts(channel: string): Array<{ window: number; payload: unknown }> {
  return harness.sent
    .filter((entry) => entry.channel === channel)
    .map(({ window, payload }) => ({ window, payload }))
}

let interviewId = ''

beforeEach(() => {
  vi.clearAllMocks()
  harness.handlers.clear()
  harness.sent.length = 0
  harness.storeDir = mkdtempSync(join(tmpdir(), 'maurya-interview-updated-'))
  process.env['ANTHROPIC_API_KEY'] = 'sk-ant-test'
  registerDbIpcHandlers()
  const discovery = repository.createDiscovery({ name: 'Discovery Maurya' })
  const template = repository.createInterviewTemplate({
    name: 'Plantilla',
    blocks: [{ title: 'Bloque', questions: [{ text: '¿Cómo lo hacéis hoy?' }] }]
  })
  interviewId = repository.createInterview({
    discoveryId: discovery.id,
    title: 'Entrevista',
    templateId: template.id
  }).id
})

describe('db:interview-updated (SPEC-059)', () => {
  it('broadcasts the persisted interview to every window after a manual script save', () => {
    const result = callHandler<DbResult<Interview>>('db:interview:update', interviewId, {
      scriptMarkdown: '# Guión editado a mano'
    })

    expect(result.ok).toBe(true)
    const sent = broadcasts('db:interview-updated')
    // Una entrega por ventana, con la entrevista ya persistida
    expect(sent.map((entry) => entry.window)).toEqual([0, 1])
    expect((sent[0].payload as Interview).scriptMarkdown).toBe('# Guión editado a mano')
    expect((sent[0].payload as Interview).id).toBe(interviewId)
  })

  it('does not broadcast when the mutation throws (the envelope still carries the error)', () => {
    const result = callHandler<DbResult<Interview>>('db:interview:update', 'i-inexistente', {
      scriptMarkdown: '# Guión'
    })

    expect(result.ok).toBe(false)
    expect(broadcasts('db:interview-updated')).toEqual([])
  })

  it('keeps the broadcast surface to the paths that touch the script', () => {
    const result = callHandler<DbResult<Interview>>('db:interview:confirm-objectives', interviewId)

    expect(result.ok).toBe(true)
    expect(broadcasts('db:interview-updated')).toEqual([])
  })

  it('does not broadcast db:interview-updated from the automatic script generation (SPEC-033)', async () => {
    const updated = repository.getInterview(interviewId)
    vi.mocked(generateInterviewScript).mockResolvedValue({
      ...updated,
      scriptMarkdown: '# Guión autogenerado'
    })

    autoGenerateInterviewScript(interviewId)
    await vi.waitFor(() =>
      expect(
        harness.sent.some(
          (entry) =>
            entry.channel === 'llm:script-generation' &&
            (entry.payload as { status: string }).status === 'done'
        )
      ).toBe(true)
    )

    expect(broadcasts('db:interview-updated')).toEqual([])
    // El camino automático sigue difundiendo su propio evento a TODAS las
    // ventanas (generating + done, una entrega por ventana cada uno)
    expect(broadcasts('llm:script-generation')).toHaveLength(4)
  })
})
