// @vitest-environment node
/**
 * SPEC-062: canales de main que sostienen las ventanas desacopladas
 * (src/main/ipc.ts) — `window:open-detached` con validación en frontera
 * (fire-and-forget, patrón `window:set-theme`), `assistant:get-snapshot` para
 * la hidratación, la difusión de `db:interview-updated` desde la generación
 * MANUAL del guión y el cierre de las ventanas al parar la grabación.
 * Generated by QA Dev agent.
 *
 * `electron` mockeado: ipcMain captura los handlers/listeners registrados y
 * BrowserWindow.getAllWindows devuelve una ventana falsa que registra los
 * envíos. Los servicios que el registro invoca se mockean parcialmente
 * (importOriginal) para que solo se ejerciten los caminos de esta spec.
 */
import type { IpcMainInvokeEvent } from 'electron'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { registerIpcHandlers } from '../../../src/main/ipc'
import { closeDetachedWindows, openDetachedWindow } from '../../../src/main/detachedWindows'
import { getAssistantSnapshot } from '../../../src/main/assistantService'
import { generateInterviewScript } from '../../../src/main/llmService'
import { finishTranscription, persistTranscript } from '../../../src/main/transcriptionService'
import { stopRecording } from '../../../src/main/wavFileService'
import type { AssistantUpdateEvent } from '../../../src/renderer/src/types/assistant'
import type { StopResult } from '../../../src/renderer/src/types/audio'
import type { Interview } from '../../../src/renderer/src/types/domain'
import type { LlmResult } from '../../../src/renderer/src/types/llm'

const harness = vi.hoisted(() => ({
  handlers: new Map<string, (event: unknown, ...args: unknown[]) => unknown>(),
  listeners: new Map<string, (event: unknown, ...args: unknown[]) => void>(),
  sent: [] as Array<{ channel: string; payload: unknown }>
}))

vi.mock('electron', () => ({
  app: { getPath: (): string => '/tmp/maurya-main-ipc-detached' },
  ipcMain: {
    handle: (channel: string, listener: (event: unknown, ...args: unknown[]) => unknown): void => {
      harness.handlers.set(channel, listener)
    },
    on: (channel: string, listener: (event: unknown, ...args: unknown[]) => void): void => {
      harness.listeners.set(channel, listener)
    }
  },
  BrowserWindow: {
    getAllWindows: (): unknown[] => [
      {
        webContents: {
          isDestroyed: (): boolean => false,
          send: (channel: string, payload: unknown): void => {
            harness.sent.push({ channel, payload })
          }
        }
      }
    ]
  },
  nativeTheme: {},
  shell: { openExternal: vi.fn(), showItemInFolder: vi.fn() },
  safeStorage: {
    isEncryptionAvailable: (): boolean => true,
    encryptString: (plain: string): Buffer => Buffer.from(plain, 'utf8'),
    decryptString: (blob: Buffer): string => blob.toString('utf8')
  }
}))

// Registro de los canales db:* (suite propia: interviewUpdatedBroadcast) y
// almacén de secretos: fuera del alcance de esta suite.
vi.mock('../../../src/main/db/ipc', () => ({ registerDbIpcHandlers: vi.fn() }))
vi.mock('../../../src/main/secretsService', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../../../src/main/secretsService')>()),
  initSecrets: vi.fn()
}))
vi.mock('../../../src/main/detachedWindows', () => ({
  openDetachedWindow: vi.fn(),
  closeDetachedWindows: vi.fn()
}))
vi.mock('../../../src/main/llmService', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../../../src/main/llmService')>()),
  generateInterviewScript: vi.fn()
}))
vi.mock('../../../src/main/assistantService', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../../../src/main/assistantService')>()),
  getAssistantSnapshot: vi.fn(),
  peekAssistantObjectivesMet: vi.fn(() => []),
  stopAssistant: vi.fn(() => null)
}))
vi.mock('../../../src/main/transcriptionService', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../../../src/main/transcriptionService')>()),
  finishTranscription: vi.fn(),
  persistTranscript: vi.fn(),
  resetTranscription: vi.fn()
}))
vi.mock('../../../src/main/wavFileService', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../../../src/main/wavFileService')>()),
  stopRecording: vi.fn()
}))

function invoke<T>(channel: string, ...args: unknown[]): T {
  const handler = harness.handlers.get(channel)
  if (handler === undefined) {
    throw new Error(`Canal no registrado: ${channel}`)
  }
  return handler({} as IpcMainInvokeEvent, ...args) as T
}

function send(channel: string, ...args: unknown[]): void {
  const listener = harness.listeners.get(channel)
  if (listener === undefined) {
    throw new Error(`Canal no registrado: ${channel}`)
  }
  listener({}, ...args)
}

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: null,
    contactIds: [],
    interviewGroupId: null,
    templateId: 'tpl-1',
    title: 'Entrevista',
    status: 'prepared',
    scriptMarkdown: '# Guión regenerado',
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

beforeEach(() => {
  vi.clearAllMocks()
  harness.handlers.clear()
  harness.listeners.clear()
  harness.sent.length = 0
  registerIpcHandlers()
})

describe('canales de main de las ventanas desacopladas (SPEC-062)', () => {
  describe('window:open-detached', () => {
    it('asks the lifecycle module to open the window of the requested component', () => {
      send('window:open-detached', 'assistant', 'i-1')
      send('window:open-detached', 'script', 'i-1')

      expect(vi.mocked(openDetachedWindow)).toHaveBeenNthCalledWith(1, 'assistant', 'i-1')
      expect(vi.mocked(openDetachedWindow)).toHaveBeenNthCalledWith(2, 'script', 'i-1')
    })

    it('ignores an unexpected payload in silence (frontier validation)', () => {
      send('window:open-detached', 'objectives', 'i-1')
      send('window:open-detached', 'assistant', '')
      send('window:open-detached', 'assistant', 42)
      send('window:open-detached', undefined, undefined)

      expect(vi.mocked(openDetachedWindow)).not.toHaveBeenCalled()
    })
  })

  describe('assistant:get-snapshot', () => {
    it('returns the last emitted assistant event so the detached window can hydrate', () => {
      const snapshot: AssistantUpdateEvent = {
        state: 'active',
        queue: { pending: [], pinned: [] },
        objectivesMet: [1]
      }
      vi.mocked(getAssistantSnapshot).mockReturnValue(snapshot)

      expect(invoke<AssistantUpdateEvent | null>('assistant:get-snapshot')).toEqual(snapshot)
    })

    it('returns null without a live session', () => {
      vi.mocked(getAssistantSnapshot).mockReturnValue(null)

      expect(invoke<AssistantUpdateEvent | null>('assistant:get-snapshot')).toBeNull()
    })
  })

  describe('llm:generate-script', () => {
    it('broadcasts the persisted interview after a manual generation', async () => {
      const generated = interview()
      vi.mocked(generateInterviewScript).mockResolvedValue(generated)

      const result = await invoke<Promise<LlmResult<Interview>>>('llm:generate-script', 'i-1')

      expect(result).toEqual({ ok: true, data: generated })
      expect(harness.sent).toEqual([{ channel: 'db:interview-updated', payload: generated }])
    })

    it('does not broadcast when the generation fails', async () => {
      vi.mocked(generateInterviewScript).mockRejectedValue(new Error('sin clave'))

      const result = await invoke<Promise<LlmResult<Interview>>>('llm:generate-script', 'i-1')

      expect(result.ok).toBe(false)
      expect(harness.sent).toEqual([])
    })
  })

  describe('recording:stop', () => {
    it('closes the detached windows when the recording stops', async () => {
      vi.mocked(stopRecording).mockReturnValue({
        filePath: '/tmp/rec.wav',
        durationSeconds: 5,
        sizeBytes: 44,
        sampleRate: 16000,
        channels: 2
      } as ReturnType<typeof stopRecording>)
      vi.mocked(persistTranscript).mockReturnValue({ transcriptPath: null, latency: null })
      vi.mocked(finishTranscription).mockResolvedValue(undefined)

      await invoke<Promise<StopResult>>('recording:stop')

      expect(vi.mocked(closeDetachedWindows)).toHaveBeenCalledTimes(1)
    })
  })
})
