/**
 * SPEC-062 (AC-17..AC-20): vista de la ventana desacoplada del guión — el
 * guión renderizado como markdown de SOLO LECTURA a ventana completa, empty
 * state sin CTA, error state con «Reintentar» y actualización en vivo cuando
 * main difunde la entrevista persistida (`db:interview-updated`).
 * Generated by QA Dev agent.
 *
 * Frontera de mocking: bridge window.api (installMockApi); el evento de
 * difusión se inyecta con emitInterviewUpdated. La página se monta en su ruta
 * real (DETACHED_ROUTES.script, el mismo módulo con el que main construye el
 * hash). MarkdownView es el REAL (TipTap): jsdom necesita los polyfills de
 * geometría de ProseMirror.
 */
import { act, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { ScriptWindowPage } from '@/pages/ScriptWindowPage'
import { DETACHED_ROUTES } from '@/types/detached'
import type { DbResult, Interview } from '@/types/domain'
import { installProseMirrorJsdomPolyfills } from '../../helpers/prosemirrorJsdom'
import { installMockApi, type MockApiHandle } from '../../helpers/mockApi'

let mockApi: MockApiHandle

const SCRIPT_MD = '# Guión adaptado\n\n## Bloque 1\n\nPregunta adaptada a Acme'
const UPDATED_MD = '# Guión regenerado\n\n## Bloque 1\n\nPregunta nueva tras regenerar'

function interview(overrides: Partial<Interview> = {}): Interview {
  return {
    id: 'i-1',
    discoveryId: 'd-1',
    companyId: 'c-1',
    contactIds: [],
    interviewGroupId: null,
    templateId: 'tpl-1',
    title: 'Discovery con Acme',
    status: 'draft',
    scriptMarkdown: SCRIPT_MD,
    objectives: [],
    wavPath: null,
    transcriptPath: null,
    createdAt: '2026-07-04T10:00:00.000Z',
    updatedAt: '2026-07-04T10:00:00.000Z',
    ...overrides
  }
}

function setInterview(result: DbResult<Interview>): void {
  vi.mocked(mockApi.api.db.getInterview).mockResolvedValue(result)
}

function renderScriptWindow(): void {
  render(
    <MemoryRouter initialEntries={['/detached/script/i-1']}>
      <Routes>
        <Route path={DETACHED_ROUTES.script} element={<ScriptWindowPage />} />
      </Routes>
    </MemoryRouter>
  )
}

beforeEach(() => {
  vi.clearAllMocks()
  installProseMirrorJsdomPolyfills()
  mockApi = installMockApi()
})

describe('ScriptWindowPage (ventana desacoplada del guión, SPEC-062)', () => {
  // SPEC-062 · AC-17
  it('renders the script as read-only markdown at full window, without editor or save/regenerate controls', async () => {
    setInterview({ ok: true, data: interview() })
    renderScriptWindow()

    const root = await screen.findByTestId('script-window-root')
    const view = await screen.findByTestId('script-window-markdown')
    // Markdown renderizado, no crudo
    const heading = within(view).getByText('Guión adaptado')
    expect(heading.closest('h1')).not.toBeNull()
    expect(within(view).getByText('Bloque 1').closest('h2')).not.toBeNull()
    expect(view.textContent).not.toContain('#')
    // Solo lectura: el área de TipTap no es editable y no hay toolbar
    expect(view.querySelector('[contenteditable="true"]')).toBeNull()
    expect(within(root).queryByRole('toolbar')).not.toBeInTheDocument()
    expect(within(root).queryByRole('button')).not.toBeInTheDocument()
    // Sin chrome de la app: la vista vive fuera del Layout
    expect(screen.queryByRole('banner')).not.toBeInTheDocument()
    expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
  })

  it('shows loading placeholders while the interview is being read', async () => {
    vi.mocked(mockApi.api.db.getInterview).mockReturnValue(
      new Promise<DbResult<Interview>>(() => undefined)
    )
    renderScriptWindow()

    const root = await screen.findByTestId('script-window-root')
    expect(root.querySelectorAll('[data-slot="skeleton"]').length).toBeGreaterThan(0)
    expect(screen.queryByTestId('script-window-markdown')).not.toBeInTheDocument()
    expect(screen.queryByTestId('script-window-empty')).not.toBeInTheDocument()
    expect(screen.queryByTestId('script-window-error')).not.toBeInTheDocument()
  })

  // SPEC-062 · AC-18
  it('shows the empty state without any CTA when the interview has no script', async () => {
    setInterview({ ok: true, data: interview({ scriptMarkdown: null }) })
    renderScriptWindow()

    const empty = await screen.findByTestId('script-window-empty')
    expect(within(empty).getByText('Esta entrevista no tiene guión.')).toBeInTheDocument()
    expect(within(empty).queryByRole('button')).not.toBeInTheDocument()
    expect(within(empty).queryByRole('link')).not.toBeInTheDocument()
    expect(screen.queryByTestId('script-window-markdown')).not.toBeInTheDocument()
  })

  // SPEC-062 · AC-19
  it('shows the updated script when main broadcasts the persisted interview, without reopening the window', async () => {
    setInterview({ ok: true, data: interview() })
    renderScriptWindow()
    expect(await screen.findByText('Guión adaptado')).toBeInTheDocument()

    act(() => {
      mockApi.emitInterviewUpdated(interview({ scriptMarkdown: UPDATED_MD }))
    })

    await waitFor(() => expect(screen.getByText('Guión regenerado')).toBeInTheDocument())
    expect(screen.queryByText('Guión adaptado')).not.toBeInTheDocument()
    // Sin re-consultar el almacén: el evento trae la entrevista ya persistida
    expect(vi.mocked(mockApi.api.db.getInterview)).toHaveBeenCalledTimes(1)
  })

  // SPEC-062 · AC-19 (la difusión de OTRA entrevista no toca esta ventana)
  it('ignores the broadcast of a different interview', async () => {
    setInterview({ ok: true, data: interview() })
    renderScriptWindow()
    expect(await screen.findByText('Guión adaptado')).toBeInTheDocument()

    act(() => {
      mockApi.emitInterviewUpdated(interview({ id: 'i-otra', scriptMarkdown: UPDATED_MD }))
    })

    expect(screen.getByText('Guión adaptado')).toBeInTheDocument()
    expect(screen.queryByText('Guión regenerado')).not.toBeInTheDocument()
  })

  // SPEC-062 · AC-20
  it('shows an error state with «Reintentar» when the read fails, and recovers on retry', async () => {
    const user = userEvent.setup()
    setInterview({ ok: false, error: { kind: 'not-found', message: 'Entrevista no encontrada' } })
    renderScriptWindow()

    const errorState = await screen.findByTestId('script-window-error')
    expect(within(errorState).getByText('Entrevista no encontrada')).toBeInTheDocument()
    expect(screen.queryByTestId('script-window-markdown')).not.toBeInTheDocument()
    // El error tiene prioridad sobre el vacío: sin entrevista legible no se
    // sabe siquiera si hay guión
    expect(screen.queryByTestId('script-window-empty')).not.toBeInTheDocument()

    setInterview({ ok: true, data: interview() })
    await user.click(within(errorState).getByRole('button', { name: 'Reintentar' }))

    expect(await screen.findByTestId('script-window-markdown')).toBeInTheDocument()
    expect(screen.queryByTestId('script-window-error')).not.toBeInTheDocument()
    expect(vi.mocked(mockApi.api.db.getInterview)).toHaveBeenCalledTimes(2)
  })

  // SPEC-062 · AC-19 + AC-20 (una versión nueva difundida supera el error)
  it('leaves the error state when a newer version of the interview is broadcast', async () => {
    setInterview({ ok: false, error: { kind: 'storage', message: 'Almacén ilegible' } })
    renderScriptWindow()
    expect(await screen.findByTestId('script-window-error')).toBeInTheDocument()

    act(() => {
      mockApi.emitInterviewUpdated(interview({ scriptMarkdown: UPDATED_MD }))
    })

    expect(await screen.findByText('Guión regenerado')).toBeInTheDocument()
    expect(screen.queryByTestId('script-window-error')).not.toBeInTheDocument()
  })
})
